### ISSUE TITLE
Premake configuration not working on Ubuntu16.04

### ISSUE THREAD

**Issue by realitix** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#10]
Hi,
I'm trying to use `premake5` to generate the makefile on Linux but I encounter a problem.

When I run `premake5 gmake`, it generates the build configuration files in `../build`, this is working.
But when I go into the `build` folder and I run `make`, I get:

```
==== Building VulkanSample (debug_x64) ====
Creating Desktop_gmake2/x64/Debug
VulkanSample.cpp
g++: error: /MDd: Aucun fichier ou dossier de ce type
VulkanSample_gmake2.make:155 : la recette pour la cible « Desktop_gmake2/x64/Debug/VulkanSample.o » a échouée
```

(In french sorry).

I tried with `premake5 --os=linux gmake` or `premake5 --os=linux gmake2` and the problem persists.
`make` is trying to add the `/MDd` flag which is a Windows flag.
I am not familiar with premake so maybe you could find a way.

I have to use premake to compile because I am writing a script that automates the process and it must work on Windows and Linux.

Thanks,
Jean-Sébastien

**Comment by adam-sawicki-amd** [comment]
Building on Linux is working and being tested on Travis CI. The commands I use are, after installing Vulkan SDK:

```bash
cd premake
../premake5 gmake
cd ../build
make config=debug_linux-x64
cd ..
```

Crucial part is to use `debug_linux-x64` or `release_linux-x64` config - there is no Windows `/MDd` option there.

You can see build script here: [.travis.yml](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/.travis.yml).

**Comment by realitix** [comment]
Indeed, thanks
