### ISSUE TITLE
-Wunused-variable (clang)

### ISSUE THREAD

**Issue by jshofmann** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#101]
As of commit fbaccff808189d920f819e0113333ef48ce4043b using clang 7.0.1 I'm getting an "unused variable" warning at the -Wall -Wextra warning settings:

1>vk_mem_alloc.cpp
1>In file included from ..\..\..\src\lib\VulkanMemoryAllocator\vk_mem_alloc.cpp:9:
1>..\..\..\src\lib\VulkanMemoryAllocator/vk_mem_alloc.h(12103,16): warning : unused variable 'withinBudget' [-Wunused-variable]
1>    const bool withinBudget = (createInfo.flags & VMA_ALLOCATION_CREATE_WITHIN_BUDGET_BIT) != 0;
1>               ^
1>1 warning generated.

**Comment by adam-sawicki-a** [comment]
You are right, it was an unused variable. I removed it.
