### ISSUE TITLE
[Bug] Intel UHD Graphics 630 Physical Device Limits

### ISSUE THREAD

**Issue by cscott-glodon** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#102]
### Environment
Mac mini (2018)
3.2 GHz 6-Core Intel Core i7
16 GB 2667 MHz DDR4
Intel UHD Graphics 630 1536 MB

### Issue
Assertion failed: (vkMemReq.alignment % allocator->m_PhysicalDeviceProperties.limits.minUniformBufferOffsetAlignment == 0), function vmaCreateBuffer, file /Users/cscott-glodon/.conan/data/vma/2.3.0/glodon-usa+conan-glodon_usa/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/vma/src/vk_mem_alloc.h, line 18093.

### Question
Is this hardware limitation or avoidable? Am able to run application without using VMA.

**Comment by adam-sawicki-a** [comment]
This is a bug in the library. These asserts are incorrect and should not be there. I will remove them.
