### ISSUE TITLE
Accepting nullptr as parameter for vmaDestroyBuffer

### ISSUE THREAD

**Issue by IAmNotHanni** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#103]
I managed to create a bug by doing this:

`vmaDestroyBuffer(vma_allocator, uniform_buffers[i].buffer, nullptr);`

instead of:

`vmaDestroyBuffer(vma_allocator, uniform_buffers[i].buffer, uniform_buffers[i].allocation);`

I think there is not `assert` checking for this parameter.
Does it make sense to accept nullptr like this?
Are there use cases for that?

I am a huge fan of VulkanMemoryAllocator. Great work!

Sincere regards,
Johannes

**Comment by adam-sawicki-a** [comment]
Yes, the function deliberately accepts `VK_NULL_HANDLE` as buffer as well as allocation. It's a common pattern in many APIs to behave like this. You can also safely `free(NULL)` in C and `delete myNullPointer` in C++.
