### ISSUE TITLE
vmaCreateAccelerationStructure?

### ISSUE THREAD

**Issue by cheako** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#106]
Building on #104, a higher level abstraction for AS.

Thanks.

**Comment by adam-sawicki-a** [comment]
Yes, that's on my TODO list. I might do it pretty soon, subject to time constraints of my other projects.

**Comment by adam-sawicki-a** [comment]
Hey, I've coded first prototype support on a separate branch "VK_KHR_ray_tracing". Can you please take a look and see if it works for you? Any feedback is welcomed.

**Comment by cheako** [comment]
I think if you put  #106 in the commit msg it will link the commit here.

**Comment by cheako** [comment]
I think there are two buffers for some or every AS?  I'm sorry I don't know anything about this, just what I'm looking at in the code here.  Both of the AS defined in this example had both memory allocations.
https://github.com/maierfelix/VK_KHR_ray_tracing/blob/master/VK_KHR_ray_tracing/VK_KHR_ray_tracing.cpp#L620-626

OBJECT/bound to AS
https://github.com/maierfelix/VK_KHR_ray_tracing/blob/master/VK_KHR_ray_tracing/VK_KHR_ray_tracing.cpp#L235

BUILD_SCRATCH/bound to VkBuffer
https://github.com/maierfelix/VK_KHR_ray_tracing/blob/master/VK_KHR_ray_tracing/VK_KHR_ray_tracing.cpp#L293

**Comment by cheako** [comment]
I figured it out, I guess.  What's missing is just vma_create_acceleration_structure_buffer()/destroy() calls that are a blend of vma_create_buffer() and vma_create_image() using vkGetAccelerationStructureMemoryRequirementsKHR/VkAccelerationStructureMemoryRequirementsInfoKHR where type is either BUILD_SCRATCH or UPDATE_SCRATCH, instead of OBJECT.

**Comment by cheako** [comment]
Should probably document that calling vkGetAccelerationStructureDeviceAddressKHR() is up to the client as it feels like something that should be available in an info struct.

**Comment by adam-sawicki-a** [comment]
I've added function `vmaCreateAccelerationStructureScratchBuffer`. Please check if it looks useful to you.

(And I forgot to refer to this ticket in my commit message again 😊)

**Comment by cheako** [comment]
There was a type mismatch.

**Comment by cheako** [comment]
There are some other bugs here, but I think I can fix them.

**Comment by adam-sawicki-a** [comment]
Any help in getting this working is very welcomed.

**Comment by adam-sawicki-a** [comment]
Implementation of support for VK_KHR_ray_tracing extension in VMA is on the TODO list but is now on hold, planned for the future.

**Comment by cheako** [comment]
94f00da Is good, but it's difficult to merge into master ATM.

**Comment by cheako** [comment]
Example: https://gitlab.com/cheako/ash-rt/-/tree/762868856fa6d50b8545b255dc0c46f59b776545
It builds, but I don't have the hardware to run it.

**Comment by tomilov** [comment]
Why do we need `vmaCreateAccelerationStructureScratchBuffer`? Can't we do with simple `vmaCreateBuffer`?

**Comment by cheako** [comment]
@tomilov It's an uninteresting distinction, one calls vkGetAccelerationStructureMemoryRequirementsKHR() and the other calls vkGetBufferMemoryRequirements().

**Comment by cheako** [comment]
I'm not creating a PR, because on hold.

**Comment by helixd-2k18** [comment]
Specification finalized under `VK_KHR_acceleration_structure`.

**Comment by adam-sawicki-a** [comment]
I confirm the support is planned and under development.

**Comment by adam-sawicki-a** [comment]
I can see that in the final version of `VK_KHR_acceleration_structure` extension, `VkAccelerationStructureKHR` object is created on top of a `VkBuffer`, so I think no support is needed in VMA.

The only addition I could think of is a convenience function to query for size, create a buffer, and create an acceleration structure with one call. But I think is is a bad idea too because:

- `vkGetAccelerationStructureBuildSizesKHR` returns sizes of 3 buffers with one call (`accelerationStructureSize`, `updateScratchSize`, `buildScratchSize`), so it shouldn't be hidden in creation of one buffer.
- I don't think the library should provide creation of `VkAccelerationStructureKHR` on top of a `VkBuffer`, just like it doesn't provide the creation of `VkImageView` on top of a `VkImage`. VMA is just about creating objects that go directly into `VkDeviceMemory`.

I'm looking forward to read your feedback.

**Comment by adam-sawicki-a** [comment]
Please note that buffer sub-allocation, which is useful also for acceleration structures, is on the TODO list as #88. Any feedback is welcomed in that ticket about how the API of this feature should look like.

**Comment by adam-sawicki-a** [comment]
I'm closing this ticket due to inactivity. Please let me know if you have additional questions.
