### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by WinteryFox** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#107]
Hi everyone,

After updating to the latest commit ( 4405c51 ) I am getting an assertion failed. I am running the beta NVIDIA drivers (422.77) which support Vulkan 1.2.133. Everything was working fine until I updated VMA, is this a bug or am I doing something wrong?

```
Assertion failed!

Program: Foo.exe
File: vk_mem_alloc.h, Line 15394

Expression: m_VulkanFunctions.vkGetPhysicalDeviceProperties != nullptr
```

**Comment by adam-sawicki-a** [comment]
I checked on my NVIDIA card, driver 445.75, Vulkan SDK 1.2.131.2 and it works correctly. I also double-checked the code that fetches function pointers and it looks good to me.

Please check any other Vulkan program like command-line "vulkaninfo" if it works for you.

**Comment by WinteryFox** [comment]
vulkaninfo seems to work (https://hasteb.in/xezepuqi.yaml). I tried 445.75 too and it spits out the same error.

**Comment by adam-sawicki-a** [comment]
Possibly you didn't set `VmaAllocatorCreateInfo::instance` member when creating the allocator. Please try setting it and see if it helps. Documentation telling that it's optional is not correct - it's my fault, it's required now.

**Comment by WinteryFox** [comment]
Ahh yes, that fixed it! Thank you very much.

**Comment by adam-sawicki-a** [comment]
I clarified the documentation. Thank you for helping me to find this issue.
