### ISSUE TITLE
[Improvement] Allow several ways to retrieve Vulkan functions

### ISSUE THREAD

**Issue by realitix** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#11]
Hi @adam-sawicki-amd,

As a result of our email conversation, I open this issue to keep track of the changes and to talk about the best way to do it.

## Context

In the LunarG [documentation](https://vulkan.lunarg.com/doc/sdk/1.0.61.1/linux/LoaderAndLayerInterface.html), it's explicitly written that in order to maximize performance, Vulkan functions should be retrieved from `vkGetDeviceProcAddr`.

So there are 4 ways to retrieve Vulkan functions:

1 - statically linked with the SDK
2 - dynamically linked during linktime with the SDK
3 - dynamically linked during runtime with the SDK
4 - retrieved from vkGetDeviceProcAddr

## Current state

Currently, with your library, the 2 last options are unavailable.
Theses 2 last options are the most common ways to use Vulkan SDK because (3) allows to gracefully exit if SDK is unavailable and (4) allows for the best performance.

## Improvement

Add in `VmaAllocatorCreateInfo` an optional field for each Vulkan function used in the library.
These fields have to be optional for people who wants to link during linktime.
This change would allow to use your library in the 4 modes listed above.

Let's do it !

**Comment by adam-sawicki-amd** [comment]
I committed proposed solution on separate branch for now;

https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/tree/Pointers_to_Vulkan_functions

Does it solve the problem?

**Comment by realitix** [comment]
Sorry for the closing (by mistake). I didn't have time yet to review.

I let you know on monday.

**Comment by realitix** [comment]
Hello @adam-sawicki-amd, I added note directly in the code.
It' very good but just a small improvement, we should be able to override the constant without modifying the source file.
Here my 3 comments:

[1](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/commit/ab0b39a783042d66d56d8ea5c9dc4a21bdde212b#diff-44540aefde48c442bbf9b6a5c0fc3fdeR389)

[2](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/commit/ab0b39a783042d66d56d8ea5c9dc4a21bdde212b#diff-44540aefde48c442bbf9b6a5c0fc3fdeR1276)

[3](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/commit/ab0b39a783042d66d56d8ea5c9dc4a21bdde212b#diff-44540aefde48c442bbf9b6a5c0fc3fdeR6166)

**Comment by adam-sawicki-amd** [comment]
Thank you for the comments. I applied them all, committed this change and merged to master branch.

**Comment by realitix** [comment]
Thanks a lot @adam-sawicki-amd, very good work (and fast)!
