### ISSUE TITLE
Removal of VMA_STATIC_VULKAN_FUNCTIONS.

### ISSUE THREAD

**Issue by cheako** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#111]
954631a

This was useful for libraries that depended on other libraries linking with Vulkan.  With VMA_STATIC_VULKAN_FUNCTIONS set to 0 it was possible to call passthrough functions to Vulkan, but not link to Vulkan directly.

**Comment by adam-sawicki-a** [comment]
If you find this useful then OK, I restored `VMA_STATIC_VULKAN_FUNCTIONS` macro and also added new `VMA_DYNAMIC_VULKAN_FUNCTIONS`, all implemented in a new way. Please let me know if it works for you.
