### ISSUE TITLE
vmaFlushMappedAllocation[s]

### ISSUE THREAD

**Issue by Cscotttaakan** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#119]
vmaFlushMappedAllocation calls `vkFlushMappedMemoryRanges`. Why does it not allow you to pass a pointer to flush multiple allocations in a single call? Wouldn't it be more compact and would utilize `vkFlushMappedMemoryRanges` properly?

**Comment by adam-sawicki-a** [comment]
Thanks for the suggestion. I think it's a good idea. I will implement it when I find some time.
