### ISSUE TITLE
External Memory Support

### ISSUE THREAD

**Issue by fhoenig** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#123]
Would it be possible to add this?

Is there a way to pass the struct into pNext without modifying the library?

See here: https://github.com/NVIDIA/cuda-samples/blob/6be514679b201c8a0f0cda050bc7c01c8cda32ec/Samples/simpleVulkan/vulkanCUDASinewave.cu#L1206

**Comment by adam-sawicki-a** [comment]
Support for imported/exported external memory has been explicitly left out of scope of this library. See documentation:

https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/general_considerations.html#general_considerations_features_not_supported
