### ISSUE TITLE
vmaCreateAllocator memory read fail

### ISSUE THREAD

**Issue by anitaschaefer** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#127]
I included VMA in my project and when creating an allocator, it aborts the program. Using the debugger I saw that my allocator has the following "value": `read memory from 0xcccccccccccccccc failed (0 of 1 bytes read)` 

I include `vk_mem_alloc.h` in my application's header file and use the macro `#define VMA_IMPLEMENTATION` in the applications .cpp file. 

The allocator is created after the instance, physical device and logical device in the following way: 
`VmaAllocatorCreateInfo allocatorInfo = {};
    allocatorInfo.physicalDevice = m_physicalDevice;
    allocatorInfo.device = m_device;

    if(vmaCreateAllocator(&allocatorInfo, &m_allocator) != VK_SUCCESS) {
        throw std::runtime_error("Failed to create allocator. ");
    }`

What could be the source of this error?

**Comment by adam-sawicki-a** [comment]
Depending on your compiler, e.g. if you use Visual Studio and the project is in Debug configuration, value 0xCCCCCCCC indicates uninitialized variable on a stack. Please enter the function using the debugger and see whether it succeeds or not, and why `m_allocator` is not assigned. Also make sure that `VMA_ASSERT` is defined as not empty, so internal errors are reported.

**Comment by adam-sawicki-a** [comment]
I'm closing this ticket due to inactivity for a long time. Please let me know if you have additional questions.
