### ISSUE TITLE
Can VMA list up all unfreed resources automatically ?

### ISSUE THREAD

**Issue by IAmNotHanni** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#130]
Hello,

if we call `vmaDestroyAllocator` before all resources are freed, we get this error message:

> 2020-05-08 13:39:17.585787 Assertion failed: m_pMetadata->IsEmpty() && "Some allocations were not freed before destruction of this memory block!", file vk_mem_alloc.h, line 11669
debug  4380  3452 [vulkan-renderer] Destroying depth stencil image view. 

If VMA recording is enabled, we can see a detailed list of memory allocations and deallocations:

```
3452,10.469,0,vmaCreateImage,0,1,130,800,800,1,1,1,4,0,96,0,0,32,1,0,0,0,0000000000000000,00000000107E48E8,MSAA target depth image.
3452,10.470,0,vmaCreateImage,0,1,130,800,800,1,1,1,1,0,33,0,0,32,5,0,0,0,0000000000000000,00000000107E45D0,Depth stencil image.
// some other allocations/frees here are not listed..
3452,13.820,0,vmaDestroyBuffer,00000000107E4930
3452,13.821,0,vmaDestroyAllocator
```

I was wondering: Do I have to sort out which create call has a corresponding free call manually? Can't VMA recording somehow sort out the ones which have been freed so it can tell us which ones are still unfreed ? This would be very useful since we could use the internal naming of memory allocations to see which resources is not freed correctly.

I know that introducing this feature would eventually have a runtime cost. What are your opinions on this?

If this feature is not available and you agree that this would be useful, I might implement it and create a pull request if I can find the time.

Sincerely yours,
Johannes

**Comment by adam-sawicki-a** [comment]
Thank you for this suggestion. I think it's a good idea. The list of unfreed allocations and their names is already easily available at the moment the assert is fired.

Question is: How to report the list? There is a macro `VMA_DEBUG_LOG` used throughout the code and defined as empty by default. Maybe using it would be enough?

**Comment by IAmNotHanni** [comment]
I think it would be good to have all unfreed resources in the vma-replay CSV file.

**Comment by adam-sawicki-a** [comment]
What do you mean by having them in the vma-replay CSV file? That file with input to the VmaReplay tool contains commands for allocation and free. If you mean VmaReplay would detect unfreed resources, would it then write another CSV file with their list? Or do you mean something else?

**Comment by IAmNotHanni** [comment]
I was misunderstanding the use of vma-replay CSV files: I just used them as a log of function calls.
Ah I see `VMA_DEBUG_LOG` prints the list to the console. I will be using this.

**Comment by medranSolus** [comment]
Hi! Since VmaReplay has been recently removed, now if you define `VMA_DEBUG_LOG` you'll get list of unfreed allocations with all possible details. Hope that will help you!

*Marek Machliński, Developer Technology Engineer Intern, AMD*

**Comment by adam-sawicki-a** [comment]
@expipiplus1 It seems we cannot use `VMA_NULLABLE` / `VMA_NOT_NULL` annotations for the new `VmaVirtualAllocation` as it is defined using `VK_DEFINE_NON_DISPATCHABLE_HANDLE` which on some platforms is an integer not a pointer. If this is a problem please discuss with @IAmNotHanni as we are coding the library in C++ for 64-bit Windows so we have no development environment to test either Android or Haskell.
