### ISSUE TITLE
Alignment restriction

### ISSUE THREAD

**Issue by martty** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#131]
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/src/vk_mem_alloc.h#L16274 restricts alignment to power-of-two.

Could you elaborate why the alignment is restricted here?

**Comment by adam-sawicki-a** [comment]
It is common in various memory management APIs to require memory alignment to be a power of two. That's what Vulkan does:
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap11.html#VkMemoryRequirements
> The implementation guarantees certain properties about the memory requirements returned by vkGetBufferMemoryRequirements2, vkGetImageMemoryRequirements2, vkGetBufferMemoryRequirements and vkGetImageMemoryRequirements:

> The alignment member is a power of two.

That's what other APIs do as well, e.g.:
https://docs.microsoft.com/pl-pl/cpp/c-runtime-library/reference/aligned-malloc?view=vs-2019
> The alignment value, which must be an integer power of 2.

Let me know if you meet a Vulkan implementation that doesn't comply with that and returns alignment that is not power of two.

**Comment by martty** [comment]
Thank you for your reply. This is indeed true for memory requirements of Vulkan objects. I am using VMA to suballocate VkBuffers in this case, and a non-POT alignment would be useful for me (for batching scenarios). After a quick test, it doesn't seem like VMA is taking advantage of the alignment being POT and is correctly aligning my allocations to eg. 12.

**Comment by adam-sawicki-a** [comment]
You are right that the general allocation algorithm will probably work with non-POT alignment, but "buddy" algorithm will not because it all relies on nodes being aligned to POT:
https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/custom_memory_pools.html#buddy_algorithm

What's your use case? How do you take advantage of using non-POT alignment in VMA? I would like to understand this.

**Comment by martty** [comment]
I have one big VkBuffer which I suballocate vertex data from, as described in #88. Let's say I have one attribute, positions (vec3, 12 bytes). I can draw 2 models without binding vertex buffers if the models share a vertex buffer (provided by the suballocation) and if the byte offset of the two data ranges is divisible by the stride of the attribute binding (alignment). This second requirement is because you can provide vertexOffset to vkCmddrawIndexed(), which essentially provides a vertexOffset * strideof(attribute) offset into the bound vertexbuffers.

**Comment by adam-sawicki-a** [comment]
I understand, thanks for the explanation.

I have a plan to expose pure allocation algorithms in VMA without real memory allocation, so they could be used in cases like yours, e.g. to sub-allocate parts of a GPU buffer, or CPU memory, or whatever. If you have any suggestions for how the API of this new feature could look like, please feel free to elaborate, preferably in #88.

Meanwhile, going back to this ticket... If your buffer contains vertices of the same format, and the sub-allocation is "virtualized" anyway, how about you allocate using VMA with a granularity of vertices not buffers, treating entire vertex as size=1 and multiply the offsets and sizes by vertex stride only after the allocation, outside of VMA? Would that solve the problem?

**Comment by martty** [comment]
You are correct that using a single format per buffer would solve this. For now I am not sure how to proceed best, as I need to take extra steps for batching draws with multiple attributes in any case.

If this is a complex change, then please close the ticket, it just seemed like an easy thing to change and I was not aware of the buddy allocator requirement.

I'll try to give feedback on #88 after implementing this system to elaborate what I needed in the end.

**Comment by adam-sawicki-a** [comment]
Although technically simple, I don't want to enable non-POT alignment to avoid complicating the library. It would have to be defined as "accepted except when algorithm = buddy, then it's not". I'm sorry.

**Comment by martty** [comment]
No problem, thanks for your time!
