### ISSUE TITLE
Defining VMA_HEAVY_ASSERT does not compile

### ISSUE THREAD

**Issue by Selmar** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#132]
I'm defining as follows:
```C
#define VMA_HEAVY_ASSERT(expr) assert(expr)
#include <vk_mem_alloc.h>
```
This check in `vmaBeginDefragmentationPass` does not compile:
```C
VMA_HEAVY_ASSERT(VmaValidatePointerArray(pInfo->moveCount, pInfo->pMoves));
```
> vk_mem_alloc.h(4602,1): error C2678: binary '==': no operator found which takes a left-hand operand of type 'const T' (or there is no acceptable conversion)

**Comment by adam-sawicki-a** [comment]
You are right. This assert was invalid and outdated, as `pInfo->pMoves` is not a pointer array. I removed it. Thanks for spotting this.

**Comment by Selmar** [comment]
You're welcome, thanks for fixing!
