### ISSUE TITLE
ImportVulkanFunctions fails to load core 1.1 (non-KHR) functions in some cases, leading to nullptr access

### ISSUE THREAD

**Issue by null77** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#133]
In the code below VMA initializes a few 1.1 functions:

https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/src/vk_mem_alloc.h#L15763

You can see in the _Static version of this method it overloads the KHR versions with the core ones when available:

https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/src/vk_mem_alloc.h#L15724

The dynamic case also fails to load the core version because `m_UseKhrDedicatedAllocation` / `m_UseKhrBindMemory2` may be false:

https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/src/vk_mem_alloc.h#L15812

This leads to a crash in `ValidateVulkanFunctions` immediately.

Seems like a couple fixes are necessary to support the case where the extension is disabled and Vulkan 1.1 is enabled.

**Comment by adam-sawicki-a** [comment]
You are right, it was a bug. I pushed a fix. Please let me know if it works for you.

**Comment by null77** [comment]
The patch fixed the crash I was seeing, thanks!
