### ISSUE TITLE
new clang nullability-completeness build warns

### ISSUE THREAD

**Issue by jshofmann** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#135]
There are 783 new build warns all resulting from -Wnullability-completeness in VulkanMemoryAllocator commit f9921aefddee2437cc2e3303d3175bd8ef23e22c, clang 9.0.1 hosted by Visual Studio 2017. I've turned off that warning as a workaround. vk_mem_alloc.cpp is a file consisting of "#define VMA_IMPLEMENTATION #include "vk_mem_alloc.h" as recommended by https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/quick_start.html#quick_start_project_setup.

The attached vma-build-warns.txt file contains the build log as including it here would push this message body past github's 65536 character limit.

[vma-build-warns.txt](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/files/4748362/vma-build-warns.txt)

**Comment by adam-sawicki-a** [comment]
I'm sorry but I'm not going to add the nullability annotations to all internal functions of the library. Having them on the public interface adds enough obfuscation to the code.

As the documentation says in the "Features not supported" chapter, being free of any compiler warnings on any version of any compiler is out of scope of the library.
