### ISSUE TITLE
vk_mem_alloc.h, with MSVC (Visual Studio 2019) litters the file with strange, often tautological errors

### ISSUE THREAD

**Issue by Phildo** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#138]
Some examples of specific errors I'm getting are:

`argument of type "VmaDeviceMemoryBlock *" is incompatible with parameter of type "VmaDeviceMemoryBlock *"`

and

`a value of type "VmaSuballocationType" cannot be assigned to an entity of type "VmaSuballocationType"`

and

`declaration is incompatible with "void VmaBlockMetadata::PrintDetailedMap_Allocation(VmaJsonWriter &json, VkDeviceSize offset, VmaAllocation hAllocation) const"`

when the definition is

`void VmaBlockMetadata::PrintDetailedMap_Allocation(class VmaJsonWriter& json, VkDeviceSize offset, VmaAllocation hAllocation) const`

It fills the error window with over 100 errors. It compiles and runs seemingly fine, but it renders the error window useless.

**Comment by adam-sawicki-a** [comment]
I cannot reproduce the problem. I compiled the project in Visual Studio Professional 2019 Version 16.6.3. Both projects build and run in both "Debug" and "Release" configuration without any errors or warnings.

You can try these things:

- Regenerate project files by doing `premake5 vs2019` in "premake" subdirectory.
- Update your Visual Studio to the latest version using Visual Studio Installer.
- Retarget solution to the latest Windows SDK version.
- Make sure you have "x64" selected as project configuration not "Linux-x64".

**Comment by adam-sawicki-a** [comment]
I'm closing this bug due to inactivity for some time. Please let me know if you have additional questions.

**Comment by wooandrew** [comment]
Happens with Visual Studio (2019) CMake project config

**Comment by isbdnt** [comment]
> For future reference: these errors pop up when `VMA_IMPLEMENTATION` is defined _after_ `vk_mem_alloc.h` is included.
Can I include vk_mem_alloc.h in header file?

**Comment by wooandrew** [comment]
> 
> 
> > For future reference: these errors pop up when `VMA_IMPLEMENTATION` is defined _after_ `vk_mem_alloc.h` is included.
> > Can I include vk_mem_alloc.h in header file?
> > How could it be possible to define VMA_IMPLEMENTATION before vk_mem_alloc.h if you need vk_mem_alloc.h in header file?

VMA_IMPLEMENTATION is only supposed to be defined once, and it is recommended that you do it in a separate source file. 
In the source file that you define VMA_IMPLEMENTATION, make sure it is defined before including any headers:

example.h
```cpp
#include "vk_mem_alloc.h"
...
```
example.cpp
```cpp
#define VMA_IMPLEMENTATION
#include "example.h"
...
```

**Comment by isbdnt** [comment]
> > > For future reference: these errors pop up when `VMA_IMPLEMENTATION` is defined _after_ `vk_mem_alloc.h` is included.
> > > Can I include vk_mem_alloc.h in header file?
> > > How could it be possible to define VMA_IMPLEMENTATION before vk_mem_alloc.h if you need vk_mem_alloc.h in header file?
> 
> VMA_IMPLEMENTATION is only supposed to be defined once, and it is recommended that you do it in a separate source file.
> In the source file that you define VMA_IMPLEMENTATION, make sure it is defined before including any headers:
> 
> example.h
> 
> ```c++
> #include "vk_mem_alloc.h"
> ...
> ```
> 
> example.cpp
> 
> ```c++
> #define VMA_IMPLEMENTATION
> #include "example.h"
> ...
> ```

right, I did what u said, but still a lot of errors, and I found a wired solution, if I open an empty cpp file in tab, then compilation succeed

**Comment by wooandrew** [comment]
Try including the "example.h" file before all other headers (at least before any header that also requires vk_mem_alloc.h). Other than that piece of advice, I can't help you much. You'll have to fix it via trial and error.

**Comment by isbdnt** [comment]
MSVC still telling me this :(
use of undefined type 'VmaAllocation_T'

**Comment by KieranHsieh** [comment]
It look like this problem arises when including a mixture of "vk_mem_alloc.h" and the header file included with the single source file with #define VMA_IMPLEMENTATION such as:

example_allocator.h
```
#include "vk_mem_alloc.h"
```
example_allocator.cpp
```
#define VMA_IMPLEMENTATION
#include "example_allocator.h"
```
example.cpp
```
#include "example_allocator.h"
#include "vk_mem_alloc.h"
```
or
```
#include "vk_mem_alloc.h"
#include "example_allocator.h"
```

A work around to this issue is to replace all instances of #include "vk_mem_alloc.h" with #include "example_allocator.h"

Applying this fix to the above example looks like this:
```
#include "example_allocator.h"
#include "example_allocator.h"
```
