### ISSUE TITLE
Add functionality to resize allocations

### ISSUE THREAD

**Issue by ROTARTSI82** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#144]
It would be really nice if vma has something similar to c's `realloc`, so that people could easily grow buffers. 

Maybe it can increase the allocated area without copying data if there is free space after the allocation? If not it could just create a new allocation with the requested size, copy the data, and free the old one. 

I'm just learning vulkan and I'm not sure how to synchronize this, but it shouldn't be much worse than the defragmentation, right?

I'm not sure if this is within VMA's scope, but I'm going to post this anyways.

**Comment by krOoze** [comment]
Hi again, I believe this is dup of #86. But let's see if you get some more satisfying official rationale.

**Comment by adam-sawicki-a** [comment]
A feature to resize existing allocation in place when possible was in the library but it has been removed as not very useful. You would need to recreate your `VkBuffer` anyway, as Vulkan keeps track of buffer or texture size separate from the memory allocation size. Moving a buffer to a new place, like during defragmentation, requires some nontrivial logic from the user anyway, cannot be fully implemented inside VMA.

So in case you need a larger buffer, I recommend to just create a new one and remove the old one.
