### ISSUE TITLE
Allocation offsets and dynamic uniform buffers

### ISSUE THREAD

**Issue by sasmaster** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#149]
Hi. I am trying to integrate VMA. I have a renderer where there are 2 dynamic UBOs, 1 - for transforms. 2 - for materials.
I allocate both buffers using VMA.Same allocator is also used to preallocate a staging buffer.So I have 3 buffers in that allocator's
memory.After I finished the integrations I see a black screen.No validation layer errors or warnings.
What is not clear to me is if I have to use the offsets of each buffer when I  write descriptor sets of those buffers:

For example here is what I do for transform and material buffers:
```
                        VkDescriptorBufferInfo transformBufferInfo;
			transformBufferInfo.buffer = vulkanTransformUniformBuffer->buffer;
			transformBufferInfo.offset = offset;
			transformBufferInfo.range = VK_WHOLE_SIZE; 

			VulkanGetMemoryInfo(vulkanMaterialUniformBuffer, &size, &offset, &align);
			VkDescriptorBufferInfo materialBufferInfo;
			materialBufferInfo.buffer = vulkanMaterialUniformBuffer->buffer;
			materialBufferInfo.offset = offset;
			materialBufferInfo.range = VK_WHOLE_SIZE; 

```

Now I tried to set 'offset' to be the allocation::offset,but it didn't solve the problem. What am I missing here?

Thanks!

**Comment by adam-sawicki-a** [comment]
Hi, The offset to specify as `VkDescriptorBufferInfo::offset` refers to the beginning of your `VkBuffer`, not the whole memory block, so you shouldn't add `VmaAllocationInfo::offset` to it.

I don't know what else may be wrong in your code (there are numerous possible causes of having wrong results), but to eliminate the possibility of misusing offsets, you can try to allocate all your buffers with `VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT`. Then each buffer gets its own memory block and starts at offset 0. Please see if that helps.

**Comment by adam-sawicki-a** [comment]
I'm closing this ticket due to inactivity. Please let me know if you have additional questions.
