### ISSUE TITLE
Official C++ bindings support?

### ISSUE THREAD

**Issue by ghost** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#15]
I used C++ Vulkan bindings on our project. VulkanMemoryAllocator planned to support of official C++ bindings support? 
https://github.com/KhronosGroup/Vulkan-Hpp

**Comment by adam-sawicki-amd** [comment]
I currently have some higher-priority tasks to do in the project, but I may add C++ binding in the future, possibly when releasing version 2.0.0 final.

**Comment by adam-sawicki-amd** [comment]
It is now being developed on branch "cpp_binding". See also #43.

**Comment by adam-sawicki-amd** [comment]
I'm sorry to inform that it has been decided that C++ binding for VMA is not going to be officially supported as part of this repository. While having an object-oriented C++ wrapper over the library is a good idea, having it in same, extensive form as the official Vulkan C++ wrapper has too much maintenance cost, while the survey among developers indicated that majority of them prefer to use Vulkan C interface in their C++ code.

A C++ VMA wrapper is welcomed as external project and may be linked in README.md.

**Comment by adam-sawicki-amd** [comment]
C++ binding for this library has been created as external project:
https://github.com/malte-v/VulkanMemoryAllocator-Hpp

**Comment by MythreyaK** [comment]
Any plans to add an XML like in vulkan-hpp to ease generation of bindings?

**Comment by adam-sawicki-a** [comment]
I am sorry but just as the documentation says, VMA is a C++ library with C interface and any ports or bindings to additional languages are out of scope of this project. Maintaining such XML would require additional work every time the library is changed.

**Comment by MythreyaK** [comment]
Ah bummer, thanks for the info!
