### ISSUE TITLE
VMA_DEBUG_MARGIN icw allocAlignment binds wrong memory region?

### ISSUE THREAD

**Issue by MennoVink** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#152]
I'm having a weird issue on a AMD Radeon RX 5700 XT where 2D images end up being black.
I've reduced my example to only a single allocation using the vma. This first and only allocation ends up using an offset of 65536. This is caused by the VmaAlignUp call in CheckAllocation. Using 16 as VMA_DEBUG_MARGIN will cause the pOffset to have to be aligned up to this number.
If i then change the memoryOffset used in VmaDeviceMemoryBlock::BindImageMemory to 0 then the image contents show correctly. Using VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT or not using VMA_DEBUG_MARGIN also solve this issue.

This is what i'm doing to create the image:
```
	vk::ImageCreateInfo createInfo = VkImageFactory::BuildImageCreateInfo( imageFormat );
	VkImageCreateInfo vkCreateInfo = createInfo;

	VmaAllocationCreateInfo allocInfo = { 0 };
	allocInfo.usage = VMA_MEMORY_USAGE_GPU_ONLY;
	//allocInfo.flags = VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT;

	VkImage vkHandle = VK_NULL_HANDLE;
	VkResult result = vmaCreateImage( vkDevice.GetAllocator().GetHandle(), &vkCreateInfo, &allocInfo, &vkHandle, &pimpl->allocation, nullptr );
```

The create info is a 2d 255x255*rgba8unorm without any mips or array layers and using optimal tiling. I noticed that if i keep the image 160x160 or smaller it works as well (uses offset 4096), 161x161 and up doesn't work

This is my vma configuration:

```
#define VMA_VULKAN_VERSION 001000000
#define VMA_DEDICATED_ALLOCATION 1
#define VMA_BIND_MEMORY2 0
#define VMA_MEMORY_BUDGET 1
#define VMA_HEAVY_ASSERT(expr) MEVI_REQUIRE(expr)
#define VMA_RECORDING_ENABLED 0
#define VMA_USE_STL_CONTAINERS 1
#define VMA_DEFAULT_LARGE_HEAP_BLOCK_SIZE (128ull * 1024 * 1024)

#define VMA_MUTEX mevi::CriticalSection
#define VMA_RW_MUTEX mevi::ReadWriteCriticalSection

#if defined( MEVI_DEBUG )
#	define VMA_DEBUG_MARGIN 16
#	define VMA_DEBUG_DETECT_CORRUPTION 1
#	define VMA_DEBUG_INITIALIZE_ALLOCATIONS 1
#endif
```

Any ideas as to what may be going wrong?

**Comment by adam-sawicki-a** [comment]
First thing you can try is to disable VMA_DEBUG_MARGIN, but create some dummy image before the one you need and see if it works then. We need to check whether different offsets at which your image is placed cause the bug to appear or go away, regardless of VMA_DEBUG_MARGIN.

Please also make sure that you don't use VmaAllocationInfo::offset in all the placed where it's not needed, especially not apply it to pointer returned by vmaMapMemory.

Please also check if it helps to leave VMA_DEBUG_MARGIN but not set VMA_DEBUG_INITIALIZE_ALLOCATIONS.

**Comment by MennoVink** [comment]
Creating any dummy image before it instead of the debug margin also breaks the behaviour. It doesn't seem to matter if i create a small image where the actual image offset ends up being 64K or if i create a large dummy image pushing the actual image x alignments further.

I'm not using VmaAllocationInfo::offset anywhere at all, maybe that is the problem? The buffer to image copy (for transfers) targets the image through the subresourceRange, not it's memory. So does the image's view creation. I'm not sure where i would need to use the offset other than binding memory? (which is what i'm letting vma do for me)

Having VMA_DEBUG_MARGIN without the VMA_DEBUG_INITIALIZE_ALLOCATIONS define still shows the issue. Same if i keep the init_allocs enabled but disable just the detect_corruption or disable both the other VMA_DEBUG_ defines.

**Comment by adam-sawicki-a** [comment]
OK, thanks for this test. Then it seems that the bug occurs whenever the image is placed at some offset higher than 0.

If you suspect VMA binds wrong memory region, please enter the code with a debugger to see what offset is used for binding the image to the memory, although I think such error is unlikely.

Another thing you can try to do is manually allocate some memory with vkAllocateMemory, vkCreateImage etc. and bind your image at some non-zero offset to see if the bug still occurs. If yes, it will mean the bug is not related to VMA.

**Comment by MennoVink** [comment]
okay... so I updated manual allocation code to add an alignment worth of padding at the start and that also broke. I know of no other place where the used memory offset should go other than binding so i thought lets update the driver...
problem solved, thanks for thinking along 👍

**Comment by adam-sawicki-a** [comment]
You're welcome. I'm glad you found the solution.
