### ISSUE TITLE
Android Configuration

### ISSUE THREAD

**Issue by CogSimGuy** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#155]
Is there any example of how to configure for Android? Combination of DEFINEs? Cannot get gradle to build without 20+ errors based around undefined references/pointers to Vulkan calls...

**Comment by adam-sawicki-a** [comment]
There are some open source projects that use VMA and compile on Android, for example Google Filament: https://github.com/google/filament

I think this is the matter of the way you link your project with Vulkan API. Please experiment with macros VMA_STATIC_VULKAN_FUNCTIONS, VMA_DYNAMIC_VULKAN_FUNCTIONS.

**Comment by CogSimGuy** [comment]
Thanks, I'll look into this...
