### ISSUE TITLE
Occationally infinite repeat while defragment cpu memories.

### ISSUE THREAD

**Issue by jhbaek7** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#156]
Hi. 
I has tried to add defragment method on my rendering engine.
I'm using cpu visible memory defragment like described on documents.
While testing, I experienced infinite repeat in while loop of VmaDefragmentationAlgorithm_Fast::InsertSuballoc method.
I think the maybe break statement is needed in while loop to stop repeating when condition in if statement is false.
Or, Is there something I missing to use defragment correctly?

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this. The new defragmentation feature was an external contribution and as such is not considered finished and well tested. Finishing it is on the TODO list, but I can't promise it will happen any time soon.

**Comment by adam-sawicki-a** [comment]
With new commit [88510e9](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/commit/88510e9801cb686131b66f415cbf9409a0df7ad9) we switched to the new TLSF allocation algorithm, along with a completely new defragmentation algorithm and API, so the problem should not happen any more.
