### ISSUE TITLE
Oversubscription on RADV's Heap 0

### ISSUE THREAD

**Issue by chaoticbob** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#157]
Hi,

I'm running into a weird issue with VMA and RADV (default driver on Ubuntu 20.04) that I can't make sense of. I have an application that allocates 4 1920x1080 float16 images using GPU_ONLY. It seems that VMA is picking the heap 0 for this allocation and this results in a validation error:
```
vkAllocateMemory: attempting to allocate 16777224 bytes from heap 0,but size of that heap is only 16777216 bytes.
```

I can't say I understand RADV's rationale for 2 DEVICE_LOCAL heaps, but this is what it looks like on my system:
```
        memoryHeaps[0]:
                size   = 16777216 (0x01000000) (16.00 MiB)
                budget = 18446744073271062528 (0xffffffffe5dd3000) (16.00 EiB)
                usage  = 0 (0x00000000) (0.00 B)
                flags: count = 1
                        MEMORY_HEAP_DEVICE_LOCAL_BIT
        memoryHeaps[1]:
                size   = 8573157376 (0x1ff000000) (7.98 GiB)
                budget = 8117891072 (0x1e3dd3000) (7.56 GiB)
                usage  = 0 (0x00000000) (0.00 B)
                flags: count = 1
                        MEMORY_HEAP_DEVICE_LOCAL_BIT
        memoryHeaps[2]:
                size   = 8573157376 (0x1ff000000) (7.98 GiB)
                budget = 8500088832 (0x1faa51000) (7.92 GiB)
                usage  = 0 (0x00000000) (0.00 B)
                flags: count = 0
                        None
```

I'm not doing anything special with VMA just a straight forward call to vmaAllocateMemoryForImage after a call to vkCreateImage. 

Any idea why heap 0 is selected as opposed to heap 1?

Thanks!

**Comment by adam-sawicki-a** [comment]
Hi, I have no idea why this driver exposes such 16 MB memory heap at the beginning. The budget of 18446744073271062528 bytes inside of it is also nonsensical, which indicates this driver is totally broken. I think you should rather open a ticket for RADV project. VMA is developed mostly on and for Windows using proprietary GPU drivers where no such situation occurs.

However, VMA is prepared to handle such situations. If allocation size exceeds the size of a memory heap, some drivers still allow to make this allocation, while some others return `VK_ERROR_OUT_OF_DEVIVCE_MEMORY`. In the latter case, VMA will try next eligible memory type, which may end up in heap 1. So I expect everything will work correctly and the validation layer error can just be ignored.

You can also try to make your allocations with flag `VMA_ALLOCATION_CREATE_WITHIN_BUDGET_BIT`. It can be used even without enabling VK_EXT_memory_budget extension. Then VMA won't try to allocate more than is available in a memory heap and so it will try another heap right away, which can solve this issue.

Please let me know if that helps.

**Comment by chaoticbob** [comment]
Hi Adam,

Thanks for responding so quickly. I did as you suggested and filed an issue on Mesa's issue tracker for RADV: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3845

In the interim I will try your other suggestions and report back.

Thanks.

**Comment by chaoticbob** [comment]
Hi Adam,

Looks like this was an issue with RADV. There's a fix in already. I'll wait for it to show up in Ubuntu eventually. 

Thanks again.
