### ISSUE TITLE
Alignment for vmaMapMemory

### ISSUE THREAD

**Issue by MikhailGorobets** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#159]
Hi. In Vulkan specification the function vkMapMemory returns a pointer which must be aligned to at least VkPhysicalDeviceLimits::minMemoryMapAlignment.
Perhaps it should be worth simulating this behavior for vmaMapMemory?
![VulkanMemory](https://user-images.githubusercontent.com/25492259/102489184-f121f400-408e-11eb-8d8a-066a7f7ca4b2.png)

**Comment by adam-sawicki-a** [comment]
What do you mean by simulating it? `VkPhysicalDeviceLimits::minMemoryMapAlignment` specifies a restriction on alignment of the pointer returned by `vkMapMemory`, so it is really a restriction that a Vulkan implementation (graphics driver) must follow, not a developer using Vulkan. `vmaMapMemory` uses `vkMapMemory` under the hood, so it follows the restriction automatically. Am I right? Or do I misunderstand something here?

**Comment by adam-sawicki-a** [comment]
I'm closing this ticket due to inactivity. Please let me know if you have additional questions.

**Comment by MikhailGorobets** [comment]
Below is a pseudocode of the problem I had in mind. Of course, the problem can be solved on my part in several ways. But I think it would be better to add an additional alignment parameter on creation. Or use the default 64 byte alignment so that we can immediately save the result of AVX512 instructions

![Untitled](https://user-images.githubusercontent.com/25492259/106151678-6ad4f380-619e-11eb-9955-2413e997aa22.png)

**Comment by adam-sawicki-a** [comment]
OK I see, so you basically want to have all the allocations to use some specific minimum alignment, which may be above what Vulkan implementation requires? Please try to define your custom value of `VMA_DEBUG_ALIGNMENT` macro and see if it helps.

**Comment by adam-sawicki-a** [comment]
I'm closing this ticket due to inactivity. Please let me know if you have any further questions.
