### ISSUE TITLE
Support for VK_KHR_external_memory and VK_KHR_external_memory_win32 extensions

### ISSUE THREAD

**Issue by manaskulkarni786** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#16]
This will enable use of the allocated memory for sharing across apis / processes. Especially important for VR projects

**Comment by adam-sawicki-amd** [comment]
How would you like the support for these extensions to look like in the interface of this library? You can already add `VkExternalMemoryImageCreateInfoKHR` structure to the `pNext` chain of the
`VkImageCreateInfo` structure.

**Comment by manaskulkarni786** [comment]
So we don't have to add VkExportMemoryAllocateInfoKHR in the pNext of the VkMemoryAllocateInfo? I thought you have to specify both?

**Comment by adam-sawicki-amd** [comment]
You are right. I will add support for these extensions to my TODO list to implement it some time in the future.

**Comment by manaskulkarni786** [comment]
Great. Thanks

**Comment by adam-sawicki-amd** [comment]
I considered what structures could be passed in `pNext` chain of `VkMemoryAllocateInfo` regarding import/export:

```
VkExportMemoryAllocateInfoKHR
VkExportMemoryAllocateInfoNV
VkExportMemoryWin32HandleInfoKHR
VkExportMemoryWin32HandleInfoNV
VkImportMemoryWin32HandleInfoKHR
VkImportMemoryWin32HandleInfoNV
VkImportMemoryFdInfoKHR
VkImportMemoryHostPointerInfoEXT
```

And I concluded that there is no convenient way to pass all the required parameters to this library. Allocations for imported/exported external memory tend to require explicit memory type index and dedicated allocation anyway, so they don't interact with main features of this library.

So I don't want to implement any support for it. I believe that such special purpose allocations should be made manually, using `vkCreateBuffer` and `vkAllocateMemory`.
