### ISSUE TITLE
VK_EXT_memory_priority extension

### ISSUE THREAD

**Issue by FilippoLeon** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#160]
I'd like to use VMA with VK_EXT_memory_priority (I want to test how well it works). I saw @adam-sawicki-a 's link to:
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/tree/VK_EXT_memory_priority
(a long time ago in a tweet) but the branch is since then not reachable. Is there a way to access the code to test out the feature without messing with the internals of VmaAllocator myself?

**Comment by adam-sawicki-a** [comment]
Unfortunately, there is no way to use VK_EXT_memory_priority with VMA at the moment. It is on my TODO list. Any suggestions about how an API for this should look like are welcomed. Meanwhile, I'm afraid the only way to use it is to allocate memory blocks with a non-default priority using Vulkan functions directly or hack VMA source code.

**Comment by FilippoLeon** [comment]
Thanks. I will think it trough. I think a priority would make sense per-pool and in case of dedicated allocations. But I am not sure if it makes sense, since I'm not sure what implementations will do with it (if they choose to ignore or do something meaningful with it).

**Comment by adam-sawicki-a** [comment]
I agree it should work with dedicated allocations and pools. Should I then add `float priority` to `VmaAllocationCreateInfo` (working with dedicated only? forcing dedicated when non-zero?) an `VmaPoolCreateInfo`?

**Comment by FilippoLeon** [comment]
That would be ideal. I would say the VmaAllocationCreateInfo.priority is ignored when the memory is not dedicated (in this case only the default priority or the pool priority is used). Unless the allocation from a pool fails and falls back to dedicated, in which case it should still use the pool priority even if VmaAllocationCreateInfo.priority was set?

**Comment by adam-sawicki-a** [comment]
OK, this sounds good.

BTW, I also plan to enable a possibility to create dedicated allocations out of custom pools. This would interact with this feature nicely, allow to create a custom pool with a custom priority that all the allocations created from it would get automatically, dedicated or not.

**Comment by FilippoLeon** [comment]
> BTW, I also plan to enable a possibility to create dedicated allocations out of custom pools. This would interact with this feature nicely, allow to create a custom pool with a custom priority that all the allocations created from it would get automatically, dedicated or not.

Great! Do you think it is possible to reserve some memory for dedicated allocations this way (I imagine not, as I do not even know how to do it well directly without vma, but I would love this)? I currently can either reserve undedicated memory via a pool, or use dedicated memory but then you cannot reserve it.

PS: do you have some more information about the status of this extension by modern drivers (if they actually use it)?

**Comment by adam-sawicki-a** [comment]
If you mean dedicated allocation in a strict Vulkan way, you cannot reserve memory for it as you need to pass your image/buffer during allocation through `VkMemoryDedicatedAllocateInfo`.

Otherwise, you can reserve some memory for later use by creating a custom pool with non-zero `VmaPoolCreateInfo::blockSize` and `minBlockCount`.

If you want to have separate memory blocks reserved for individual images/buffers, you can ask one for its `vkGetImageMemoryRequirements`, allocate memory without a resource using `vmaAllocateMemory` (you can still use `VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT` to get a separate `VkDeviceMemory` block) and later bind using e.g. `vmaBindImageMemory`.

**Comment by adam-sawicki-a** [comment]
I pushed some implementation. Please let me know if it looks good to you.

**Comment by FilippoLeon** [comment]
That was quick. It seems to be working. Sadly there is no real way to test its effects.

**Comment by adam-sawicki-a** [comment]
Thank you for your feedback.

Yes, there is no a reliable way to make sure priorities are working. You can try to over-subscribe video memory and see if setting high priority to the blocks that contain key render targets helps the performance.
