### ISSUE TITLE
VK_ERROR_OUT_OF_POOL_MEMORY not a Vulkan 1.0 core feature

### ISSUE THREAD

**Issue by AshkanAliabadi** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#164]
Hi Adam,

The VK_ERROR_OUT_OF_POOL_MEMORY enum used in the now deprecated function VmaAllocator_T::ResizeAllocation is only promoted to core [starting from Vulkan 1.1](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkResult.html).  For that reason older versions of the Android NDK, such as NDK 19c ([download link](https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip)), which we need to support in PyTorch Mobile, do not have it defined, which in turn is posing a problem to our integration of VMA in PyTorch.  I could hack around it in PyTorch but seeing how this enum is used in [only one location](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/a420c3d752c4e2e40d4ed2c8ed3139c45c001acf/src/vk_mem_alloc.h#L16775), and that is a deprecated function, I was wondering if there is something we could do to remove it.  VK_ERROR_OUT_OF_POOL_MEMORY_KHR is defined to the same value as VK_ERROR_OUT_OF_POOL_MEMORY so switching the two can be one way of fixing this without breaking backward compatibility for your users.

I am eager to get this working soon so I can enable our Vulkan CI in https://github.com/pytorch/pytorch/pull/52781.  Let me know how you want to move forward.  I can submit a PR with a solution of your choosing if you don't have the bandwidth.

Thanks!

**Comment by AshkanAliabadi** [comment]
By the way, just realized we have the same situation with [VK_MEMORY_PROPERTY_PROTECTED_BIT](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkMemoryPropertyFlagBits.html) which is a 1.1 feature.  In case that helps, we have VMA_VULKAN_VERSION defined to 1000000.

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this bug. I removed function vmaResizeAllocation as it was deprecated and doing nothing anyway, while current code is developed towards version 3.0.0, so breaking backward compatibility is fine.

I also surrounded usage of VK_MEMORY_PROPERTY_PROTECTED_BIT with appropriate #if.

Please let me know if it fixes the problem for you.

**Comment by AshkanAliabadi** [comment]
Thanks Adam for your quick response and fix, you rock!  I'll try it out and keep you posted.
