### ISSUE TITLE
Seperate sub-directory for header

### ISSUE THREAD

**Issue by PixelyIon** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#165]
Hey there,
We import this repository as a submodule in our project, this allows us to trivially update it as required but we end up facing the issue of not being able to pick and place individual files/folders. An issue arises with using `src` as an include directory due to it being polluted with a lot of unrelated sample code. It would be appreciated if `vk_mem_alloc.h` could be moved out to its own directory, something like `include` would work wonderfully.

I will say, the project is fairly different in structure compared to a lot of libraries as samples/tests are generally under their own sub-directories rather than `src` which tends to generally be the source files for the compilation of the library itself. A library being header-only with a macro for definitions is quite non-conventional aside from when it's for declaring static storage, it might make more sense to explicitly have a source file and for the library to be structured like a conventional C++ library. It ends up removing a redundancy with needing to create a source file in a project for it and can be trivially accounted for with a build system.

I do understand if resolving this issue is non-trivial due to it being a potentially breaking change.

Thanks in advance,
Mark

**Comment by adam-sawicki-a** [comment]
Hey Mark,

Thank you for the suggestion. I agree putting the main library file vk_mem_alloc.h in a separate directory will be helpful. I will make this change.

When it comes to the design of the library being "STB-style" single header with private implementation extracted using macro `VMA_IMPLEMENTATION`, this approach has its pros and cons, but it was a design decision to do it this way established before the project even started.

**Comment by expipiplus1** [comment]
This link needs updating: https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/4a132e510ce4d46c3cd888a118a4d1c5abcb0609/README.md#L5

**Comment by expipiplus1** [comment]
And I suspect that the link to `vk_mem_alloc.h` in the doxyfile needs changing too

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this issue. I fixed README, Doxyfile, also moved Doxyfile to main directory.

**Comment by expipiplus1** [comment]
Thanks for the fix!
