### ISSUE TITLE
Add CMake support

### ISSUE THREAD

**Issue by IAmNotHanni** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#168]
Hello. Adding CMake would make it easier to work with VMA on Linux (and Windows in my opinion). Furthermore CMake could create project maps for VMA library, the sample application, VMA replay, and even the shaders. 

I am aware not everyone likes CMake, however I must point out that even [Microsoft's STL repository](https://github.com/microsoft/STL) switched from their own build system to CMake. (More information on that in the following talk: [C++20 STL Features: One Year of Development on GitHub - Stephan T. Lavavej - CppCon 2020](https://youtu.be/8kjRx8vo6y4?t=222))

If you don't mind I'm workint on a pull request for this. (I also will work on https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/130 soon).

**Comment by adam-sawicki-a** [comment]
I agree with you. Cmake is a standard these days. Switching from Premake to Cmake is on my TODO list for this project.

**Comment by IAmNotHanni** [comment]
Alright. I'm working on it :)

**Comment by IAmNotHanni** [comment]
I'm finished. Before I open he pull request: Should it be only one `CMakeLists.txt` or should it be split up into the subfolders?

**Comment by adam-sawicki-a** [comment]
Your contribution is welcome, please feel free to propose this pull request.
