### ISSUE TITLE
Port VulkanSample to Linux using glfw

### ISSUE THREAD

**Issue by IAmNotHanni** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#169]
I would like to port the sample application to Linux using [glfw](https://www.glfw.org/).
We have several options:

- Use glfw as foundation for Windows example as well to have one code base.
- Split the code up so we have a Windows example and a Linux example.
- Just put the Linux example into the same file.

**Comment by adam-sawicki-a** [comment]
I am sorry, but I cannot accept this contribution. Although the library itself is portable across many platforms, it is developed mostly on and for Windows PC, and so we are not able to support and maintain projects like the sample app or VmaReplay for other platforms. Support for other platforms is welcome as external projects / forks.
