### ISSUE TITLE
Port VmaReplay to Linux

### ISSUE THREAD

**Issue by IAmNotHanni** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#170]
On my TODO list.

**Comment by adam-sawicki-a** [comment]
I am sorry, but I cannot accept this contribution. Although the library itself is portable across many platforms, it is developed mostly on and for Windows PC, and so we are not able to support and maintain projects like the sample app or VmaReplay for other platforms. Support for other platforms is welcome as external projects / forks.
