### ISSUE TITLE
Link to Vulkan spec about VK_KHR_dedicated_allocation incorrect?

### ISSUE THREAD

**Issue by IAmNotHanni** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#174]
I checked all links in the code comments. Where is this link supposed to go?
[VK_KHR_dedicated_allocation in Vulkan specification](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap44.html#VK_KHR_dedicated_allocation)

Because `VK_KHR_dedicated_allocation` is not mentioned on that page.
Shouldn't it go to [this page](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_dedicated_allocation)?

**Comment by adam-sawicki-a** [comment]
Thank you for finding this issue. I don't like the big single-page documentation, I prefer the chunked one. I fixed the link.
