### ISSUE TITLE
vmaUnmap after vmaFlushAllocation causes something wrong

### ISSUE THREAD

**Issue by ShaoyuanLi** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#180]
So I am using multiple 1 quad vertex buffer and 2 uniform block buffer with vulkan memory allocator. I call vmaFlushAllocation so it is visible device side. The memory usage is VMA_MEMORY_USAGE_CPU_TO_GPU.
VkBuffer usage is VK_BUFFER_USAGE_VERTEX_BUFFER_BIT and VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT respectively.
```
vmaMapMemory(m_allocator, buf->allocation, &buf->addr));
char* addr = static_cast<char*>(buf->addr);
memcpy(addr + offset, data, size);
vmaFlushAllocation(m_allocator, buf->allocation, offset, size);
vmaUnmapMemory(m_allocator, buf->allocation);
buf->addr = nullptr;
```
I update two uniform block buffer in every frame by below codes and the first.size is 256 the second'size is 64 and the vertex buffer is not updated in every frame.

it is wrong and all draw-calls would draw nothing which seems like buffer is empty(00000000........). this problem only occurs in Android(In My Xiaomi-6) and it is right effect in Windows.

I try to use RenderDoc and RenderDoc could capture VkAPI commands but **PipelineState Viewer and Texture Viewer in RenderDoc display right effect.**

If I choose one of three methods: 
1. change usage to CPU_ONLY
2. change flags to VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT
3. unmapMemory until destroy buffer instead of unmap in every update

this problem would disappear. 
Is it a driver bug? or, Is there something I missing to use VMA correctly?

**Comment by adam-sawicki-a** [comment]
First of all, please make sure not to use allocation's offset when accessing pointer to mapped data or doing `vmaFlushAllocation`. Both the returned pointer and the flush command refer to the beginning of your allocation already, not the entire `VkDeviceMemory` block. This is a mistake that users often make.

You can also try to reorder your calls, call `vmaFlushAllocation` after `vmaUnmapMemory`.

Also make sure your synchronization (like barriers) is right. Enable validation layer and check errors and warnings. Introduce extra synchronization (barriers or even `vkQueueWaitIdle`) and see if the bug goes away.

**Comment by ShaoyuanLi** [comment]
> First of all, please make sure not to use allocation's offset when accessing pointer to mapped data or doing `vmaFlushAllocation`. Both the returned pointer and the flush command refer to the beginning of your allocation already, not the entire `VkDeviceMemory` block. This is a mistake that users often make.
> 
> You can also try to reorder your calls, call `vmaFlushAllocation` after `vmaUnmapMemory`.
> 
> Also make sure your synchronization (like barriers) is right. Enable validation layer and check errors and warnings. Introduce extra synchronization (barriers or even `vkQueueWaitIdle`) and see if the bug goes away.

If I use offset with vmaFlushAllocation just like
```
vmaCreateBuffer(m_allocator,...) // with size 256
...
vmaMapMemory(m_allocator, buf->allocation, &buf->addr);
memcpy(buf->addr + offset, data, size); // offset + size < 256
vmaFlushAllocation(m_allocator, buf->allocation, offset, size);
```
Is it legal？Or I must flush all allocation `vmaFlushAllocation(m_allocator, buf->allocation, 0, offset + size)?

**Comment by ShaoyuanLi** [comment]
Thanks! 
I found the problem - I use a internal multi-loop buffer for multi-thread usage and could not consider memory usage alignment.
