### ISSUE TITLE
Allocation failures on macOS.

### ISSUE THREAD

**Issue by HindrikStegenga** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#184]
For my renderer I wanted to use vma to deal with my allocations. However, it seems that this is broken on macOS.
I am on big sur running under xcode 12.5. Many of my allocations fail with "CPU memory allocation failed.", and reverting the change from: https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/pull/137, specifically going back to the old alignment behaviour which is used on older macOS version, resolves the allocation failures.

**Comment by adam-sawicki-a** [comment]
The library is developed mostly on- and for Windows PC. Unfortunately I don't have a development environment for MacOS. Any suggestions about how to fix this problem are welcome.

**Comment by adam-sawicki-a** [comment]
OK, I merged that pull request. Thank you.

**Comment by null77** [comment]
@nico fyi, your changes were reverted in master earlier this year. I'm trying to update the integration we use and noticed this. Any ideas on what could be happening?

**Comment by null77** [comment]
@phuang fyi
