### ISSUE TITLE
TLSF allocation algorithm

### ISSUE THREAD

**Issue by plasmacel** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#189]
It would be great to apply the state of the art TLSF (Two-Level Segregated Fit) allocation algorithm in a custom VMA pool using a `VMA_POOL_CREATE_TLSF_ALGORITHM_BIT` flag, as presented in

> M. Masmano, I. Ripoll, A. Crespo and J. Real, "TLSF: a new dynamic memory allocator for real-time systems," Proceedings. 16th Euromicro Conference on Real-Time Systems, 2004. ECRTS 2004., 2004, pp. 79-88, doi: 10.1109/EMRTS.2004.1311009.

Compared to the buddy scheme, it provides much better fragmentation characteristics and low overhead per allocation.

**Comment by devshgraphicsprogramming** [comment]
got a public link to the paper?

**Comment by plasmacel** [comment]
Sure. http://www.gii.upv.es/tlsf/files/ecrts04_tlsf.pdf

**Comment by devshgraphicsprogramming** [comment]
unfortunately the license makes the two repositories you've linked incompatible for use in VMA (or my own project)

**Comment by plasmacel** [comment]
The first repo is BSD-licensed, which is permissive, but as I know one of its previous version was placed in the public domain by the author. You can see a fork of that version here: https://github.com/samplecount/tlsf. If I have enough time and patience I will read the paper and rework the public domain version myself and will share that.

**Comment by adam-sawicki-a** [comment]
Thank you for this suggestion. I will evaluate this algorithm and try to implement it when I find enough time for such research. If it is better than the one used currently, I can even make it the default.

**Comment by medranSolus** [comment]
Hi and thank you for the suggestion! The feature you requested is now up and running, so I encourage you to try it out and possibly give me some feedback if you have any suggestion about how it performs.
Currently TLSF algorithm is available in custom pools via **VMA_POOL_CREATE_TLSF_ALGORITHM_BIT** and in **VmaVirtualBlock** via **VMA_VIRTUAL_BLOCK_CREATE_TLSF_ALGORITHM_BIT** creation flags.

*Marek Machliński, Developer Technology Engineer Intern, AMD*
