### ISSUE TITLE
Please update "Memory Mapping" section of documentation please

### ISSUE THREAD

**Issue by c0nd3v** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#20]
In the "Memory Mapping" section of the documentation it says:

`TODO update this...`

For a newcomer to this library this is intimidating because I'm not sure if the documentation is correct.

Thank you.

**Comment by adam-sawicki-amd** [comment]
Thanks for pointing to this issue. I've updated this documentation chapter. Commit a3e019d4766725814b3a4585092e6ff1a1f36cb9.
