### ISSUE TITLE
VMA uses the extension version vkGetBufferMemoryRequirements2KHR of core function vkGetBufferMemoryRequirements2

### ISSUE THREAD

**Issue by plasmacel** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#203]
To determine whether the allocation should be dedicated, VMA checks for the presence of Vulkan API version 1.1, then uses `vkGetBufferMemoryRequirements2KHR` function from extension `VK_KHR_get_memory_requirements2` inside `VmaAllocator_T::GetBufferMemoryRequirements`:

    if (m_UseKhrDedicatedAllocation || m_VulkanApiVersion >= VK_MAKE_VERSION(1, 1, 0))
    {
        ...
        (*m_VulkanFunctions.vkGetBufferMemoryRequirements2KHR)(m_hDevice, &memReqInfo, &memReq2);
        ...
    }

However `VK_KHR_get_memory_requirements2` is promoted into the Vulkan 1.1 core.

If the version is less than 1.1, expecting an enabled `VK_KHR_get_memory_requirements2` could be a solution, but if the Vulkan version is 1.1 or above, then expecting the user to enable an extension which is already promoted into the core is not a good idea. Still, currently it must be done, otherwise the extension function `vkGetBufferMemoryRequirements2KHR` is not loaded, but only `vkGetBufferMemoryRequirements2`, which results in a segmentation violation and crash inside VMA's `VmaAllocator_T::GetBufferMemoryRequirements` function.

**Comment by plasmacel** [comment]
It can happen when you provide Vulkan functions via `VmaVulkanFunctions`.

**Comment by adam-sawicki-a** [comment]
I've pushed a new change that documents some members of `VmaVulkanFunctions`, clarifying which functions to fetch. What do you think about it?

**Comment by adam-sawicki-a** [comment]
I'm closing this ticket due to inactivity. Please let me know if you meet any further problems with this.

**Comment by kweezo** [comment]
I am experiencing the same issue, in `VmaAllocatorCreateInfo` I am not adding any flags and not enabling the dedicated allocations extensions. I made sure I specified `VK_API_VERSION_1_3`in instance creation and allocator creation however VMA still seemingly wants to call vkGetBufferMemoryRequirements2KHR as evident by the GDB trace.

```0x0000000000000000 in ?? ()
(gdb) up
#1  0x00007ffff71312b9 in VmaAllocator_T::GetBufferMemoryRequirements (this=0x523000011900, hBuffer=0xcb3ee80000000007, memReq=..., requiresDedicatedAllocation=@0x7fffbb609120: false, 
    prefersDedicatedAllocation=@0x7fffbb609130: false) at /usr/include/VulkanMemoryAllocator/vk_mem_alloc.h:13561
13561           (*m_VulkanFunctions.vkGetBufferMemoryRequirements2KHR)(m_hDevice, &memReqInfo, &memReq2);
(gdb) ```

**Comment by adam-sawicki-a** [comment]
When you use Vulkan version 1.1 or higher, function `vkGetBufferMemoryRequirements2` should be available and VMA tries to use it. The function pointer is called `m_VulkanFunctions.vkGetBufferMemoryRequirements2KHR` but it should really point to the function `vkGetBufferMemoryRequirements2` despite its name. Please make sure it does by using any of the methods for importing Vulkan functions described in the documentation:
https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/quick_start.html#quick_start_project_setup

**Comment by dirkz** [comment]
I'm using a self-built vulkan 1.4.304 on windows and I'm running into this issue as well, regardless if I chose the static or dynamic way of binding. I'm setting VMA (3.2.0) to use vulkan 1.2. Yes, I can probably work around that by enabling the extension, or being explicit about the function pointer to be used, or maybe even patching VMA as a last resort. But is relying on [vkGetBufferMemoryRequirements2KHR](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/v3.2.0/include/vk_mem_alloc.h#L13388C38-L13388C71) really the way to do this? Honest question, I don't know what the spec says, and it looks like it works for you without problems. I'm probably still overlooking something in my setup code.

E.g. doing it dynamically:

[Vulkan SDK Build](https://github.com/dirkz/vulkan-sdk-builder)
[VMA Inclusion](https://github.com/dirkz/vulkan-hpp-tutorial/blob/vma_dynamic/source/Vma.h)
[VMA Implementation](https://github.com/dirkz/vulkan-hpp-tutorial/blob/vma_dynamic/source/Vma.cpp)
[VMA Creation](https://github.com/dirkz/vulkan-hpp-tutorial/blob/vma_dynamic/source/HelloTriangleApplication.cpp#L167)

**Comment by mdrost** [comment]
Do you by any chance use AMD graphics card? I just encountered the same issue on AMD Radeon RX 7900 XTX, and have done some debugging and turns out that `vkGetBufferMemoryRequirements2` is probably simply missing in AMD drivers. `vkGetDeviceProcAddr` returns `NULL` for that function.

**Comment by mdrost** [comment]
I found the problem (in my case):
When creating Vulkan instance as `VkApplicationInfo::apiVersion` I passed `VK_API_VERSION_1_0` which I copied from Vulkan Tutorial :)

**Comment by GrinlexGH** [comment]
In fact, this is a complete non-compliance with the Vulkan specification:

Table 2. vkGetDeviceProcAddr behavior
| device | pName | return value |
|--------|-------|--------------|
| NULL | *<sup>1</sup> | undefined |
| invalid device | *<sup>1</sup> | undefined |
| device | NULL | undefined |
| device | requested core version<sup>2</sup> device-level dispatchable command<sup>3</sup> | fp<sup>4</sup> |
| device | enabled extension device-level dispatchable command<sup>3</sup> | fp<sup>4</sup> |
| any other case, not covered above | | NULL |

If the extension is not enabled, `vkGetDeviceProcAddr` **must** return `NULL`.

Try to update or reinstall driver and dont forget to restart the system, as in this case it is its fault

**Either this is due to the fact that you are using `vkGetInstanceProcAddr` to get a function from the device extension, which happens when you use `VULKAN_HPP_DEFAULT_DISPATCHER.init(instanceHandle)` also without calling `VULKAN_HPP_DEFAULT_DISPATCHER.init(deviceHandle)`. (btw vma-hpp have two overloads for `vma::functionsFromDispatcher` for `vulkan.hpp` loader and `vulkan_raii.hpp` instance and device loaders)**
