### ISSUE TITLE
vmaGetBudget unusably slow

### ISSUE THREAD

**Issue by gvcallen** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#204]
We have an application which is consistently allocating and freeing memory buffers. The reason we need this is because the total size of our data is practically unknown, so we load data in "chunks" based on proximity to the view point.

Before allocating additional memory, we query vmaGetBudget in order to determine the percentage of DEVICE_LOCAL memory that has been used. When this reaches a certain limit, we free up old chunks and retry the allocations. We are working with very large datasets with many chunks. I am mentioning this to illustrate that we need to call vmaGetBudget many times in total i.e. before each chunk allocation.

We have done timings and calling vmaGetBudget is unusably slow. We are not sure if we are doing something wrong or not. On average, each call takes around 4 to 5 ms. For a small area, we get 1977ms for 419 calls. For a large area (1.1 million triangles) we get 19154ms for 2473 calls. Of course 20 seconds just for querying memory budget is unusable.

We are using the vulkan memory budget extension, and are calling vmaSetCurrentFrameIndex for each imageIndex acquired from vkAcquireNextImageKHR (not sure if this is the correct usage as docs are slightly unclear?).

Is 4ms expected from this function? I can't imagine that it is.

Help on this would be appreciated. Not sure if this is a bug or not! Thanks a lot.

**Comment by adam-sawicki-a** [comment]
I'm closing this ticket due to inactivity. Please let me know if you meet any further problems with this.
