### ISSUE TITLE
VMA_DYNAMIC_VULKAN_FUNCTIONS and VK_NO_PROTOTYPES

### ISSUE THREAD

**Issue by chaoticbob** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#211]
Hi,

Just a heads up, I might have misunderstanding of how VMA_DYNAMIC_VULKAN_FUNCTIONS is suppose to be used with VK_NO_PROTOTYPES...so please correct me if that's case. 

In my current project, I have VK_NO_PROTOTYPES to prevent accidental `vk*` calls...and this is forcing me to use VMA_DYNAMIC_VULKAN_FUNCTIONS. So during VMA intiailization, I pass a pointer to a VmaVulkanFunctions to VmaAllocatorCreateInfo. Unfortunately, this is where I run into a bit of trouble because VMA is still expecting `vkGetInstanceProcAddr` and `vkGetDeviceProcAddr` to be defined somewhere when it gets used in `VmaAllocator_T::ImportVulkanFunctions_Dynamic()`.

So if I'm misunderstanding the intended usage here, would appreciate the correction.

If it's somehow on the case, is it possible to allow `vkGetInstanceProcAddr` and `vkGetDeviceProcAddr` to get passed in via pointers if VK_NO_PROTOTYPES is active? Or is there a better path?

Thanks!

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this issue. You are right, `VMA_DYNAMIC_VULKAN_FUNCTIONS` was implemented in a hacky way. I changed it - added `VmaVulkanFunctions::vkGetInstanceProcAddr`, `vkGetDeviceProcAddr`, which are now required when using `VMA_DYNAMIC_VULKAN_FUNCTIONS`. Please let me know whether it works for you.

**Comment by chaoticbob** [comment]
Hi Adam - thank you for making these changes. Working quite well!
