### ISSUE TITLE
Static linking vulkan functions broken

### ISSUE THREAD

**Issue by jeremyong** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#215]
VmaUsage.h has the following preprocessor definitions hardcoded:

```
#define VMA_STATIC_VULKAN_FUNCTIONS 0
#define VMA_DYNAMIC_VULKAN_FUNCTIONS 1
```

These bypass any sort of checking or compiler passed flags via the cmake var `VMA_DYNAMIC_VULKAN_FUNCTIONS`.

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this problem. We also noticed that these two settings set from Cmake were not properly defining macros as 0 or 1. Hopefully this is all fixed now.

**Comment by jeremyong-az** [comment]
Thanks! I'm sure the dynamic linking flow is more common but the static linkage model is helpful for testing apps and whatnot.
