### ISSUE TITLE
using VMA_USE_STL_CONTAINERS breaks the build

### ISSUE THREAD

**Issue by birsoyo** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#216]
Using `VMA_USE_STL_CONTAINERS` breaks the build with
```
vk_mem_alloc.h(8621): error C2440: 'return': cannot convert from 'std::reverse_iterator<std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>>>' to 'std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>>'
```
Basically, STL iterators do not have reverse_iterator conversion constructors.

**Comment by adam-sawicki-a** [comment]
We removed `VMA_USE_STL_CONTAINERS` completely. The library now always uses its own containers, which simplified the code.
