### ISSUE TITLE
Unable to set VMA_STATIC_VULKAN_FUNCTIONS to OFF when integrating cmake project

### ISSUE THREAD

**Issue by snuffick** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#218]
If VMA_STATIC_VULKAN_FUNCTIONS is set to OFF it is ignored in the src/CMakeLists.txt, and it will be forced to ON.

**Comment by medranSolus** [comment]
Hi, it was a bug, but I fixed it now.

*Marek Machliński, Developer Technology Engineer Intern, AMD*
