### ISSUE TITLE
VMA doesn't support render doc? 

### ISSUE THREAD

**Issue by Cazadorro** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#219]
I'm trying to use buffer device address, and that doesn't appear to work with renderdoc.  I tried seeing if I could manually set up the replay feature, but that doesn't appear possible... at all? 

The problem with this is that I straight up can't use render doc with out the ability to toggle this feature, so the excuse used here 
[Please note that the library supports only VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT*. The second part of this functionality related to "capture and replay" is not supported, as it is intended for usage in debugging tools like RenderDoc, not in everyday Vulkan usage.](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/enabling_buffer_device_address.html).  What this effectively is saying, is that I can't debug my memory allocations... I don't understand this logic.

**Comment by adam-sawicki-a** [comment]
I am sorry but I don't fully understand your question. Can you please clarify what error do you experience? Capturing a frame from an app that uses VMA using RenderDoc works for me.

That quote from the documentation only means that VMA doesn't provide any functions that would interact with "capture and replay" part of that extension. You can still enable `VkPhysicalDeviceBufferDeviceAddressFeatures::bufferDeviceAddressCaptureReplay` and, for example, you can attach `VkMemoryOpaqueCaptureAddressAllocateInfo` to `VkMemoryAllocateInfo` and still use VMA by creating a custom pool for your allocation with the structure attached to `VmaPoolCreateInfo::pMemoryAllocateNext`.

**Comment by Cazadorro** [comment]
Even if I don't use buffer device address, merely enabling it on the VMA allocator causes [DEVICE_LOST in renderdoc](https://github.com/baldurk/renderdoc/issues/2416). That straight up shouldn't happen, though it's hard to tell whose "fault" that is.  

When I originally read that line, *I* thought it meant "As a normal user of VMA **who is not a developer of a debugging application** I shouldn't have to worry about doing anything special".   I see now it must mean *I cannot use VMA normally and buffer device address at all if I plan on debugging my application*.   This is a massive problem, even if it doesn't have an easy engineering solution.  My expectation as a naïve user would have been that I could use VMA normally all else considered, especially considering render doc itself is specifically mentioned. 

If I were to user your solution, I would need to manually create a memory pool for each type of allocation I would hope to create, keep that behind the scenes, and choose at runtime.  It would be even worse if I had to choose for each allocation.  This doesn't seem like a tenable solution, as this problem supposedly infects *every* allocation I have regardless if one actually needs/uses buffer device address.

**Comment by adam-sawicki-a** [comment]
My intention was exactly this and it seems to work for me:
> "As a normal user of VMA who is not a developer of a debugging application I shouldn't have to worry about doing anything special"

The sample application of VMA - VmaSample has BUFFER_DEVICE_ADDRESS enabled by default wherever available and I was able to capture a frame from this application with RenderDoc successfully. My environment: Radeon RX 6800 XT, driver 21.12.1, Windows 10, Vulkan SDK 1.2.198.1, RenderDoc 1.17.

If it doesn't work for you, please attach a debugger and see why the crash happens - what kind of crash is it and what is the call stack. Please also enable Vulkan validation layers and see if there are no errors reported.
