### ISSUE TITLE
clang: compilation errors

### ISSUE THREAD

**Issue by Andreyogld3d** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#223]
Hi! 
I have compilation error using Android Studio with clang

vk_mem_alloc.h:2390:26: error: nullability specifier '_Nonnull' cannot be applied to non-pointer type 'VmaVirtualAllocation' (aka 'unsigned long long')

https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/include/vk_mem_alloc.h#L2390
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/include/vk_mem_alloc.h#L2415
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/include/vk_mem_alloc.h#L2432
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/include/vk_mem_alloc.h#L17657
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/include/vk_mem_alloc.h#L17675
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/include/vk_mem_alloc.h#L17695

error: cannot initialize return object of type 'VmaAllocHandle' (aka 'unsigned long long') with an rvalue of type 'nullptr_t'
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/include/vk_mem_alloc.h#L11684
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/include/vk_mem_alloc.h#L11687

**Comment by medranSolus** [comment]
Hi and thanks for pointing that out! It should now be fixed but please let me know if everything works fine for you.

*Marek Machliński, Developer Technology Engineer Intern, AMD*

**Comment by adam-sawicki-a** [comment]
@expipiplus1 It seems we cannot use `VMA_NULLABLE` / `VMA_NOT_NULL` annotations for the new `VmaVirtualAllocation` as it is defined using `VK_DEFINE_NON_DISPATCHABLE_HANDLE` which on some platforms is an integer not a pointer. If this is a problem please discuss with @IAmNotHanni as we are coding the library in C++ for 64-bit Windows so we have no development environment to test either Android or Haskell.

**Comment by Andreyogld3d** [comment]
Hi @adam-sawicki-a 
I have no errors foe new version, I see only a lot of Warnings:
C/C++: ../../../../../../lib/VulkanMemoryAllocator\vk_mem_alloc.h:917:28: warning: type nullability specifier '_Nullable' is a Clang extension [-Wnullability-extension]
C/C++: ../../../../../../lib/VulkanMemoryAllocator\vk_mem_alloc.h:264:30: note: expanded from macro 'VMA_NULLABLE'
...
C/C++: ../../../../../../lib/VulkanMemoryAllocator\vk_mem_alloc.h:17803:80: warning: type nullability specifier '_Nonnull' is a Clang extension [-Wnullability-extension]
...
C/C++: ../../../../../../lib/VulkanMemoryAllocator\vk_mem_alloc.h:17804:11: warning: type nullability specifier '_Nullable' is a Clang extension [-Wnullability-extension]

Issue can be closed

**Comment by adam-sawicki-a** [comment]
What platform and compiler do you use? Macros like `VMA_NULLABLE`, `VMA_NOT_NULL` are defined as not empty only `#ifdef __clang__` so they are used only when available. All of them are also defined only `#ifndef VMA_NULLABLE` etc., so if you use Clang and still get warnings please define them as empty before `#include` of VMA or propose an improvement to the `#ifdef` that enables them conditionally so they are used only when available.

**Comment by Andreyogld3d** [comment]
I Use Android Studio with clang compiler for Android NDK 23.1.7779620:

C:/../clang.exe  --version                  
Android (7714059, based on r416183c1) **clang version 12.0.8** (https://android.googlesource.com/toolchain/llvm-project c935d99d7cf2016289302412d708641d52d2f7ee)                                                      Target: x86_64-w64-windows-gnu                                                                                                                                                                                     Thread model: posix
https://github.com/android/ndk/wiki/Changelog-r23

**Comment by expipiplus1** [comment]
> @expipiplus1 It seems we cannot use `VMA_NULLABLE` / `VMA_NOT_NULL` annotations for the new `VmaVirtualAllocation` as it is defined using `VK_DEFINE_NON_DISPATCHABLE_HANDLE` which on some platforms is an integer not a pointer. If this is a problem please discuss with @IAmNotHanni as we are coding the library in C++ for 64-bit Windows so we have no development environment to test either Android or Haskell.

Sorry I missed this. Individual things like this aren't hard to work around for the Haskell bindings, so :+1:
