### ISSUE TITLE
Warning in 32 bit Windows build

### ISSUE THREAD

**Issue by TheLavaBlock** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#225]
Hi!

Unfortunately there is a warning when we build it in 32 bit on Windows:

`D:\a\liblava\liblava\ext\VulkanMemoryAllocator\include\vk_mem_alloc.h(3136,27): warning C4293: '<<': shift count negative or too big, undefined behavior [D:\a\liblava\liblava\build\lava.base.vcxproj]`

https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/a4d39851fd7c76aa78846057bc3522546062fcfb/include/vk_mem_alloc.h#L3136

**Comment by adam-sawicki-a** [comment]
Thank you for noticing this. I fixed it.
