### ISSUE TITLE
Make reliance of extensions optional

### ISSUE THREAD

**Issue by achienbsi** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#23]
The code uses structures and prototypes from these extensions:

VK_KHR_get_memory_requirements2
VK_KHR_dedicated_allocation

On Android, they are not supported and not defined in vulkan.h. For the most part it can be work around by defining them locally in the cpp file including vk_mem_alloc.h however it's not possible to redefine VkStructureType to include a couple missing ones being used.

**Comment by achienbsi** [comment]
Here are the lines causing problems
[diff.txt](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/files/1861434/diff.txt)

**Comment by adam-sawicki-amd** [comment]
Thank you very much for finding this issue and proposing solution. I found out that there are macros defined by Vulkan header when these extensions are available, so I decided to use them, so you don't need to explicitly enable/disable anything for VMA. Can you please verify if the code I pushed to "development" branch works for you?

**Comment by achienbsi** [comment]
That works!

**Comment by adam-sawicki-amd** [comment]
Thanks.
