### ISSUE TITLE
Out of bound memory access in TLSF implementation

### ISSUE THREAD

**Issue by AdamYuan** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#231]
[previous issue](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/230
)
Well, after some test, I believe the bug still exist.
I add a assertion in the vma header as followed:
```c++
void VmaBlockMetadata_TLSF::InsertFreeBlock(Block* block)
{
    // ...
    uint32_t index = GetListIndex(memClass, secondIndex);
    VMA_ASSERT(index < m_ListsCount); // THE ASSERTION
    block->PrevFree() = VMA_NULL; // Line 10342
    block->NextFree() = m_FreeList[index];
    m_FreeList[index] = block;
    if (block->NextFree() != VMA_NULL)
    // ...
```
And in the example code (compiled in debug mode)
```c++
#define VMA_IMPLEMENTATION
#include "vk_mem_alloc.h"

#include <cstdio>
#include <cstdlib>

VmaVirtualBlock block{VK_NULL_HANDLE};

int main() {
	{
		VmaVirtualBlockCreateInfo info = {};
		info.flags = VMA_VIRTUAL_BLOCK_CREATE_TLSF_ALGORITHM_BIT;
		info.size = 50331648;
		vmaCreateVirtualBlock(&info, &block);
	}
	{
		VmaVirtualAllocationCreateInfo info = {};
		info.alignment = 2;

		VmaVirtualAllocation allocation[3] = {};

		info.size = 576;
		vmaVirtualAllocate(block, &info, allocation + 0, nullptr);

		info.size = 648;
		vmaVirtualAllocate(block, &info, allocation + 1, nullptr);

		vmaVirtualFree(block, allocation[0]);

		info.size = 720;
		vmaVirtualAllocate(block, &info, allocation + 2, nullptr);
	}
	return 0;
}
```
the assertion fails, which indicates there are surely some memory access errors.
This can cause segfault in more complex scenarios.

**Comment by medranSolus** [comment]
Hi and thank you for bringing up this issue! Unfortunately when I tested it with code you provided the mentioned assert did not fire. Could you please share what values are present in variables `memClass`, `secondIndex`, `index` and `block->size`? It would help me to debug this further. Also on what machine are you running this, 32 or 64 bit?

*Marek Machliński, Developer Technology Engineer Intern, AMD*

**Comment by AdamYuan** [comment]
(here's the only modifications in vma header https://github.com/AdamYuan/VulkanMemoryAllocator/commit/22c49610c646cc9ea55469f6ed22023e2a36820b)
Before the assertion failure, I print these variables and get the following
```
memClass = 47
secondIndex = 32
index = 1536
m_ListsCount = 1025
block->size = 576
```
The machine I use is 64 bit and the compiler is g++ (GCC) 11.1.0

**Comment by medranSolus** [comment]
Thank you for that data. Could you in your setup change the contents of the function `uint8_t VmaBitScanMSB(uint64_t mask)` ([line 3125](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/include/vk_mem_alloc.h#L3125)) to disable compiler intrinsic for your platform and fallback to classic loop and then post results?

*Marek Machliński, Developer Technology Engineer Intern, AMD*

**Comment by AdamYuan** [comment]
Disabling the usage of builtin_clzl: 
```
memClass = 248
secondIndex = 32
index = 7968
m_ListsCount = 7969
block->size = 576
```
but the following compiler warning occurs
```
vk_mem_alloc.h:3136:23: warning: left shift count >= width of type [-Wshift-count-overflow]
 3136 |     uint64_t bit = 1u << 63;
      |                    ~~~^~~~~
```
I changed the line to
```c++
    uint64_t bit = 1ull << 63;
```
and then got this
```
memClass = 2
secondIndex = 4
index = 68
m_ListsCount = 593
block->size = 576
```

**Comment by AdamYuan** [comment]
I changed to builtin_clzl line to
```c++
         return 63 - static_cast<uint8_t>(__builtin_clzl(mask));
```
and also got
```
memClass = 2
secondIndex = 4
index = 68
m_ListsCount = 593
block->size = 576
```

**Comment by adam-sawicki-a** [comment]
Can you please check if the bug is fixed now?

**Comment by AdamYuan** [comment]
I think it is fixed, no segfault anymore. Thanks!

**Comment by adam-sawicki-a** [comment]
This is great. Thank you for reporting this bug.
