### ISSUE TITLE
"==" is misspelled as “=” at src/Test.cpp:2495

### ISSUE THREAD

**Issue by mkx171217** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#234]
File: src/Test.cpp
Function: TestUserData
Line: 2495
"TEST(allocInfo.pUserData = numberAsPointer);" should be "TEST(allocInfo.pUserData == numberAsPointer)"

**Comment by adam-sawicki-a** [comment]
Thanks for finding this bug.
