### ISSUE TITLE
A lot of errors when compiling with -Wall -Wextra -Werror on gcc-10 v2.1.0-631-gfd82bc7

### ISSUE THREAD

**Issue by milasudril** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#236]
See the attached log file
[slask.txt] (https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/files/8055564/slask.txt)

**Comment by adam-sawicki-a** [comment]
I fixed init-order in the constructor.

Unused variables and parameters are mostly those that are used in debug configuration when `VMA_ASSERT` or other validation features are enabled, so they are not really unused. Just as I said before, the code of this library should not be bigger or more complicated just to silence these warnings.
