### ISSUE TITLE
add "#include <intrin.h>" in vk_mem_alloc.h

### ISSUE THREAD

**Issue by mkx171217** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#237]
Hi all:
　　I am using Win10 and VS2017 Community. I get the following error when compiling:
```
3>e:\mygit\vulkanmemoryallocator\src\../include/vk_mem_alloc.h(3068): error C3861: '__popcnt': identifier not found
```
　　So every time after updating the newest code, I have to manually add a line "#include <intrin.h>" in vk_mem_alloc.h。
　　Can you add this in vk_mem_alloc.h？

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this bug. Indeed, the include was missing and should be there. I've added it.
