### ISSUE TITLE
TestLinearAllocator fails

### ISSUE THREAD

**Issue by mkx171217** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#239]
Hi all:
　　TestLinearAllocator fails on my computer, like this:
![image](https://user-images.githubusercontent.com/7500850/154395708-f1423dbc-16d1-40fa-bcaf-67b36b32dceb.png)

**Comment by mkx171217** [comment]
I debugged and found that actual allocated size is larger than bufCreateInfo.size, like this:
![image](https://user-images.githubusercontent.com/7500850/154396067-5b18a65b-bec4-40ae-8d9c-7e87c8e249b3.png)

**Comment by mkx171217** [comment]
I am using Win10 and VS2017 Community. The device information on my computer is as follows:
```
Vulkan Memory Allocator Sample 2.4.0
Vulkan API version used: 1.2
physicalDeviceProperties:
    driverVersion: 0x192058
    vendorID: 0x8086 (Intel)
    deviceID: 0x5912
    deviceType: 1 (INTEGRATED_GPU)
    deviceName: Intel(R) HD Graphics 630
    limits:
        maxMemoryAllocationCount: 2115564
        bufferImageGranularity: 1 B
        nonCoherentAtomSize: 1 B
physicalDeviceVulkan11Properties:
    maxMemoryAllocationSize: 8665350144 B (8.07 GB)
physicalDeviceVulkan12Properties:
    driverID: 5 (INTEL_PROPRIETARY_WINDOWS)
    driverName: Intel Corporation
    driverInfo: Intel driver

MEMORY HEAPS:
heapCount=1, typeCount=3
Heap 0: 8665350144 B (8.07 GB) DEVICE_LOCAL
    Type 0: DEVICE_LOCAL, HOST_VISIBLE, HOST_COHERENT
    Type 1: DEVICE_LOCAL, HOST_VISIBLE, HOST_COHERENT, HOST_CACHED
    Type 2: DEVICE_LOCAL

Conclusions:
- All heaps are DEVICE_LOCAL.
- All heaps are HOST_VISIBLE.
- No types are HOST_VISIBLE but not HOST_COHERENT.
- No types are not DEVICE_LOCAL and not HOST_VISIBLE.
- No types are AMD-specific DEVICE_COHERENT or DEVICE_UNCACHED.
- No types are LAZILY_ALLOCATED.

Enabled extensions and features:
Validation layer: 1
Sparse binding: 1
VK_EXT_memory_budget: 1
VK_AMD_device_coherent_memory: 0
bufferDeviceAddress: 1
VK_EXT_memory_priority: 1
```

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this issue. I can see that allocation sizes are aligned to 32 B on your platform.

I submitted a fix. Please let me know if it fixes the bug for you or whether there are more such problems in tests.

**Comment by mkx171217** [comment]
Hi @adam-sawicki-a :
　　Unfortunately it still fails.
　　According to your hint, I debugged and found that buffer memory alignment is 64B on my platform.
![image](https://user-images.githubusercontent.com/7500850/154604737-e2ddcf31-3f69-4a8e-9722-474674df56f2.png)
　　So I replaced all "32" in function "TestLinearAllocator" with "64", and now all test cases can pass.
　　Best regards.

**Comment by adam-sawicki-a** [comment]
OK, I applied the change as you described. Thank you for checking this.
