### ISSUE TITLE
vmaDestroyBuffer can't take null allocation

### ISSUE THREAD

**Issue by achienbsi** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#24]
The document says the buffer and/or allocation can be null but null allocation will trigger assert when the function calls allocator->FreeMemory(allocation);

**Comment by adam-sawicki-amd** [comment]
Thanks for finding this bug. I pushed fix to development branch. 6530fe3a38fde2ea0183cde8acd011777da42e53
