### ISSUE TITLE
TestVirtualBlocks fails in Linux because result of 'printf("%p", void*)' differs between Windows and Linux

### ISSUE THREAD

**Issue by mkx171217** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#243]
Hi all:
　　Recently I am porting test cases in VMA to Linux. Today I find TestVirtualBlocks fails at "TEST(str.find("\"UserData\": \"0000000000000001\"") != std::string::npos)".
　　Finally I find out that the reason is when printing pointer using "printf %p", the result is different in Windows and Linux. 
　　Fox example, the following code will print "0000000000000002" in Windows, but "0x2" in Linux.
 ```
int main(void)
{
    char buf[21]{0};
    void* pUserData = (void*)(uintptr_t)2;
    //VmaPtrToStr
    snprintf(buf, 21, "%p", pUserData);
    std::cout<< buf << std::endl;
}
```
　　Unfortunately I don't know how to eliminate this difference. C11 states that "The value of the pointer is converted to a sequence of printing characters, in an implementation-defined manner".
　　Best regards.

**Comment by adam-sawicki-a** [comment]
I am sorry but the library is developed on Windows using Visual Studio. Although the library itself is cross-platform and intended to work on a variety of platforms, compilers, and GPUs, the sample app and test suite is developed and tested on Windows only. We cannot ensure continuous support for other platforms.
