### ISSUE TITLE
Mixing wprintf and printf in test cases

### ISSUE THREAD

**Issue by mkx171217** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#244]
Hi all:
　　Mixing wprintf and printf in Linux C causes one of them has no output. Fox example, The final result string in TestVirtualBlocksAlgorithmsBenchmark cannot be printed in Linux.
　　Best regards.

**Comment by adam-sawicki-a** [comment]
I am sorry but the library is developed on Windows using Visual Studio. Although the library itself is cross-platform and intended to work on a variety of platforms, compilers, and GPUs, the sample app and test suite is developed and tested on Windows only. We cannot ensure continuous support for other platforms.
