### ISSUE TITLE
VmaCountBitsSet crashes on CPUs without support for MSVC `__popcnt` (ARM, older x86)

### ISSUE THREAD

**Issue by akien-mga** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#245]
`__popcnt` is used here unconditionally for MSVC without checking that it's actually supported by the CPU:
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/dc3f6bb9159df22ceed69c7765ddfb4fbb1b6ed0/include/vk_mem_alloc.h#L3080-L3081

This has been reported to triggering a crash in Godot: https://github.com/godotengine/godot/issues/58463

I don't know much about this instruction myself but Stackoverflow seems to have decent advice on checking capability with `cpuid` here:
https://stackoverflow.com/a/42913358

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this issue. I removed usage of `__popcnt` intrinsic function. User can still provide optimized implementation by defining macro `VMA_COUNT_BITS_SET`.

I hope that functions like `_BitScanForward` are not affected in the same way?

**Comment by akien-mga** [comment]
> Thank you for reporting this issue. I removed usage of `__popcnt` intrinsic function. User can still provide optimized implementation by defining macro `VMA_COUNT_BITS_SET`.

That works, but if that optimization is important, I think you should be able to improve things to actually check CPU capabilities. The MSDN docs provide some guidance on how to check for Advanced Bit Manipulation support: https://docs.microsoft.com/en-us/cpp/intrinsics/popcnt16-popcnt-popcnt64?view=msvc-170

![image](https://user-images.githubusercontent.com/4701338/155722307-d95340f4-0bf1-4cb7-9564-52cd4621381b.png)

So far I didn't find information that would indicate that the GCC/Clang `__builtin_popcount` has a similar requirement, so you might be able to always use it, and only need to check CPU capabilities (or add a macro entry point) for MSVC. Might need double checking though.

> I hope that functions like `_BitScanForward` are not affected in the same way?

Based on https://docs.microsoft.com/en-us/cpp/intrinsics/bitscanforward-bitscanforward64?view=msvc-170 I think it might be fine, it seems supported without specific requirements on all architectures supported by MSVC:

![image](https://user-images.githubusercontent.com/4701338/155722053-1973498e-f05b-48b7-b250-07bcb3563681.png)

**Comment by akien-mga** [comment]
Reading https://stackoverflow.com/questions/60165922/stdbitsetncount-vs-builtin-popcount it sounds like `std::bitset<T>::count` might be a good cross-platform alternative? http://www.cplusplus.com/reference/bitset/bitset/count/

**Comment by adam-sawicki-a** [comment]
`std::bitset` is an STL container, so something different than we need here, where we want to just calculate bit count in a single number.

There is a nice header `<bit>` that offers what we need: https://en.cppreference.com/w/cpp/numeric/popcount but it is available only since C++20, while the library uses C++14.

So I am going to leave it as-is for now.
