### ISSUE TITLE
Error when using VMA in library

### ISSUE THREAD

**Issue by kalakuer** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#247]
I have two applications using VMA, one is dynamic library application A, and the other is static library application B. I have correctly linked to VMA Library in both applications, and they can be compiled and linked. However, when I write an executable application C, when C is linked to dynamic library A, it can run normally in release mode, but when I switch to debug mode, The error "unable to locate the entry vkGetDeviceImageMemoryRequirements on A.dll" will appear. When I link to static library B, neither mode works normally, and "unable to locate the entry vkGetDeviceImageMemoryRequirements on C.exe" will appear. The development environment I used is windows11 and visual studio 2022

**Comment by kalakuer** [comment]
Well, I found a solution. Don't use VMA_IMPLEMENTATION.  just include the head file, compile the static libraries of debug and release modes respectively(VulkanMemoryAllocatord.lib and VulkanMemoryAllocator.lib), and then link them for use

**Comment by adam-sawicki-a** [comment]
I'm glad to hear you found the solution 👍

**Comment by kalakuer** [comment]
This problem will not occur when I switch the Vulkan SDK version from 1.3.204.1 to 1.2.198.1

**Comment by paulburgess1357** [comment]
I encountered this same issue: Visual Studio 2019, Vulkan SDK 1.3.204.1.  Removing the VMA_IMPLEMENTATION macro fixed this for me as well.

**Comment by adam-sawicki-a** [comment]
This is a new function that has been added in Vulkan 1.3. Please make sure all your code uses the same version of Vulkan SDK.

You can also predefine fixed version of Vulkan to be used by VMA by defining `#define VMA_VULKAN_VERSION 1003000` (for Vulkan 1.3) or `#define VMA_VULKAN_VERSION 1002000` (if Vulkan 1.2 is enough) for all your code. This should help to investigate the issue.
