### ISSUE TITLE
[Improvement] Allow new (and future) extensions when allocating memory

### ISSUE THREAD

**Issue by reicrof** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#25]
Hi Adam,

I was wondering if you had any plan to expose the possibility to add more extensions when allocating the memory (other than the dedicated memory one).

My use case as of right now is to create memory that will be able to be exported (by using VkExportMemoryAllocateInfoKHR) so it can be used in OpenGL. But a more "general" mechanism could probably be used to expose current and future extensions as well.

Let me know what you think !
Cheers

**Comment by adam-sawicki-amd** [comment]
I'm sorry but support for external memory import/export has been considered before and decided to be left out of scope of this library. See:

https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/16#issuecomment-365931427
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/development/src/vk_mem_alloc.h#L1074

Please let me know when you find any other extensions that you would like to be supported by the library.
