### ISSUE TITLE
How do I know if buffer was allocated with coherent memory?

### ISSUE THREAD

**Issue by youss2017** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#250]
How do I know if a buffer was allocated with coherent memory to avoid unnecessary vkFlushMappedMemoryRanges?

**Comment by adam-sawicki-a** [comment]
It can be checked like this:

```cpp
VkMemoryPropertyFlags memPropFlags;
vmaGetAllocationMemoryProperties(allocator, bufAlloc, &memPropFlags);
if((memPropFlags & VK_MEMORY_PROPERTY_HOST_COHERENT_BIT) == 0)
    vmaFlushAllocation(allocator, bufAlloc, 0, VK_WHOLE_SIZE);
```

But VMA internally checks for `VK_MEMORY_PROPERTY_HOST_COHERENT_BIT`, so you can call the flush/invalidate function without much overhead - in host-coherent memory types it will not be passed to Vulkan.

**Comment by youss2017** [comment]
Thanks
