### ISSUE TITLE
Document minimum C++ standard

### ISSUE THREAD

**Issue by SpaceIm** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#252]
I don't see minimum required C++ standard of VulkanMemoryAllocator in the documentation (only if I dig into the CMakeLists).
AFAIK, it was C++11 in 2.3.0, and it's now C++14 in 3.0.0.

**Comment by adam-sawicki-a** [comment]
Thank you for this suggestion. It was mentioned in README.md but not in Doxygen documentation. I added it.

C++14 is only a minor update that fixes some missing pieces after major C++11, so I hope that 8 years after its release it can be a required version 😀
