### ISSUE TITLE
How to use in C projects

### ISSUE THREAD

**Issue by jesta88** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#26]
I made multiple attempts at using VMA as-is in a C project with both Visual Studio and CMake without success.

As soon as I define VMA_IMPLEMENTATION and include vk_mem_alloc.h, it breaks the std lib (basic types like size_t are no longer recognized), and I see a lot of errors in the implementation part of VMA.

To bypass this, I usually create a separate C++ lib for VMA, but it's not ideal. I usually only work with C so maybe I'm missing something obvious.

**Comment by jesta88** [comment]
Ok, turns out the weirdness is only caused by this:
`#ifdef __INTELLISENSE__
#define VMA_IMPLEMENTATION
#endif`

For C projects inside VS, this has to be commented. A potential fix would be adding a 
`#if defined(__cplusplus)` in there

**Comment by adam-sawicki-amd** [comment]
I submitted potential fix to "development" branch. Can you please check if it solves the problem for you?

**Comment by jesta88** [comment]
Works great, thanks!
