### ISSUE TITLE
Creating a GPU-only buffer trips IsMappingAllowed VMA_ASSERT when using VMA_DEBUG_INITIALIZE_ALLOCATIONS

### ISSUE THREAD

**Issue by rumblehhh** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#260]
We recently migrated to v3.0.0 along with the new API for selecting preferred memory types.
We use VMA_DEBUG_INITIALIZE_ALLOCATIONS in our debug builds to help identify memory corruption issues.

Following https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/usage_patterns.html we create GPU-only buffers with vmaCreateBuffer as follows:

Setup VmaAllocationCreateInfo:
VmaAllocationCreateInfo allocCreateInfo = {};
allocCreateInfo.usage = VMA_MEMORY_USAGE_AUTO;
allocCreateInfo.flags = VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT;

Setup VkBufferCreateInfo with buffer usage flags:
VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_SRC_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT

In combination VmaAllocation_T::IsMappingAllowed returns false for the resulting dedicated allocation which trips a VMA_ASSERT in VmaAllocation_T::BlockAllocMap() when attempting to call FillAllocation which seems wrong to me.

We can workaround the issue by removing VMA_DEBUG_INITIALIZE_ALLOCATIONS for now so its not a huge issue for us.

Please let me know if you need anymore information relating to this issue.

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this issue. I confirm it was a bug. Please let me know if the fix I committed works for you.

**Comment by rumblehhh** [comment]
Thanks for the swift fix! I can confirm that fixes the issue I was seeing
