### ISSUE TITLE
VmaQuickSort is never used

### ISSUE THREAD

**Issue by laurelkeys** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#262]
`VmaQuickSort` is only defined if the macro `VMA_SORT` hasn't been, so that it can be used for implementing it:
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/5ab8c1752ab9720b7a38a3bc72ebcf17ef3ce6f1/include/vk_mem_alloc.h#L3415

However, if not defined by the user, `VMA_SORT` will currently always get defined to `std::sort` as this comes before `VmaQuickSort`:
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/5ab8c1752ab9720b7a38a3bc72ebcf17ef3ce6f1/include/vk_mem_alloc.h#L2799-L2801

While `VmaQuickSort` (and `VmaQuickSortPartition`) could be deleted because of this, the other alternative would be to remove the use of `std::sort`. Then, as far as I can see, `<algorithm>` would only be used for `std::min` and `std::max`, which makes it appealing to delete this header include altogether.

**Comment by laurelkeys** [comment]
Also, it looks like `<utility>` is only included for `std::swap` and `std::forward`.

Since this is also a big header, I believe it would be nice to replace it with a custom `VmaSwap` implementation (if `VMA_SWAP` isn't user-defined) and a new `VMA_FORWARD` macro following this: https://www.foonathan.net/2020/09/move-forward/

**Comment by adam-sawicki-a** [comment]
Thank you for this suggestion. I agree that `VmaQuickSort` and `VmaQuickSortPartition` are unused and can be removed, which I just did. User of the library can provide his own implementation of `VMA_SORT`, but when he doesn't, the default is to use `std::sort`. Custom sorting algorithm was a legacy of some old code.

I don't want to reimplement custom sorting, `std::forward`, and other basic facilities just to remove `#include` of some standard library header and save some milliseconds of compilation time. I know this is a common approach among C++ programmers, but I think the standard library is carefully designed and well tested, so I would rather rely on it than implement everything on my own.
