### ISSUE TITLE
Allocate memory with HOST_ACCESS_SEQUENTIAL_WRITE and data clear

### ISSUE THREAD

**Issue by FuXiii** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#268]
When I use `VMA` to create the memory of `VkBuffer` use `HOST_ACCESS_SEQUENTIAL_WRITE`, then I `map` the memory and use `memcpy(...)` to fill data into it.

the code maybe looks like:
```CXX
typedef struct POSITION
{
    float x;
    float y;
    float z;
} POSITION;

std::vector<POSITION> POSITION_data;//the vertex position data

Buffer *position_buffer = new Buffer(device, 0, BufferUsageBits::VERTEX_BUFFER | BufferUsageBits::TRANSFER_DST, MemoryFlagsBits::HOST_ACCESS_SEQUENTIAL_WRITE, sizeof(POSITION) * POSITION_data.size());
void *position_buffer_ptr = position_buffer->Map();
memcpy(position_buffer_ptr, POSITION_data.data(), sizeof(POSITION) * POSITION_data.size());
position_buffer->Unmap();
position_buffer->Flush();
```
then use `vkCmdBindVertexBuffers(...)` to binding it. The drawing result just fine:

but if I clear the `POSITION_data`, all things are disappeared，and use `RenderDoc` to see the shader vertex input is `null`.
the code maybe looks like:
```CXX
void *position_buffer_ptr = position_buffer->Map();
memcpy(position_buffer_ptr, POSITION_data.data(), sizeof(POSITION) * POSITION_data.size());
position_buffer->Unmap();
position_buffer->Flush();
POSITION_data.clear();//<-- just clear src data after copied into buffer memory
```

Why? What should I do? I think if I had copied into `dst memory` from `src memory`, I just clear `src`,in common that should not influence the `dst`

**Comment by adam-sawicki-a** [comment]
You are right. After `memcpy`, you should be able to clear, modify, or even free the source memory. There must be something else wrong with your code that needs debugging. I can see you also use some object-oriented wrapper for VMA - please also check what is it doing under the hood.

**Comment by FuXiii** [comment]
Yes, you are right when I create `Index Buffer`:
```CXX
TBuffer *index_buffer = new TBuffer(device, 0, TBufferUsageBits::BUFFER_INDEX_BUFFER | 
TBufferUsageBits::BUFFER_TRANSFER_DST, TMemoryFlagsBits::HOST_ACCESS_SEQUENTIAL_WRITE, sizeof(uint32_t) * INDICES_data.size());
void *index_buffer_ptr = index_buffer->Map();
memcpy(index_buffer_ptr, INDICES_data.data(), sizeof(uint32_t) * INDICES_data.size());
index_buffer->Unmap();
INDICES_data.clear();
```
I forgot I use `INDICES_data.size()` to rendeing scene:
```CXX
...
 command_buffer->CmdDrawIndexed(INDICES_data.size(), 1, 0, 0, 0);//because the INDICES_data had been cleared
...
```
Awwww stupid mistake, sorry my bad. °(°ˊДˋ°) °
