### ISSUE TITLE
Apple Clang 13.4 build errors

### ISSUE THREAD

**Issue by richard-lunarg** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#269]
Since updating to XCode 13.4, I'm getting many new errors when I include vk_mem_alloc.h.

/Users/lunarg/VulkanSDK/1.3.214.0/macOS/include/vma/vk_mem_alloc.h:12752:9: note: conversion candidate of type 'void (*)(int *, int *)'
In file included from /Users/lunarg/Dev/macsdk/Vulkan-SDK-Packaging/SDK_creation/common/sdk_tests/vmaTest/vma_test.cpp:16:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/vector:275:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__bit_reference:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/algorithm:701:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/make_heap.h:15:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/sift_down.h:51:9: error: no matching function for call to object of type '(lambda at /Users/lunarg/VulkanSDK/1.3.214.0/macOS/include/vma/vk_mem_alloc.h:12751:5)'
    if (__comp(*__child_i, *__start))
        ^~~~~~

**Comment by adam-sawicki-a** [comment]
Thank you for reporting the bug. Can you please check if replacing function `SortByFreeSize` with this implementation fixes it?

```cpp
void VmaBlockVector::SortByFreeSize()
{
    VMA_SORT(m_Blocks.begin(), m_Blocks.end(),
        [](VmaDeviceMemoryBlock* b1, VmaDeviceMemoryBlock* b2)
        {
            return b1->m_pMetadata->GetSumFreeSize() < b2->m_pMetadata->GetSumFreeSize();
        });
}
```

**Comment by richard-lunarg** [comment]
It did fixe some errors. Still seeing a few, looks like a simple typo:
/Users/lunarg/Dev/macsdk/Vulkan-SDK-Packaging/SDK_creation/common/sdk_tests/vmaTest/vma_test.cpp:108:25: error: no member named 'vulkanApiVersioin' in 'VmaAllocatorCreateInfo'; did you mean 'vulkanApiVersion'?
    allocatorCreateInfo.vulkanApiVersioin = VK_API_VERSION_1_2;
                        ^~~~~~~~~~~~~~~~~
                        vulkanApiVersion
/Users/lunarg/VulkanSDK/1.3.214.0/macOS/include/vma/vk_mem_alloc.h:1063:14: note: 'vulkanApiVersion' declared here
    uint32_t vulkanApiVersion;
             ^
/Users/lunarg/Dev/macsdk/Vulkan-SDK-Packaging/SDK_creation/common/sdk_tests/vmaTest/vma_test.cpp:110:34: error: use of undeclared identifier 'logicalDevice'
    allocatorCreateInfo.device = logicalDevice;
                                 ^
/Users/lunarg/Dev/macsdk/Vulkan-SDK-Packaging/SDK_creation/common/sdk_tests/vmaTest/vma_test.cpp:118:5: error: use of undeclared identifier 'vmaDeleteAllocator'; did you mean 'vmaDestroyAllocator'?
    vmaDeleteAllocator(&allocator);
    ^~~~~~~~~~~~~~~~~~
    vmaDestroyAllocator
/Users/lunarg/VulkanSDK/1.3.214.0/macOS/include/vma/vk_mem_alloc.h:16018:33: note: 'vmaDestroyAllocator' declared here
VMA_CALL_PRE void VMA_CALL_POST vmaDestroyAllocator(
                                ^
/Users/lunarg/Dev/macsdk/Vulkan-SDK-Packaging/SDK_creation/common/sdk_tests/vmaTest/vma_test.cpp:118:24: error: cannot initialize a parameter of type 'VmaAllocator' (aka 'VmaAllocator_T *') with an rvalue of type 'VmaAllocator *' (aka 'VmaAllocator_T **')
    vmaDeleteAllocator(&allocator);
                       ^~~~~~~~~~
/Users/lunarg/VulkanSDK/1.3.214.0/macOS/include/vma/vk_mem_alloc.h:16019:18: note: passing argument to parameter 'allocator' here
    VmaAllocator allocator)
                 ^
772 warnings and 4 errors generated.

**Comment by richard-lunarg** [comment]
YES. That did the trick. Can you create a new tag with this fix so we can use it in the SDK?

**Comment by adam-sawicki-a** [comment]
OK, I pushed the fix. I will now prepare a new tag and release and I will let you know in this ticket when it is ready.

**Comment by adam-sawicki-a** [comment]
I created new tag and release v3.0.1. I hope it works fine on all platforms.

**Comment by richard-lunarg** [comment]
Thanks! I will test on all platforms here and let you know if there's another problem.
