### ISSUE TITLE
Undefined symbols while building a project for iOS

### ISSUE THREAD

**Issue by squadack** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#284]
Hi, I'm building a project for iOS and I've ran into a problem with linking - symbols `vkGetDeviceBufferMemoryRequirements` and `vkGetDeviceImageMemoryRequirements` are undefined as MoltenVK is an implementation of Vulkan 1.1 but the headers supplied with MoltenVK define `VK_VERSION_1_3`. This causes an error while linking in `ImportVulkanFunctions_Static()` function.

The obvious workaround is to define `VMA_STATIC_VULKAN_FUNCTIONS` as `0` or `VMA_VULKAN_VERSION` as `1001000` when building for iOS, but i'm wondering if this could be done by default by this library?

**Comment by wolfpld** [comment]
@squadack forgot to link the issue in MoltenVK repo: https://github.com/KhronosGroup/MoltenVK/issues/1708

**Comment by adam-sawicki-a** [comment]
I think this is a problem in MoltenVK. According to Vulkan specification, function `vkGetDeviceBufferMemoryRequirements` is `Provided by VK_VERSION_1_3`. If Vulkan headers on your platform define `VK_VERSION_1_3` but don't define `vkGetDeviceBufferMemoryRequirements` or don't export this function from the static library, this is a situation unseen in any "normal" Vulkan implementation.

Unlike what @spnda said in that linked ticket, I am wondering, without assuming these two things always match, how could we even write any code that links Vulkan statically if any of the new functions could be not exported on some platform?

I recommend to use `VMA_STATIC_VULKAN_FUNCTIONS 0` or `VMA_VULKAN_VERSION 1001000` as you described.

**Comment by spnda** [comment]
> Unlike what @spnda said in that linked ticket, I am wondering, without assuming these two things always match, how could we even write any code that links Vulkan statically if any of the new functions could be not exported on some platform?

When you statically link you link against the Vulkan loader lib which will almost always be the same version as the Vulkan headers, you get stubs for all Vulkan functions. However, with MoltenVK it is possible to directly link to the driver and have it act as a loader. After thinking about it, I think I agree that MoltenVK should instead provide function stubs for all core functions.

Though in the end, I feel like having the Vulkan loader as a lib was a mistake anyway and you should ALWAYS use dynamic function loading. Nevertheless, I think I will make a PR to MoltenVK adding these method stubs just for compatibility.
