### ISSUE TITLE
about function IsMemoryTypeNonCoherent

### ISSUE THREAD

**Issue by Judgecut** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#289]
My graph card is NVIDIA rtx2070s，when I create buffer use VMA_MEMORY_USAGE_GPU_TO_CPU，find buffer‘s memory support VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT and VK_MEMORY_PROPERTY_HOST_CACHED_BIT 。this is only support **VK_MEMORY_PROPERTY_HOST_CACHED_BIT** memory in my card.

Of course，I use this buffer call function FlushOrInvalidateAllocation is failed.
In my test,  this buffer feadback data is error without call InvalidateAllocation in same times.

**Comment by adam-sawicki-a** [comment]
I am sorry but I don't understand your question. Can you please elaborate some more and give more details, specifics of what functions do you call, what parameters do you pass, and what results do you observe?

**Comment by Judgecut** [comment]
1.rtx 2070s only memoryTypes[xxx].propertyFlags == 14 support VK_MEMORY_PROPERTY_HOST_CACHED_BIT in total memorytypes.
2.create buffer use VMA_MEMORY_USAGE_GPU_TO_CPU by call function vmaFindMemoryTypeIndex()，buffer memorytype propertyFlags is 14（VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT | VK_MEMORY_PROPERTY_HOST_CACHED_BIT）
my question is use step 2 buffer readback gpu write data，make available to the host memory domain is need call vmaInvalidateAllocation() ? 

if need, call vmaInvalidateAllocation() will failed by IsMemoryTypeNonCoherent(buffer memorytype == 14 function return false).
if not, I don't kown data is it necessarily correct.

**Comment by adam-sawicki-a** [comment]
A call to vmaInvalidateAllocation() is not needed for this memory type because it has VK_MEMORY_PROPERTY_HOST_COHERENT_BIT flag. When you write to this buffer from the GPU, then access the data through a mapped pointer on the CPU, you will see correct data, but you must not forget about proper synchronization between these two operations - to do a proper barrier on the GPU and to wait for a fence, for example.

**Comment by Judgecut** [comment]
thanks
