### ISSUE TITLE
VkDeviceSize has an issue on 32-bit on vk_mem_alloc.h.

### ISSUE THREAD

**Issue by locke-lunarg** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#293]
`WriteSize` only passes `size_t`. On 32-bit, `VkDeviceSize` can't find `uint64_t` of `WriteSize`. Thank you very much.

**Comment by adam-sawicki-a** [comment]
Thank you for reporting the problem. I submitted a fix. Please let me know if it helps.

**Comment by locke-lunarg** [comment]
Thank you. It got fixed.
