### ISSUE TITLE
Is it possible to separate m_VulkanApiVersion into vkInstance's and vkPhysicalDevice's ApiVersion on vk_mem_alloc.h.?

### ISSUE THREAD

**Issue by locke-lunarg** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#294]
I think if we can set both VkInstance's and VkPhysicalDevice's ApiVersion, it looks more clear. Thank you very much.

**Comment by adam-sawicki-a** [comment]
Please let me know if clarification in the documentation I introduced by commit 68d5105, as requested in #384, solves the problem.

**Comment by locke-lunarg** [comment]
It looks good. Thank you!
