### ISSUE TITLE
Usage of VMA_RECORDING_ENABLED and its effect

### ISSUE THREAD

**Issue by edvn0** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#295]
Hello,

I'm a very pleased user of this library, and would never not recommend it to a colleague or a friend.

I'm at the end of the road on a validation layer problem in my program, where the layers complain that two (2) instances 
of VkDeviceMemory are somehow not cleaned up. Nowhere in my source code do I anymore use VkDeviceMemory, instead I delegate all of memory initialisation and allocation to this library.

This naturally causes the VMA library to crash at program exit, aborting at vmaDestroyAllocator, something I call at the very end (after the destruction of the application).

Therefore, I thought that I could just `target_compile_definitions(myproject PRIVATE VMA_RECORDING_ENABLED)` and upon exit, would be greeted with information about the currently allocated state.

Is this no longer supported, or in which ways am I doing things incorrectly?

Thank you for a fantastic library and a very decent API.

**Comment by adam-sawicki-a** [comment]
Hello,

I am sorry but the "record & replay" feature has been removed in VMA 3.0.0. Please use some other means of debugging to find the memory leak. Unfreed `VkDeviceMemory` objects likely mean that you have some unreleased VMA allocations or custom pools. You can, for example, define macro `VMA_DEBUG_LOG` to get the list of unfreed allocations and their string names (if you assign them) printed to some text output.

**Comment by edvn0** [comment]
Aha. Thank you. 

Upon compilation on a apple-clang (1400.0.29.202), enabling VMA_DEBUG_LOG leads to compilation errors of "error: called object type 'int' is not a function or function pointer" for "VMA_DEBUG_LOG("VmaCreateAllocator")" in vk_mem_alloc.h:16031:18. 

This obviously fails at numerous places, but thought I'd provide a decent example.

**Comment by adam-sawicki-a** [comment]
I am sorry but I don't have a development environment to test it on apple-clang. The library is developed mostly on and for Windows. Please try to define `VMA_DEBUG_LOG` macro to an implementation that works on your platform, considering the parameters it is called with.

**Comment by adam-sawicki-a** [comment]
Closing this ticket due to inactivity. Please feel free to comment if you have any further questions.
