### ISSUE TITLE
Unused Variables in vk_mem_alloc.h

### ISSUE THREAD

**Issue by kjlubick** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#298]
In vk_mem_alloc.h, there are several instances of a variable called unusedRangeSize being created and then not used before it falls out of scope. These are:

 - [Line 8074](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L8074
)
 - [Line 8091](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L8091
)
 - [Line 8121](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L8121
)
 - [Line 8138](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L8138
) 
- [Line 8167](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L8167
)
- [Line 8184](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L8184
)

There are also:
 - name on [Line 6420](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L6420
) which is unused if `VMA_DEBUG_LOG` is a no-op
 - prevDeviceMemoryCount [on line 15412](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L15412
) which is unused if `VMA_DEBUG_DONT_EXCEED_MAX_MEMORY_ALLOCATION_COUNT` is not defined to be a true value.

**Comment by adam-sawicki-a** [comment]
Thank you for reporting these issues. I pushed some fixes.

However, when it comes to variables that are unused only when some macros are not defined, please note that documentation of this library clearly states in chapter "Features not supported":

> Code free of any compiler warnings. Maintaining the library to compile and work correctly on so many different platforms is hard enough. Being free of any warnings, on any version of any compiler, is simply not feasible. There are many preprocessor macros that make some variables unused, function parameters unreferenced, or conditional expressions constant in some configurations. The code of this library should not be bigger or more complicated just to silence these warnings. It is recommended to disable such warnings instead.

**Comment by tomilov** [comment]
One can use [[[maybe_unused]]](https://en.cppreference.com/w/cpp/language/attributes/maybe_unused) declaration attribute to mark variable (or event function (should be placed right after the name)) for cases, when usage depends on say `#ifndef NDEBUG` or something alike. Also in any C++ (or even C) version there is a "no-op" way to mark variable as used: it is `(void)my_variable;` statement provided right after definition. Macro implementation like `assert` goes this way aik.

**Comment by tomilov** [comment]
Another workaround if one use CMake is to add `-w` to `COMPILE_OPTIONS` to suppress warnings for the source file(s) includes `vk_mem_alloc.h`:
```cmake
add_library("vma")
target_source("vma" PRIVATE "vma.cpp")
set_source_files_properties(
    "vma.hpp"
    "vma.cpp"
    PROPERTIES
        COMPILE_OPTIONS "-w")
```
`vma.cpp`:
```cpp
#define VMA_IMPLEMENTATION
#include <vk_mem_alloc.h>
```

Also, if you import VMA as `git submodule` you can add `VulkanMemoryAllocator` target simply by using `add_subdirectory`, having `SYSTEM` settings (since CMake 3.25, which is not yet released).

Also it would be nice if VMA itself would export include path for `-isystem` (note presence of `SYSTEM` setting, which is actually missing currently) instead of `-I`:
```
target_include_directories(VulkanMemoryAllocator SYSTEM PUBLIC 
    $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>
)
```
It results in full warnings suppression. Sadly in standalone builds too (therefore it requires mentioned in neighboring issue `PROJECT_IS_TOP_LEVEL` dispatching).
