### ISSUE TITLE
Default case ordering and implicit fallthrough in switch statements in vk_mem_alloc.h

### ISSUE THREAD

**Issue by jeremy-cowham** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#299]
In vk_mem_alloc.h, the out-of-order positioning of the default case in switch statements triggers an implicit fallthrough static error in addition to being, in my opinion, less readable and intuitive. These cases are:

- [Line 11269](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L11269)
- [Line 11765](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L11765)
- [Line 13011](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L13011)
- [Line 13314](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L13314)
- [Line 13353](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L13353)
- [Line 13426](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L13426)
- [Line 13515](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L13515)
- [Line 13562](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L13562)
- [Line 13649](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L13649)
- [Line 13740](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L13740)
- [Line 13781](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L13781)
- [Line 13819](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L13819)
- [Line 13843](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L13843)
- [Line 13926](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L13926)

**Comment by adam-sawicki-a** [comment]
Thank you for these suggestions. I refactored some of the `switch` statements you mentioned.

However, for more complex control flow, I don't think that making the code longer and more complicated is worth it. Implicit fallthrough is an error only if you treat warnings as errors, while documentation of this library clearly states in chapter "Features not supported":

> Code free of any compiler warnings. Maintaining the library to compile and work correctly on so many different platforms is hard enough. Being free of any warnings, on any version of any compiler, is simply not feasible. There are many preprocessor macros that make some variables unused, function parameters unreferenced, or conditional expressions constant in some configurations. The code of this library should not be bigger or more complicated just to silence these warnings. It is recommended to disable such warnings instead.
