### ISSUE TITLE
Docs issue with vmaUnmapPersistentlyMappedMemory

### ISSUE THREAD

**Issue by bobvodka** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#3]
The comment/docs for vmaUnmapPersistentlyMappedMemory() reads;

> Unmaps persistently mapped memory of types that is HOST_COHERENT and DEVICE_LOCAL. 
This is optional performance optimization. You should call it on Windows for time of call to vkQueueSubmit and vkQueuePresent, for performance reasons, because of the internal behavior of WDDM.

The second half of that isn't particularly clear as to what you should and shouldn't do on Windows.

I'm torn between "don't unmap something between it being used in vkQueueSubmit and the following vkQueuePresent" and "only unmap/unmap persistently between where it is used and the following vkQueuePresent".

**Comment by adam-sawicki-amd** [comment]
OK, maybe I should rephrase it this way:

> (...) You should call it on Windows for time of +every+ call to vkQueueSubmit and vkQueuePresent. Example:
>
> vmaUnmapPersistentlyMappedMemory(allocator);
> vkQueueSubmit(...)
> vmaMapPersistentlyMappedMemory(allocator);

It is as simple as that. No need to think about which resources are actually used. Any ideas how to describe it better?

**Comment by bobvodka** [comment]
Ah, I see now.
In which case I think I would phrase it;

> (...) On Windows you should call it before every call to vkQueueSubmit and vkQueuePresent. After which you can remap the allocations again using vmaMapPersistentlyMappedMemory()
>Example:
>
>vmaUnmapPersistentlyMappedMemory(allocator); 
>vkQueueSubmit(...) 
>vmaMapPersistentlyMappedMemory(allocator);

I think that should make the usage clear.

**Comment by adam-sawicki-amd** [comment]
OK, done.
