### ISSUE TITLE
MSVC: Type "VmaAllocation_T" not defined

### ISSUE THREAD

**Issue by Zino2201** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#30]
Visual Studio prompt me that error when I compile my program, I get no link error just that.
I have a .cpp file with the VMA_IMPLEMENTATION define and included the header file after it

**Comment by Zino2201** [comment]
Fixed, I made a mistake in my code.

**Comment by Markyparky56** [comment]
> Fixed, I made a mistake in my code.
@Zino2201 
What was the mistake and how did you fix it? I'm having the same issue.

**Comment by adam-sawicki-amd** [comment]
Possibly you try to create an object of type `VmaAllocation_T` by value, not by pointer like `VmaAllocation_T*`, which is equivalent to `VmaAllocation`. You should always use it by pointer and treat it like an opaque pointer. Do not try to peek inside for member variables or functions.

**Comment by Markyparky56** [comment]
>Do not try to peek inside for member variables or functions.

Yup, that's what I'm doing.

```cpp
vmaInvalidateAllocation(*volume.allocator, volume.volumeAllocation, volume.volumeAllocation->GetOffset(), volume.volumeAllocation->GetSize());
```

Switched it over to `VmaAllocationInfo`/`vmaGetAllocationInfo` fixed it.

```cpp
VmaAllocationInfo info;
vmaGetAllocationInfo(*volume.allocator, volume.volumeAllocation, &info);
vmaInvalidateAllocation(*volume.allocator, volume.volumeAllocation, info.offset, info.size);
```

Offtopic Query: Since I can't find any reference on how to properly call `vmaInvalidateAllocation`, is that the correct usage? Should I be passing the offset and size from the allocation?

**Comment by btipling** [comment]
This was a build error for me. 

```cpp
void* data;
vmaMapMemory(_allocator, staging.allocation, &data);
memcpy(data, vertices.data(), vertexBufferSize);
memcpy((char*)data + vertexBufferSize, indices.data(), indexBufferSize);
```
removed the error
