### ISSUE TITLE
Integer overflow in VmaAllocator_T::AllocateMemoryOfType()

### ISSUE THREAD

**Issue by martin-ejdestig** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#300]
Stepped through `VmaAllocator_T::AllocateMemoryOfType()` and happened to notice what I think is an integer overflow at:

https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/936bc4b57e7ffa5906a786735537c5493224e7d6/include/vk_mem_alloc.h#L14513

When at that line in gdb:

```
(gdb) p m_PhysicalDeviceProperties.limits.maxMemoryAllocationCount 
$23 = 4294967295
(gdb) p m_PhysicalDeviceProperties.limits.maxMemoryAllocationCount * 3 / 4
$24 = 1073741823
(gdb) p static_cast<uint64_t>(m_PhysicalDeviceProperties.limits.maxMemoryAllocationCount) * 3 / 4
$25 = 3221225471
(gdb) 
```

**Comment by adam-sawicki-a** [comment]
Thank you very much for spotting this issue. I pushed a fix.
