### ISSUE TITLE
Do not import Vulkan package from CMakeLists.txt

### ISSUE THREAD

**Issue by tomilov** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#303]
Use [PROJECT_IS_TOP_LEVEL](https://cmake.org/cmake/help/latest/variable/PROJECT_IS_TOP_LEVEL.html) cmake option or [this](https://github.com/KhronosGroup/Vulkan-Headers/blob/main/CMakeLists.txt#L32) workaround to determine whether it fine to call `find_package(Vulkan)`. If VMA is submodule (`add_subdirectory`) of some project as well as Vulkan-Headers, then it is poison to inject some system-wide Vulkan headers from top level `CMakeLists.txt`.

**Comment by adam-sawicki-a** [comment]
Please note VMA is intended to be used as a single-header STB-style library with file "vk_mem_alloc.h" just copied to your project source code. By including this entire repository as a submodule and compiling VMA as a separate library you clutter your project with unnecessary files, add unnecessary complexity, and limit the ability to reconfigure VMA by changing its source code or predefining some `VMA_` macros.

**Comment by tomilov** [comment]
In case of strait file copying user loose ability to use `git submodule` command functionality to keep `vk_mem_alloc.h` up to date with origin repo. I mean there are use cases when namely git submodule way to add VMA to a project. These are important part of all use cases. In case of import VMA via `add_subdirectory` VMA project `CMakeLists.txt` can export single target (say named `vma` or `VulkanMemoryAllocator`, as repo named), having just [INTERFACE_INCLUDE_DIRECTORIES](https://cmake.org/cmake/help/latest/prop_tgt/INTERFACE_INCLUDE_DIRECTORIES.html) property set. To inject `Vulkan-Headers` unconditionally is not on the right way for the case.

**Comment by adam-sawicki-a** [comment]
I added usage of `PROJECT_IS_TOP_LEVEL` as you recommended. Please validate if it works for you.

**Comment by tomilov** [comment]
Thank you. I think this should work.

**Comment by tomilov** [comment]
`include_directories(${Vulkan_INCLUDE_DIR})` have to be also under the guards

**Comment by tomilov** [comment]
`find_package(Doxygen)` can be after `if(BUILD_DOCUMENTATION)` before `if(DOXYGEN_FOUND)`

**Comment by tomilov** [comment]
In the case checking `PROJECT_IS_TOP_LEVEL` for `Doxygen` is not necessarily required

**Comment by adam-sawicki-a** [comment]
Why is it required for Vulkan and not required for Doxygen?

**Comment by tomilov** [comment]
In case of `PROJECT_IS_TOP_LEVEL` the logic should be exactly the same, I pretty sure.

**Comment by adam-sawicki-a** [comment]
Thank you for the suggestions. I applied further changes.

**Comment by tomilov** [comment]
Thank you!

**Comment by juan-lunarg** [comment]
With the latest changes I can also confirm this isn't an issue anymore.
