### ISSUE TITLE
[cmake] Why isn't `VulkanMemoryAllocator` a header only library?

### ISSUE THREAD

**Issue by juan-lunarg** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#309]
Currently the CMake for `VulkanMemoryAllocator` is declared like this:

```
# VulkanMemoryAllocator is either static/dynamic
add_library(VulkanMemoryAllocator
    VmaUsage.cpp
    VmaUsage.h
    ${PROJECT_SOURCE_DIR}/include/vk_mem_alloc.h
)
```

However, the documentation implies VMA is a header only library.

If that's the case then VulkanMemoryAllocator should mimic [Vulkan-Headers](https://github.com/KhronosGroup/Vulkan-Headers) which is also a header only library.

**Comment by adam-sawicki-a** [comment]
VMA is not a header-only library in the way that everything is defined as inline. It is a ["STB-style" library](https://github.com/nothings/stb#how-do-i-use-these-libraries). It contains private implementation that should go to a C++ file, just packed into a single file for convenience. The implementation needs to be extracted using `VMA_IMPLEMENTATION` macro preceding `#include` of the library in exactly one CPP file. "VmaUsage.cpp" file is doing just that, allowing to use VMA as a separate library.

Please note that CMake script is an external contribution, included for convenience. Recommended way to use the library is to just add "vk_mem_alloc.h" file to user's project, [as described in the documentation](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/quick_start.html).
