### ISSUE TITLE
vmaFreeMemory generate a assert

### ISSUE THREAD

**Issue by Zino2201** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#31]
When vmaFreeMemory got called, it's generate a assert, I've tried to remove it but another assert tell me that I must free the allocations with it.. I don't know what to do

**Comment by adam-sawicki-amd** [comment]
Please provide more information so I can reproduce the bug. Also please check documentation to make sure you use the library properly.

How do you allocate memory? If you do it using functions `vmaCreateBuffer`, `vmaCreateImage`, then you get two objects from each function - `VkBuffer`/`VkImage` and `VmaAllocation` and you need to pass them both to `vmaDestroyBuffer`, `vmaDestroyImage`. There is no need to call `vmaFreeMemory` next to that.

**Comment by Zino2201** [comment]
Okay,

So first I checked the documentation and I do everything right normally:

NOTE: It's a persistant mapped uniform buffer

- First I'm creating the Buffer using `vmaCreateBuffer`
- After every frame I `memcpy `to it's data
- At the end I `vmaDestroyBuffer `and `vmaFreeMemory`

So first, I removed the `vmaFreeMemory `thanks by the way for the info!
But now the assert message is 

> Assertion failed: m_Metadata.IsEmpty() && "Some allocations were not freed before destruction of this memory block!", file c:\users\zino2201\documents\vulkanlearn\project\include\thirdparty\vma\vkmemalloc.h, line 6291

which I don't understand correctly because I am sure to `vmaDestroyBuffer `all buffers and allocations in my code. If needed, I can send you the code.

Thanks alot for the help, I really appreciate this library.

**Comment by adam-sawicki-amd** [comment]
Please make sure that you free every `VmaAllocation` that you create using `vmaCreateImage` or `vmaCreateBuffer`, by calling appropriate `vmaDestroyImage`, `vmaDestroyBuffer`. Make sure that you pass non-null allocation to them. You can also attach string names to your allocations and then print the list of all allocations to JSON format. Try to do it before you destroy allocator object, or use debugger to identify which allocation remains unfreed.

**Comment by Zino2201** [comment]
Okay after some research I found that I don't have destroyed a staged buffer... A very stupid mistake! Thanks for your help!
