### ISSUE TITLE
Is there a PDF for the documentation?

### ISSUE THREAD

**Issue by tuket** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#315]
Sorry, this is more a question than an issue, but I didn't know where to ask it. Maybe someone could enable the github community tab for this purpose? :)

Anyways, I was just wondering if there is a PDF version of [this documentation](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/index.html) available for download.

Thanks!

**Comment by adam-sawicki-a** [comment]
Documentation of the library is written using Doxygen comments. Doxygen is able to generate PDF through LaTeX. By default, Doxyfile is configured to just generate chunked HTML documentation as the output. You can change this configuration and generate documentation in PDF or other format if you want.

There are no plans to automatically generate PDF format or publish it on the Internet.

**Comment by tuket** [comment]
I managed to build the PDF. Looks pretty bad but here it is:
[refman.pdf](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/files/10517680/refman.pdf)
