### ISSUE TITLE
Missing flush in this example?

### ISSUE THREAD

**Issue by tuket** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#316]
I'm not sure but I think there might be a missing `vkFlushMappedMemoryRanges` in this [example](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/usage_patterns.html#usage_patterns_advanced_data_uploading)

This is only needed is the memory type does not have the `HOST_COHERENT` flag, I thoght it could be worth mentioning in the documentation?

Also seen this commented line:

```cpp
//vkCmdPipelineBarrier: VK_ACCESS_HOST_WRITE_BIT --> VK_ACCESS_TRANSFER_READ_BIT
```

would that barrier be able to replace a call to ```vkFlushMappedMemoryRanges`?

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this issue. You are right - a flush call was missing in this example. I fixed it.

Function `vmaFlushAllocation` checks for `HOST_COHERENT` automatically, so it can be just called without checking this flag on user side.

A barrier doesn't replace the Flush call, as far as I know - both are needed.
