### ISSUE TITLE
What is the correct pattern for allocating a vertex buffer and map it if HOST_VISIBLE?

### ISSUE THREAD

**Issue by tuket** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#317]
Let's say that we want to create a vertex buffer. We can create it with the pattern [suggested in the documentation](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/usage_patterns.html#usage_patterns_gpu_only).

Now, we would like to fill it with vertex data. We could use a staging buffer for this purpose, and copy the data over.

However, in some platforms with unified memory, the allocated vertex buffer might be directly accessible by the host (i.e HOST_VISIBLE). So we could avoid using a staging buffer.

If you add the `VMA_ALLOCATION_CREATE_MAPPED_BIT` you will get an assert, because it needs to be paired with either `VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT` or `VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT`.

Also you can use the flag `VMA_ALLOCATION_CREATE_HOST_ACCESS_ALLOW_TRANSFER_INSTEAD_BIT`, not to force it to allocate HOST_VISIBLE memory if there is a performance hit.

>     Together with #VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT or #VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT,
>     it says that despite request for host access, a not-`HOST_VISIBLE` memory type can be selected
>     if it may improve performance.
> 
>     By using this flag, you declare that you will check if the allocation ended up in a `HOST_VISIBLE` memory type
>     (e.g. using vmaGetAllocationMemoryProperties()) and if not, you will create some "staging" buffer and
>     issue an explicit transfer to write/read your data.
>     To prepare for this possibility, don't forget to add appropriate flags like
>     `VK_BUFFER_USAGE_TRANSFER_DST_BIT`, `VK_BUFFER_USAGE_TRANSFER_SRC_BIT` to the parameters of created buffer or image.

Now the problem, I have experienced with that flag is that it will allocate from the 256MB heap which is both DEVICE_LOCAL and HOST_VISIBLE.

I don't want to use this precious memory heap for vertex buffers.

So what I would like is: allocate DEVICE_LOCAL memory, preferably from a non-HOST_VISIBLE heap. If the only DEVICE_LOCAL memory happens to be HOST_VISIBLE (like in Intel integrated GPUs), then I would like to map the memory.

What I tried to do is: 1) allocate the vertex buffer as in suggested in [Usage Patterns - GPU Only](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/usage_patterns.html#usage_patterns_gpu_only). 2) Check if the allocation is HOST_VISIBLE, and map it if so.

```cpp
void createStaticVertexBuffer(VkDevice device, VmaAllocator allocator, size_t size, VkBuffer& buffer, VmaAllocation& allocation, VmaAllocationInfo* allocInfo = nullptr)
{
	const VkBufferCreateInfo bufferInfo = {
		.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
		.size = size,
		.usage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
	};
	const VmaAllocationCreateInfo allocCreateInfo = {
		//.flags = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT |
		//		VMA_ALLOCATION_CREATE_HOST_ACCESS_ALLOW_TRANSFER_INSTEAD_BIT |
		//		VMA_ALLOCATION_CREATE_MAPPED_BIT, // these flags will try to make a host visible buffer, unless that would imply performance penalty. Otherwise we will have to create a staging buffer
		.usage = VMA_MEMORY_USAGE_AUTO,
	};
	VmaAllocationInfo allocInfoVar;
	allocInfo = allocInfo ? allocInfo : &allocInfoVar;
	VkResult vkRes = vmaCreateBuffer(allocator, &bufferInfo, &allocCreateInfo, &buffer, &allocation, allocInfo);
	assertRes(vkRes);

	VmaAllocatorInfo allocatorInfo;
	vmaGetAllocatorInfo(allocator, &allocatorInfo);
	VkPhysicalDeviceMemoryProperties memProps;
	vkGetPhysicalDeviceMemoryProperties(allocatorInfo.physicalDevice, &memProps);
	auto memTypeFlags = memProps.memoryTypes[allocInfo->memoryType].propertyFlags;
	if (memTypeFlags & VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT) {
		vmaMapMemory(allocator, allocation, &allocInfo->pMappedData);
	}
}
```

But this turns out to be a bit verbose, so I was wondering if there might be a simpler way. I've seen there is the member function `IsMappingAllowed` but I think that's supposed to be internal, so it wouldn't compile.

```cpp
void createStaticVertexBuffer(VkDevice device, VmaAllocator allocator, size_t size, VkBuffer& buffer, VmaAllocation& allocation, VmaAllocationInfo* allocInfo = nullptr)
{
	const VkBufferCreateInfo bufferInfo = {
		.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
		.size = size,
		.usage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
	};
	const VmaAllocationCreateInfo allocCreateInfo = {
		//.flags = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT |
		//		VMA_ALLOCATION_CREATE_HOST_ACCESS_ALLOW_TRANSFER_INSTEAD_BIT |
		//		VMA_ALLOCATION_CREATE_MAPPED_BIT, // these flags will try to make a host visible buffer, unless that would imply performance penalty. Otherwise we will have to create a staging buffer
		.usage = VMA_MEMORY_USAGE_AUTO,
	};
	VkResult vkRes = vmaCreateBuffer(allocator, &bufferInfo, &allocCreateInfo, &buffer, &allocation, allocInfo);
	assertRes(vkRes);

	if(allocation->IsMappingAllowed())
		vmaMapMemory(allocator, allocation, &allocInfo->pMappedData);
}
```

```
error C2027: use of undefined type 'VmaAllocation_T'
```

Any hints on best ways to achieve this?

Thanks!

**Comment by adam-sawicki-a** [comment]
Thank you for detailed description of your use case. First of all, what you said:

> I don't want to use this precious memory heap for vertex buffers.

Sounds to me like you could detect that a memory type that is `DEVICE_LOCAL | HOST_VISIBLE` has only 256 MB and mask it out using `VmaAllocationCreateInfo::memoryTypeBits` so it is not selected for your vertex buffers. Then, I think everything should work as intended with your main approach of using `VMA_ALLOCATION_CREATE_MAPPED_BIT | VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT | VMA_ALLOCATION_CREATE_HOST_ACCESS_ALLOW_TRANSFER_INSTEAD_BIT`.

For checking properties of the memory where your allocation ended up, you can use convenience function `vmaGetAllocationMemoryProperties` instead of `vmaGetAllocatorInfo + vkGetPhysicalDeviceMemoryProperties` as you showed.

Please also note that flag `VK_BUFFER_USAGE_TRANSFER_DST_BIT` is not needed when you map a buffer and write to it from the CPU. It is only needed when a buffer is used as a source of GPU transfer - `vkCmdCopy*` calls.

**Comment by tuket** [comment]
Thanks for your reply!

> Sounds to me like you could detect that a memory type that is DEVICE_LOCAL | HOST_VISIBLE has only 256 MB and mask it out using VmaAllocationCreateInfo::memoryTypeBits so it is not selected for your vertex buffers. Then, I think everything should work as intended with your main approach of using VMA_ALLOCATION_CREATE_MAPPED_BIT | VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT | VMA_ALLOCATION_CREATE_HOST_ACCESS_ALLOW_TRANSFER_INSTEAD_BIT.

That would work but discriminating a heap by size feels a bit arbitrary.

> For checking properties of the memory where your allocation ended up, you can use convenience function vmaGetAllocationMemoryProperties instead of vmaGetAllocatorInfo + vkGetPhysicalDeviceMemoryProperties as you showed.

Cool! I didn't know about that function

> Please also note that flag VK_BUFFER_USAGE_TRANSFER_DST_BIT is not needed when you map a buffer and write to it from the CPU. It is only needed when a buffer is used as a source of GPU transfer - vkCmdCopy* calls.

Ah, true. I only wanted that flag in case the selected memory type was HOST_VISIBLE. I guess I need to change my solution to determine the memory type index beforehand.

**Comment by tuket** [comment]
This is yet another attempt:

```cppu32 findMemTypeForStaticVertexBuffer(VmaAllocator allocator, size_t size, VkBufferCreateInfo& bufferInfo)
{
	bufferInfo = {
		.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
		.size = size,
		.usage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
	};
	VmaAllocationCreateInfo allocCreateInfo = {
		.usage = VMA_MEMORY_USAGE_AUTO,
	};
	u32 memType;
	VkResult vkRes = vmaFindMemoryTypeIndexForBufferInfo(allocator, &bufferInfo, &allocCreateInfo, &memType);
	assertRes(vkRes);

	VkMemoryPropertyFlags memPropFlags;
	vmaGetMemoryTypeProperties(allocator, memType, &memPropFlags);
	if (memPropFlags & VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT) {
		// if the chosen memory type is HOST_VISIBLE we don't actually need the TRANSFER_DST_BIT
		bufferInfo.usage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
		allocCreateInfo.requiredFlags = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT; // probably not need but just in case
		u32 memType;
		VkResult vkRes = vmaFindMemoryTypeIndexForBufferInfo(allocator, &bufferInfo, &allocCreateInfo, &memType);
		assertRes(vkRes);
	}
	return memType;
}

void createStaticVertexBuffer(VkDevice device, VmaAllocator allocator, size_t size, VkBuffer& buffer, VmaAllocation& allocation, VmaAllocationInfo* allocInfo = nullptr)
{
	VkBufferCreateInfo bufferInfo;
	const u32 memType = findMemTypeForStaticVertexBuffer(allocator, size, bufferInfo);

	const VmaAllocationCreateInfo allocCreateInfo = {
		.usage = VMA_MEMORY_USAGE_AUTO,
		.memoryTypeBits = u32(1) << memType
	};
	VmaAllocationInfo allocInfoVar;
	allocInfo = allocInfo ? allocInfo : &allocInfoVar;
	VkResult vkRes = vmaCreateBuffer(allocator, &bufferInfo, &allocCreateInfo, &buffer, &allocation, allocInfo);
	assertRes(vkRes);

	VkMemoryPropertyFlags memPropFlags;
	vmaGetAllocationMemoryProperties(allocator, allocation, &memPropFlags);
	if (memPropFlags & VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT) {
		vmaMapMemory(allocator, allocation, &allocInfo->pMappedData);
	}
}
```

So basically, I try to find the memory type for `VK_BUFFER_USAGE_VERTEX_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT` expecting.
- If the memType is HOST_VISIBLE: I repeat the find but without TRANSFER_DST, since the flag is actually not needed.
- If not HOST_VISIBLE: just use that memType. We will create a staging buffer to fill the vertex buffer.

Not sure if it would be a good idea to cache the memType; maybe with a static variable.

```cpp
	static VkBufferCreateInfo bufferInfo;
	static const u32 memType = findMemTypeForStaticVertexBuffer(allocator, size, bufferInfo);
```

Would save some CPU cycles (specially since `vmaFindMemoryTypeIndexForBufferInfo` might need to create temporary buffers in older Vulkan version), but I'm not sure if it's a safe assumption.

**Comment by tuket** [comment]
Nice, thanks!

That variable is used in the same function here:
```cpp
	if (memPropFlags & VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT) {
		vmaMapMemory(allocator, allocation, &allocInfo->pMappedData);
	}
```

**Comment by tuket** [comment]
Hello @adam-sawicki-a 


Sorry to revive this old thread.

I have just seen this flag:
[VMA_ALLOCATION_CREATE_HOST_ACCESS_ALLOW_TRANSFER_INSTEAD_BIT](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/group__group__alloc.html#ggad9889c10c798b040d59c92f257cae597a11337f96eacf34c1016c339eac165cad)


According to the documentation:

> Together with [VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/group__group__alloc.html#ggad9889c10c798b040d59c92f257cae597a9be224df3bfc1cfa06203aed689a30c5) or [VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/group__group__alloc.html#ggad9889c10c798b040d59c92f257cae597add61238d98e20917b9a06c617763f492), it says that despite request for host access, a not-HOST_VISIBLE memory type can be selected if it may improve performance.
> 
> By using this flag, you declare that you will check if the allocation ended up in a HOST_VISIBLE memory type (e.g. using [vmaGetAllocationMemoryProperties()](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/group__group__alloc.html#ga571e87dd38e552249b56b1b0b982fad1)) and if not, you will create some "staging" buffer and issue an explicit transfer to write/read your data. To prepare for this possibility, don't forget to add appropriate flags like VK_BUFFER_USAGE_TRANSFER_DST_BIT, VK_BUFFER_USAGE_TRANSFER_SRC_BIT to the parameters of created buffer or image.

This sounds familiar to the usage pattern I was asking about originally.

I don't recall this flag. Has it been recently added for this purpose?

Thank you.

**Comment by adam-sawicki-a** [comment]
Hello,

This flag was added to VMA at the same time flags `VMA_ALLOCATION_CREATE_HOST_ACCESS_*` were added. We just didn't discuss it here. I agree that it should be good for your use case.
