### ISSUE TITLE
Don't use deprecated VK_VERSION_* macros

### ISSUE THREAD

**Issue by emrsmsrli** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#319]
Hello, 

`VK_VERSION_*` macros are deprecated in latest SDK, please use `VK_API_VERSION_*` macros instead

Usage: 
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/7c35d6299bff1c92654dbd2571635ecb0160a0f5/include/vk_mem_alloc.h#L16000

**Comment by adam-sawicki-a** [comment]
Hello,

I am sorry but VMA must be backward-compatible to work even with old versions of Vulkan and Vulkan SDK, down to Vulkan 1.0, so I cannot unconditionally use latest additions like this.

**Comment by emrsmsrli** [comment]
It doesn't affect me at all, it was merely a suggestion for using up-to-date definitions :) 

You can use `#if VK_HEADER_VERSION >= 176` to check whether the newer versions of the macros should be used. https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/656#issuecomment-1082295727 

If you believe it's not worth the effort, you can just close this issue. 
Have a nice day!
