### ISSUE TITLE
Minor documentation mistakes

### ISSUE THREAD

**Issue by dgough** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#32]
https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/memory_mapping.html

The first code example says: `VmaBuffer` instead of `VkBuffer`. 

This sentence should start with "The" instead of "They":

> They way it's implemented is that the library always maps entire memory block, not just region of the allocation. For further details, see description of vmaMapMemory() function

**Comment by adam-sawicki-amd** [comment]
Thank you for finding these issues. I fixed them on development branch.
