### ISSUE TITLE
Defragmentaton: Incorrect Cast

### ISSUE THREAD

**Issue by CannibalVox** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#328]
One line in the defragmentation code appears to incorrectly cast the m_AlgorithmState (should be an array of StateExtensive pointers) into an array of size_t pointers: https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/include/vk_mem_alloc.h#L13733

**Comment by medranSolus** [comment]
Hello and thanks for noticing that! Fix has been just pushed in ff37e9278616b79ee36c9e102c9345ed155f9354.
