### ISSUE TITLE
Combining buffers into one large buffer - still necessary?

### ISSUE THREAD

**Issue by io7m** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#33]
Hello. Apologies if this isn't the right place to ask such questions, but I've not seen links to any kind of support area.

The [Nvidia documentation](https://developer.nvidia.com/vulkan-memory-management) suggests that it's preferable to to combine buffers into one large buffer and use offsets/ranges within that large buffer to get the best performance. Is this still necessary and/or possible with `vma`? I'm not sure from the documentation if `vma` handles this kind of suballocation for me or not.

**Comment by adam-sawicki-amd** [comment]
Yes, it is preferable to use larger buffers, but VMA doesn't support this out-of-the-box. What VMA does is it allocates larger `VkDeviceMemory` blocks and manages them to sub-allocate memory for whole `VkBuffer` and `VkImage` objects. Managing contents of such objects - like regions of a single Vulkan buffer - would be like a second-level sub-allocation and it's out of scope of this library. It is possible with VMA, you just need to do it yourself.
