### ISSUE TITLE
Question about buddy algorithm

### ISSUE THREAD

**Issue by imrodriguezro** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#330]
Hi all,
I saw that in the release `v3.0.1` the buddy algorithm was removed. I would like to ask you, 1) why was it removed?, and maybe as follow-up questions, 2) does the linear algorithm work reasonably well instead of the buddy one (I'd guess it depends on the application)?, and 3) how hard you think it would be to bring back myself (implement in a fork or something) the buddy algorithm?

Sorry in advance for the many questions and thank you.

**Comment by adam-sawicki-a** [comment]
Hi,

Buddy algorithm has been removed as part of the effort to simplify the library code, along with some other features that we considered not useful or not commonly used. Default allocation algorithm should work better than buddy algorithm in most if not all the cases, in terms of both speed and, even more, memory consumption and the amount of memory wasted.

Linear algorithm is a special use algorithm that will not reclaim memory in between allocations, only at the beginning and at the end of the memory range with your allocations, so I recommend to use it only if you are sure you allocate and deallocate in one of the patterns described in the documentation - as a stack, a queue, or freeing all at once.

I don't recommend to bring the buddy algorithm back, as it likely won't perform better than our current default algorithm (TLSF), but if you want to do it, it should be fairly easy. There is an abstract base class `VmaBlockMetadata` that you can inherit from to implement your own allocation algorithm.

**Comment by imrodriguezro** [comment]
Thanks for the prompt answer! I think I'll stick to the default algorithm then.
