### ISSUE TITLE
Race condition in repeated rapid buffer creation, access and destruction

### ISSUE THREAD

**Issue by amini-allight** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#331]
I'm afraid I can't provide source code for this because it occurred on a private project (and it was spread between half a dozen files), but I'm fairly sure there's a race condition in repeated rapid calls to `vmaCreateBuffer` and `vmaDestroyBuffer` on multiple threads, in contrast to what is stated in the documentation.

Steps to replicate:

1. Use Vulkan 1.0 with the `VK_LAYER_KHRONOS_validation` validation layer.
    - The bug appears to occur with or without validation layers, but without them the only indication will be occasional random segfaults when writing to a buffer.
    - The Vulkan version does not appear to matter, it has also been observed under 1.3.
2. Compile without debug symbols at the highest optimization level available.
    - This is required as the bug seems to require very high performance to trigger.
4. Create a single `VmaAllocator` with the default configuration (setting only `physicalDevice`, `device` and `instance`, using Vulkan 1.0 and no extensions). No flags were set, especially not `VMA_ALLOCATOR_CREATE_EXTERNALLY_SYNCHRONIZED_BIT`.
    - Again, Vulkan version appears not to matter but has been included for completeness.
6. Two threads extremely rapidly and repeatedly allocate, map, read/write and deallocate CPU-accessible (a mixture of `VMA_MEMORY_USAGE_CPU_TO_GPU` and `VMA_MEMORY_USAGE_GPU_TO_CPU`, it's unknown if this is important) buffers using the same allocator. They do not share these buffers in any way.
7. Despite not sharing the buffers in any way the following validation errors will occur:
    - `vkMapMemory(): object of type VkDeviceMemory is simultaneously used in thread A and thread B`
    - `vkUnmapMemory(): object of type VkDeviceMemory is simultaneously used in thread A and thread B`
    - `VkMapMemory: Attempting to map memory on an already-mapped VkDeviceMemory ADDRESS[]. The Vulkan spec states: memory must not be currently host mapped`
    - Sometimes the program may also segfault while writing to one of the buffers.
8. Adding external synchronization such as `lock_guard<mutex> lock(allocatorLock);` above all calls to `vmaCreateBuffer` and `vmaDestroyBuffer` causes the validation errors and segfaults to stop. Adding external synchronization to `vmaMapMemory` is not required and fails to fix the problem, despite what the error messages would suggest.

Platform info:

- Linux 6.2.11-arch1-1
- Mesa 23.0.2-1
- Using the RADV/`vulkan-radeon` Vulkan driver, version 23.0.2-1
- AMD RX 6900 XT

**Comment by turol** [comment]
Can you use ThreadSanitizer, Helgrind or DRD on your program and see if they spot the problem?

**Comment by amini-allight** [comment]
I'm going to be away for today and the weekend, I'll try them on Monday if that's okay.

**Comment by amini-allight** [comment]
I managed to replicate the bug in a standalone program, available [here](https://gitlab.com/amini-allight/vma-bug-demo).

However I also discovered that the bug is specific to VMA version `3.0.1` and in `3.1.0-development` (the current version at time of writing) it no longer exists.

I'm closing this issue as it appears to be fixed.

**Comment by adam-sawicki-a** [comment]
Thank you very much for investigating this issue! Please use latest version of the code from "master" branch, as official Releases were not updated for long time.
