### ISSUE TITLE
[Feature request] Link into *.so instead of *.a

### ISSUE THREAD

**Issue by werdahias** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#336]
Hi, 
building on linux produces two files: `vk_mem_alloc.h` and `VulkanMemoryAllocator.a `.
Could you enable support to dynamically link into a .so library ? .a library files are considered kinda deprecated. Currently there is not way to build a .so.

**Comment by adam-sawicki-a** [comment]
Hi,
I am sorry, but this library is developed mostly on and for Windows. I don't have a development environment to test it.

CMake script is an external contribution provided for convenience. The library is a single header file and it is recommended to just include it in your project codebase, so you can build it however you want.

**Comment by abouvier** [comment]
> Currently there is not way to build a .so.

You can always do:
`$ cmake (...) -DBUILD_SHARED_LIBS=ON`
