### ISSUE TITLE
[Feature request] add a .pc file for better integration

### ISSUE THREAD

**Issue by werdahias** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#337]
Could you maybe consider adding a .pc file so this library can be picked up by other buildsystems better and be adapted more ?

**Comment by adam-sawicki-a** [comment]
The library is a single header file and it is recommended to just include it in your project codebase, so you can build it however you want. CMake script is an external contribution provided for convenience. I am sorry but support for other build system is out of scope of this project.
