### ISSUE TITLE
"Could not implement aligned_alloc..." when linking VMA as a CMake target

### ISSUE THREAD

**Issue by starcatter** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#344]
`
[...]/vk_mem_alloc.h:2791: void* vma_aligned_alloc(size_t, size_t): Assertion 0 && "Could not implement aligned_alloc automatically. Please enable C++17 or later in your compiler or provide custom implementation of macro VMA_SYSTEM_ALIGNED_MALLOC (and VMA_SYSTEM_ALIGNED_FREE if needed) using the API of your system."' failed.
`

This seems to happen because the CMake project for VMA is setup for C++14, and when using GCC on Linux it needs C++17 for the `aligned_alloc()` function. The project I'm using VMA for is using C++20, but the setting is not propagated back to VMA's CMake project.

As an example, [VulkanMemoryAllocator-Hpp](https://github.com/YaaZ/VulkanMemoryAllocator-Hpp) links VMA this way.

My solution to this problem is overriding VMA's C++ standard after including it:

```

add_subdirectory(vma)

set_target_properties(VulkanMemoryAllocator PROPERTIES CXX_STANDARD 17)

```

I don't know how desirable it is for the VMA's CMake project to stay at C++14, if it's not a big deal then I suggest simply bumping the standard in the [src/CMakeLists.txt](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/src/CMakeLists.txt#L21) file.

**Comment by adam-sawicki-a** [comment]
Thank you for this suggestion. I agree it may be a good idea to default to C++17 in src/CMakeLists.txt to fix the issue with `aligned_alloc`. I committed this change.
