### ISSUE TITLE
Relocate vk_mem_alloc.h under includes/vulkan to give the header file better scope

### ISSUE THREAD

**Issue by rickyjames35** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#348]
This is just a suggestion that most libraries do. If you move `vk_mem_alloc.h` from `VulkanMemoryAllocator/include` to `VulkanMemoryAllocator/include/vulkan` then when you `#include` it, the header will be under the `vulkan` directory like the `Vulkan-Headers` library. Check out how they have it structured https://github.com/KhronosGroup/Vulkan-Headers/tree/ed857118e243fdc0f3a100f00ac9919e874cfe63/include/vulkan

Here's an example of how I `#include` it now:
```
#include <spdlog/spdlog.h>
#include <vulkan/vulkan.hpp>
#include <vk_mem_alloc.h>
```
and here's what I'm hoping for:
```
#include <spdlog/spdlog.h>
#include <vulkan/vulkan.hpp>
#include <vulkan/vk_mem_alloc.h>
```

btw, I'm using Conan to to import this library so I don't have as much control of reorganizing the directory structure.

**Comment by adam-sawicki-a** [comment]
Thank you for the suggestion. I am sorry but I don't think it is a good idea to change it.

Such a major change in the location of the main file in the repository would probably break compatibility with many users who pull this library.

I don't think it is necessary.

Besides that, putting "vk_mem_alloc.h" under "vulkan" subdirectory would feel like it is part of Vulkan itself. While VMA is now included in the SDK, it is a separate project, maintained by separate people, so I don't think it is "official enough" compared to Vulkan-Headers, which is hosted by Khronos.
