### ISSUE TITLE
Dead code in `FindMemoryPreferences`

### ISSUE THREAD

**Issue by marc0246** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#354]
This bit of code is dead:
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/2a28bc4b39b9b80dad909036442f629f570d7ae1/include/vk_mem_alloc.h#L3745-L3752
Because the same code appears just below it but unconditionally. This leads me to believe that there is a missing `else` that was supposed to exist somewhere along the line.

**Comment by adam-sawicki-a** [comment]
Thank you for noticing this. The logic was correct, as intended, but you are right that the code was suboptimal. I refactored it.
