### ISSUE TITLE
Windows + NOMINMAX

### ISSUE THREAD

**Issue by chaoticbob** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#36]
This isn't a real issue, but I got caught by not having NOMINMAX defined on Windows and got a bunch of compiler errors. Soft suggestion to maybe document this somewhere?

**Comment by adam-sawicki-amd** [comment]
This library just includes `<vulkan/vulkan.h>`, which in turn includes `<windows.h>` on Windows. I added appropriate paragraph in documentation. Thank you for this suggestion.
