### ISSUE TITLE
Can we use C++ classes instead of C Interface

### ISSUE THREAD

**Issue by GNFulLT** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#363]
Hello. Is there any way to use classes that defined in here : 
https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/annotated.html

With C Interface : 
``` 
// In Header file
VmaAllocator m_allocatorRef; 
VmaAllocation m_allocationBlock;

// In Cpp file 
VkDeviceMemory_T* GVulkanBuffer::get_device_memory() 
{       
        VmaAllocationInfo inf = {};
        vmaGetAllocationInfo(m_allocatorRef, m_allocationBlock, &inf);
        return inf.deviceMemory; 
} 
```

What I want is : 
``` 
VkDeviceMemory_T* GVulkanBuffer::get_device_memory()
 { 
         return m_allocationBlock->GetMemory(); 
}
 ```

I can't use #define VMA_IMPLEMENTATION because i already have a dedicated cpp file for the implementations and it causes link errors. Is there any correct way to do that ? I couldn't see anything about that in the documentation. Thank you.

**Comment by adam-sawicki-a** [comment]
Hello. I am sorry but VMA was purposefully designed to have C interface with structures and global functions, to look like Vulkan API. Classes like the ones you showed are internal implementation of the library and not intended for direct use.

It would be possible to develop an object-oriented C++ wrapper over VMA, like Vulkan-Hpp does for Vulkan. There was such project https://github.com/malte-v/VulkanMemoryAllocator-Hpp but it seems to be no longer maintained.

As the VMA documentation says, bindings to other programming languages are welcome as external repositories and I can link to them from README.md, but I will not include them in this repository.

**Comment by adam-sawicki-a** [comment]
This fork seems to be maintained: https://github.com/YaaZ/VulkanMemoryAllocator-Hpp

**Comment by tomilov** [comment]
Is it possible to change the development method in such a way that the main source become `vma.xml` registry (that defines docs and C-interface), like `vk.xml` in Vulkan? It can ease development of bindings. Either C++ or others.

**Comment by adam-sawicki-a** [comment]
I am sorry, but development and ongoing maintenance of such additional code is out of scope of this project.
