### ISSUE TITLE
VMA_ASSERT(index < m_ListsCount);

### ISSUE THREAD

**Issue by batcholi** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#367]
I am getting this assertion failure on Linux with a AMD GPU, and not with NVIDIA. 

The assertion failure is triggered while trying to allocate an image with 
VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE
and
VK_IMAGE_USAGE_STORAGE_BIT
 
The format is VK_FORMAT_R8G8B8A8_UINT.

The GPU is a 6900 XT. 
Validation layers are enabled with no validation error reported. 

Here is the relevant code:
```
VkExtent2D extent {........}; // this is arbitrary but always valid extent..
VmaAllocationCreateInfo _allocInfo {.usage = VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE};
VkImageCreateInfo _imageInfo {
            .sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
            .flags = 0,
            .imageType = VK_IMAGE_TYPE_2D,
            .format = VK_FORMAT_R8G8B8A8_UINT,
            .extent = VkExtent3D{.width = extent.width, .height = extent.height, .depth = 1},
            .mipLevels = 1,
            .arrayLayers = 1,
            .samples = VK_SAMPLE_COUNT_1_BIT,
            .tiling = VK_IMAGE_TILING_OPTIMAL,
            .usage = VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT,
            .sharingMode = VK_SHARING_MODE_EXCLUSIVE,
            .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED
        };
vmaCreateImage(_device->_allocator, &_imageInfo, &_allocInfo, &_handle, &_allocation, nullptr)
```

This issue happens both on Windows and Linux, with both the current `master` branch of VMA and the `v3.0.1` tag. 

This code has been working fine for years with nvidia gpus.

**Comment by adam-sawicki-a** [comment]
Do you mean the assert inside function `VmaBlockMetadata_TLSF::InsertFreeBlock`? If so, is this the only or first allocation you make using VMA? If not, I won't be able to reproduce this issue by just passing the same parameters of the allocated image. This assert relates to TLSF allocator, which means the order and parameters of allocations and deallocations made before it likely influence the result. Additional help in debugging this issue is needed.

**Comment by batcholi** [comment]
Yes that is the assertion I'm referring to. 
It is the first image allocation made from a specific dynamic lib, but not the first allocation overall. 
My engine allocates some buffers and images using VMA, and then loads some modules dynamically (dlopen/LoadLibrary), and the first vma image allocation from a certain module causes this assertion failure. 
I have tried with other flags/usage and the issue persists, so it does have something to do with it being the first (or just after something else, in this case a storage buffer). 
It is not a trivial engine/game so sharing source code won't be useful here.. but I can try to help as much as I can by answering questions and/or trying things on my end.

**Comment by adam-sawicki-a** [comment]
Could it be memory corruption in VMA internal CPU data structures? Or a synchronization issue? VMA should be thread-safe, but you can try to `#define VMA_DEBUG_GLOBAL_MUTEX 1` and see if it helps. You may also disable / comment out parts of your project.

**Comment by batcholi** [comment]
I am getting lock-order-inversion in `amdvlkpro64.so` upon calling `vkCreateInstance`
Would that mean it's a bug in AMD's drivers?

**Comment by turol** [comment]
Yes but that shouldn't cause corrupted memory, only potential deadlocks. Also on Linux you really should be using RADV.

**Comment by batcholi** [comment]
Does RADV support VK_KHR_ray_tracing? (my project requires it)

**Comment by batcholi** [comment]
But anyway the assertion failure also happens on Windows.

**Comment by batcholi** [comment]
Nothing to report with AddressSanitizer. 
However, Valgrind reports a `Condition jump or move depends on unitialized values`.... in `amdvlkpro64.so` of course....

**Comment by turol** [comment]
> Does RADV support VK_KHR_ray_tracing? (my project requires it)

I think so, in some version at least. Maybe not the latest stable yet.

> However, Valgrind reports a Condition jump or move depends on unitialized values.... in amdvlkpro64.so of course....

You can add `--track-origins=yes` to check if said value originates in your code.
One of the advantages of RADV is that you can check the driver source to see what's going on.

**Comment by batcholi** [comment]
The uninitialized value comes from libvulkan.so. 
But it doesn't seem to be related to the issue at all as it happens before creating the device and the vma allocator.
Also, I have tested with RADV, the lock-order-inversion error is gone when compiled with thread sanitizer, but I still get the original assertion failure. 
I have also disabled all external modules in my engine and that assertion still happens just with a different allocation (the next one in line). 
The last VMA allocation that worked before the assert is an image with 
`VMA_MEMORY_USAGE_AUTO`
 and 
`VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT`
with format `VK_FORMAT_R8G8B8A8_UNORM` and extent is the size of the screen (1080p). 

Then the allocation that fails is also an image, also with `VMA_MEMORY_USAGE_AUTO` but the usage also has the `VK_IMAGE_USAGE_SAMPLED_BIT` and the format is `VK_FORMAT_R32G32B32A32_SFLOAT`, and the extent is half that size. 

Also note that in this last test I did without any module, the vulkan initialization and every allocation runs in the same (main) thread. 

Let me know if there is any more information I can give you.

**Comment by batcholi** [comment]
If it helps you debug the issue: 
![Screenshot_20230911_133751](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/assets/3421077/c0929be0-8c65-4b17-acbf-923f96af3623)

**Comment by batcholi** [comment]
And here's the stack in my own code where I call the vma function to allocate that image. 

![Screenshot_20230911_135932](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/assets/3421077/a1acbc9e-4d93-4361-9ff5-33391c478c81)

**Comment by batcholi** [comment]
I confirm that the assertion failure happens on the first call to `VmaBlockMetadata_TLSF::InsertFreeBlock`. 
The other allocations before it don't seem to use TLSF at all. 
I have also checked again with an nvidia gpu and it uses some TLSF allocations properly and without ever failing. (RTX 2080 and RTX 3090, windows and linux).

**Comment by adam-sawicki-a** [comment]
Thank you for showing this debugging session. This is very helpful. Can you please use some Debug (unoptimized) version of the code and check with the debugger what happens with the calculations inside `VmaBlockMetadata_TLSF::InsertFreeBlock`? When `block->size` = 32400, `VMA_BITSCAN_MSB` should return 14 and `memClass` should be 14 - 7 = 7, while your screenshot shows 42. Is the function `VmaBitScanMSB` working incorrectly in your environment?

**Comment by batcholi** [comment]
![Screenshot_20230912_071706](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/assets/3421077/377c27f3-fb7e-4b4c-9cdd-ea9e4478c343)
![Screenshot_20230912_071750](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/assets/3421077/99e120f6-5e4c-44d3-ac8e-31a3d1b9221d)
![Screenshot_20230912_071853](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/assets/3421077/8176fa31-b6f1-4683-9da2-9ca38f972a3f)

**Comment by batcholi** [comment]
`static_cast<uint8_t>(__builtin_clzll(size))` with size 32400 results in the value 14. 
But in that code path it's `63 -` that 14, which results in 49... maybe this should directly return the value (14) instead?

**Comment by batcholi** [comment]
Yep, that fixed it, no more assertion failure, all allocations work with my suggested fix. 

![Screenshot_20230912_073919](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/assets/3421077/b9b71358-293b-4e3b-aa2a-4b026030520f)

**Comment by adam-sawicki-a** [comment]
What compiler version are you using? If this was the bug, it is hard to believe that no one stumbled upon it before. This function is used on any GCC or Clang compiler.

**Comment by batcholi** [comment]
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: /usr/bin/python3.11 (found version "3.11.5") found components: Interpreter 
-- Google Mock was not found - tests based on that will not build
-- spirv-tools not linked - illegal SPIRV may be generated for HLSL
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE

**Comment by batcholi** [comment]
Funny story: Now with that "fix", I get the assertion failure with an NVIDIA GPU, but not with AMD...

**Comment by adam-sawicki-a** [comment]
It seems you compile your program on a different machine with different compiler and other hardware/software environment. I recommend to compile it once and check the same executable on both machines to separate the issue we have here from the GPU you are using.

**Comment by batcholi** [comment]
I also get that same assertion failure on Windows (compiled using MINGW GCC from a Linux machine). 
The assertion failure happens both on Windows and Linux, only with AMD gpu. 
But with NVIDIA gpu it always works fine on both Windows and Linux. 
And now after removing that `63 -`, it's the other way around.

**Comment by adam-sawicki-a** [comment]
Can you please confirm that the same executable compiled once on one machine and copied to the other machine works correctly on one and fails on the other?

**Comment by batcholi** [comment]
I can confirm that. It was the case when I first posted the issue. 
I was compiling with GCC 13.2.1 on the Nvidia machine, then running the executable on the AMD machine directly. 
It was only yesterday that I decided to re-create that dev env on the AMD machine so I can do quicker iterations, and it gives the same results.

**Comment by batcholi** [comment]
Yes, launched in the same way (tried both ways on both machines)

**Comment by adam-sawicki-a** [comment]
Can you please test this simple program compiled and launched on both your machines? This should help us debug the issue without connection to VMA or the GPU you have installed.

https://godbolt.org/z/3TrTe6fs4

```cpp
#include <cstdio>
#include <cstdint>
int main()
{
    unsigned long long size = 32400;
    uint8_t y = static_cast<uint8_t>(__builtin_clzll(size));
    printf("%i\n",(int)y);
}
```

Compiler Explorer says it prints 49, as expected by the current version of VMA code.

**Comment by batcholi** [comment]
got `49` on the NVIDIA machine and `14` on the AMD machine, compiled individually with same environment as the main project (just an additional target in the cmake config). 
I have also copied the one compiled from the NVIDIA machine to the AMD machine, and it also gives `14` there. 
I confirm that the result depends on which machine it was executed on, not which machine compiled it. 

Additional info about the two machines:
Machine 1: Linux kernel 6.1.44-1-MANJARO with NVIDIA gpu, intel i9-9900k
Machine 2: Linux kernel 5.15.130-1-MANJARO with AMD gpu, intel i7-2600k

both 64-bit of course.

**Comment by adam-sawicki-a** [comment]
This is a very interesting finding. The difference is likely due to a different version of the software environment (OS, standard C library, kernel). It surely doesn't depend on the GPU installed, although we can still call these machines AMD and NVIDIA just to give them names.

Is there a known bug in the older Linux version related to this function? Maybe it is worth searching for it.

**Comment by batcholi** [comment]
But the interesting thing is I also get that assertion failure on Windows, on that AMD machine (multiboot) compiled from MINGW

**Comment by batcholi** [comment]
I have updated the AMD machine to Linux kernel 6.1, it still gives `14`. 

I have compiled and tested that same test for windows, on that AMD machine it gives `14`. 
On another Windows machine with an NVIDIA GPU, it gives `49`.... 
All machines have Intel CPU. 

Weirdly, it really looks like it has nothing to do with the OS, but the GPU....

**Comment by batcholi** [comment]
I just swapped the GPU for an old GTX 1060 and I still get `14`. 
Now let's compare two Windows machines: 

Machine 2: Intel i7-2600k, Windows 10 pro 22H2, 8 Gb RAM, GTX 1060. result = `14`

Machine 3: Intel i7-11700k, Windows 10 pro 22H2, 32 Gb RAM, RTX 3090. result = `49`

There is quite a big gap in the CPU architecture year, maybe that is it...

**Comment by batcholi** [comment]
I have swapped both the SSD and the AMD GPU from Machine 2 to Machine 3. 
So, Machine 3 now has the AMD RX 6900 XT and running the exact same Linux OS as the one that had the error. 
I am now getting `49` as expected. 
We can safely rule out the GPU and the OS. 

Which leaves us with CPU, Motherboard and RAM.  I'm guessing it has to do with the CPU, even though they're both Intel...

**Comment by adam-sawicki-a** [comment]
Thank you for all the testing you are doing, including hardware manipulation. Despite the bug is clearly unrelated to VMA, let's continue discussion about it here, as I am curious about the root cause.

Can you use the debugger to enter inside `__builtin_clzll` and see the x86 disassembly, to see whether there are some calculations inside that can go wrong, or is it just usage of a processor instruction that gives wrong result straight away?

**Comment by adam-sawicki-a** [comment]
Could this issue be related?
https://stackoverflow.com/questions/45107728/different-gcc-output-for-builtin-clzll-on-different-optimisation-levels-and-wr

**Comment by batcholi** [comment]
Figured it out after looking at the disassembly (thanks). 
I was using the `-mlzcnt` optimization flag, and turns out that was not supported on the 2600k hence was giving the wrong result. 

On the left it's with that flag on, and on the right it's off. 
With the flag off it properly gives the value 49. 

![disas](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/assets/3421077/3e6cd79d-928a-4290-87d4-c474285dd1b0)

![stack-overflow](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/assets/3421077/016a9eb2-6cd6-43e3-a700-47fb7dd5c4ef)

I will close this issue.
