### ISSUE TITLE
Clang 16 emits 800 warnings for vk_mem_alloc.h

### ISSUE THREAD

**Issue by toppa102** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#369]
Compiling a simple .cpp file with cmake and clang 16.0.6 emits about 800 warnings like this:
```
vma_test/VulkanMemoryAllocator/include/vk_mem_alloc.h:17334:22: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    VmaAllocationInfo* pAllocationInfo)
                     ^
vma_test/VulkanMemoryAllocator/include/vk_mem_alloc.h:17334:22: note: insert '_Nullable' if the pointer may be null
    VmaAllocationInfo* pAllocationInfo)
                     ^
                       _Nullable
vma_test/VulkanMemoryAllocator/include/vk_mem_alloc.h:17334:22: note: insert '_Nonnull' if the pointer should never be null
    VmaAllocationInfo* pAllocationInfo)
```

Main.cpp:
```
#define VMA_IMPLEMENTATION
#include <vk_mem_alloc.h>

int main()
{
}
```

CMakeLists.txt:
```
cmake_minimum_required (VERSION 3.8)

project ("vmatest")

find_package(Vulkan REQUIRED)
add_subdirectory("VulkanMemoryAllocator")

add_executable (vmatest
    "Main.cpp")
target_link_libraries(vmatest
    PRIVATE GPUOpen::VulkanMemoryAllocator
    PRIVATE Vulkan::Vulkan)
```

**Comment by adam-sawicki-a** [comment]
Documentation of this library clearly states in chapter "Features not supported":

> Code free of any compiler warnings. Maintaining the library to compile and work correctly on so many different platforms is hard enough. Being free of any warnings, on any version of any compiler, is simply not feasible. There are many preprocessor macros that make some variables unused, function parameters unreferenced, or conditional expressions constant in some configurations. The code of this library should not be bigger or more complicated just to silence these warnings. It is recommended to disable such warnings instead.

**Comment by juan-lunarg** [comment]
To easily address this do the following in your CMake code

```
add_subdirectory("VulkanMemoryAllocator" SYSTEM) # Requires CMake 3.25 or higher
```

Look into the `SYSTEM` keyword. It's what you want.
