### ISSUE TITLE
Comments format question/request

### ISSUE THREAD

**Issue by richard-lunarg** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#370]
On macOS using XCode, I'm getting a ton of bogus warnings because of the format of some of the comments. Technically this is really an Xcode bug, but it's probably easier to "fix" the comments. I can do this and do a PR, but I wanted to know if there would be any resistance to this minor change. The "problem" is the double ** after the initial slash for a comment as seen below.

Xcode is seeing the \ in front of brief (even though there's white space in between) and then flags the following lines with "Empty Paragraph passed to "\param" command as it thinks the comments have closed. The code actually COMPILES just fine!

Would it be okay to remove the double ** and just have /* at the beginning of the line?

I don't know if this is an "Xcode is being stupid" or a "Why does this work anywhere then?" issue. It also occurs to me this format might be getting parsed somewhere and it could be some sort of standard I'd be breaking if I did a PR.

/** \brief Binds buffer to allocation with additional parameters.

\param allocator
\param allocation
\param allocationLocalOffset Additional offset to be added while binding, relative to the beginning of the `allocation`. Normally it should be 0.
\param buffer
\param pNext A chain of structures to be attached to `VkBindBufferMemoryInfoKHR` structure used internally. Normally it should be null.

This function is similar to vmaBindBufferMemory(), but it provides additional parameters.

If `pNext` is not null, #VmaAllocator object must have been created with #VMA_ALLOCATOR_CREATE_KHR_BIND_MEMORY2_BIT flag
or with VmaAllocatorCreateInfo::vulkanApiVersion `>= VK_API_VERSION_1_1`. Otherwise the call fails.
*/

**Comment by adam-sawicki-a** [comment]
These are Doxygen comments used for generating documentation. If you don't know about this tool, please take a look at e.g.:
https://en.wikipedia.org/wiki/Doxygen

**Comment by richard-lunarg** [comment]
Okay, well now I feel silly ;-)

Adding a carriage return also does not cleanup the warnings. I'll go report the bug to Apple then.
