### ISSUE TITLE
HOST_VISIBLE always ending up with HOST_COHERENT enabled without explicitly defining it

### ISSUE THREAD

**Issue by DevLewa** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#374]
My apologies in advance in case this is/was answered in the docs (Or if it's something basic that i've overlooked).

I have implemented UBOs with VMA and benchmarking various implementations as to how memory is sent to the GPU.
(Specifically the impact of the HOST_COHERENT memory flag)

Now, i define UBOs like this:
```
VkBufferCreateInfo bufferInfo = {};
bufferInfo.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
bufferInfo.size = bufferCreateInfo.size; //bufferCreateInfo is an external struct passed into this function

VmaAllocationCreateInfo allocInfo = {};

bufferInfo.usage = VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT; //uniform buffer usage
allocInfo.requiredFlags = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT;

VmaAllocationInfo allocationInfo = {};
VkBuffer buffer;
VmaAllocation allocation;

VkResult res = vmaCreateBuffer(this->allocator, &bufferInfo, &allocInfo, &buffer, &allocation, &allocationInfo);	
```
(memory mapping happens later with vmaMapMemory)

The thing is that no matter if i set the "requiredFlags" as
`allocInfo.requiredFlags = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT;`
or
`allocInfo.requiredFlags = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT;`

the memory allocated via VMA always ends up with the "HOST_COHERENT" bit enabled. (Which i wasn't able to figure out/trace through the source code. From my understanding, only enabling the "VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT" should not enable HOST_COHERENT as this is a seperate flag altogether.)

I validated this by checking the buffer with:

```
VkMemoryPropertyFlags memPropFlags;
vmaGetAllocationMemoryProperties(allocator, allocation, &memPropFlags);
if ((memPropFlags & VK_MEMORY_PROPERTY_HOST_COHERENT_BIT) > 0)
{
	assert(false);
}
```
as well as the general behaviour of the Data passed in to the GPU. ( even without flushing the mapped memory of this buffer with vmaFlushAllocation, the data is visible for the GPU without any issues/flushing/cach invalidation being needed.)
Checked the Buffer in Renderdoc too and host coherent is also defined there.

Is this intended behaviour? (Or what is more likely an error or my part?) Are there some specific circumstances where HOST_COHERENT is automatically enabled? (like with the VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT?)

Testing this on an Nvidia Geforce GTX 1060 (6GB)

**Comment by turol** [comment]
Do you actually have memory types which are host visible but not coherent? On my RTX3060M on Linux there are no such memory types. Everything that is host visible is also coherent.

**Comment by adam-sawicki-a** [comment]
If you want to find the logic for selection of the memory type, check function `FindMemoryPreferences`: https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/include/vk_mem_alloc.h#L3653 `HOST_COHERENT` flag is not required there.

You are right that a memory type without this flag, if one is available, may offer better performance. However, it seems that currently all 3 PC GPU vendors (AMD, NVIDIA, Intel) expose all memory types that are `HOST_VISIBLE` as also having `HOST_COHERENT` flag set, at least on Windows. Please use `vulkaninfo` command-line tool to inspect memory types available on your platform and see if this is still true.

**Comment by DevLewa** [comment]
Oh, so the combination of HOST_VISIBLE and HOST_COHORENT has to be a specific memory type that is supported by the Driver? I thought that HOST_COHERENT is optional (as in if it's supported you can enable it to avoid manually flushing the memory but don't have to.) 

FindMemoryPreferences was one of the functions i was stepping through in my last debugging session but wasn't able to catch HOST_COHERENT anywhere. (Though i might've overlooked something there. Have to check again.) I assume the driver isn't automatically flagging the HOST_VISIBLE allocation as HOST_COHERENT after the fact?

Thats my memorytypes output from the vulkaninfo
```
memoryTypes: count = 11
        memoryTypes[0]:
                heapIndex     = 1
                propertyFlags = 0x0000:
                        None
                usable for:
                        IMAGE_TILING_OPTIMAL:
                                None
                        IMAGE_TILING_LINEAR:
                                color images
                                (non-sparse, non-transient)
        memoryTypes[1]:
                heapIndex     = 1
                propertyFlags = 0x0000:
                        None
                usable for:
                        IMAGE_TILING_OPTIMAL:
                                color images
                                (non-sparse)
                        IMAGE_TILING_LINEAR:
                                None
        memoryTypes[2]:
                heapIndex     = 1
                propertyFlags = 0x0000:
                        None
                usable for:
                        IMAGE_TILING_OPTIMAL:
                                FORMAT_D16_UNORM
                                (non-sparse, non-transient)
                        IMAGE_TILING_LINEAR:
                                None
        memoryTypes[3]:
                heapIndex     = 1
                propertyFlags = 0x0000:
                        None
                usable for:
                        IMAGE_TILING_OPTIMAL:
                                FORMAT_X8_D24_UNORM_PACK32
                                FORMAT_D24_UNORM_S8_UINT
                                (non-sparse, non-transient)
                        IMAGE_TILING_LINEAR:
                                None
        memoryTypes[4]:
                heapIndex     = 1
                propertyFlags = 0x0000:
                        None
                usable for:
                        IMAGE_TILING_OPTIMAL:
                                FORMAT_D32_SFLOAT
                                (non-sparse, non-transient)
                        IMAGE_TILING_LINEAR:
                                None
        memoryTypes[5]:
                heapIndex     = 1
                propertyFlags = 0x0000:
                        None
                usable for:
                        IMAGE_TILING_OPTIMAL:
                                FORMAT_D32_SFLOAT_S8_UINT
                                (non-sparse, non-transient)
                        IMAGE_TILING_LINEAR:
                                None
        memoryTypes[6]:
                heapIndex     = 1
                propertyFlags = 0x0000:
                        None
                usable for:
                        IMAGE_TILING_OPTIMAL:
                                FORMAT_S8_UINT
                                (non-sparse, non-transient)
                        IMAGE_TILING_LINEAR:
                                None
        memoryTypes[7]:
                heapIndex     = 0
                propertyFlags = 0x0001: count = 1
                        MEMORY_PROPERTY_DEVICE_LOCAL_BIT
                usable for:
                        IMAGE_TILING_OPTIMAL:
                                color images
                                FORMAT_D16_UNORM
                                FORMAT_X8_D24_UNORM_PACK32
                                FORMAT_D32_SFLOAT
                                FORMAT_S8_UINT
                                FORMAT_D24_UNORM_S8_UINT
                                FORMAT_D32_SFLOAT_S8_UINT
                        IMAGE_TILING_LINEAR:
                                color images
                                (non-sparse, non-transient)
        memoryTypes[8]:
                heapIndex     = 1
                propertyFlags = 0x0006: count = 2
                        MEMORY_PROPERTY_HOST_VISIBLE_BIT
                        MEMORY_PROPERTY_HOST_COHERENT_BIT
                usable for:
                        IMAGE_TILING_OPTIMAL:
                                None
                        IMAGE_TILING_LINEAR:
                                color images
                                (non-sparse, non-transient)
        memoryTypes[9]:
                heapIndex     = 1
                propertyFlags = 0x000e: count = 3
                        MEMORY_PROPERTY_HOST_VISIBLE_BIT
                        MEMORY_PROPERTY_HOST_COHERENT_BIT
                        MEMORY_PROPERTY_HOST_CACHED_BIT
                usable for:
                        IMAGE_TILING_OPTIMAL:
                                None
                        IMAGE_TILING_LINEAR:
                                color images
                                (non-sparse, non-transient)
        memoryTypes[10]:
                heapIndex     = 2
                propertyFlags = 0x0007: count = 3
                        MEMORY_PROPERTY_DEVICE_LOCAL_BIT
                        MEMORY_PROPERTY_HOST_VISIBLE_BIT
                        MEMORY_PROPERTY_HOST_COHERENT_BIT
                usable for:
                        IMAGE_TILING_OPTIMAL:
                                None
                        IMAGE_TILING_LINEAR:
                                color images
                                (non-sparse, non-transient)
```

**Comment by adam-sawicki-a** [comment]
> Oh, so the combination of HOST_VISIBLE and HOST_COHORENT has to be a specific memory type that is supported by the Driver? I thought that HOST_COHERENT is optional (as in if it's supported you can enable it to avoid manually flushing the memory but don't have to.)

This is correct. Please read more about device memory in Vulkan - chapter 11.2 of the specification:
https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap11.html#memory-device

Unlike in Direct3D 12, Vulkan has a flexibility in memory types that a particular Physical Device exposes. When allocating memory, you need to choose one of the available memory types. They have some flags that describe their capabilities and performance. These are not flags that you enable. You can also check this article:
https://asawicki.info/news_1740_vulkan_memory_types_on_pc_and_how_to_use_them

As you can see on the listing you quoted, on your GPU all memory types that are `HOST_VISIBLE` are also `HOST_COHERENT`.

Automatic choice of the best memory type for your Image or Buffer is one of the main features of VMA. I recommend you to use `VMA_MEMORY_USAGE_AUTO` (plus `VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT` or `VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT`, if you need to map it) and forget about all this complexity.

**Comment by DevLewa** [comment]
Alright, that clears it then. Should've done more research on this topic.
Will do as you suggested. Thank you.
