### ISSUE TITLE
GpuMemDumpVis.py using unsupported call on modern Python + PIL install

### ISSUE THREAD

**Issue by alecazam** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#375]
When running this, the code failed to execute textsize on my Windows Python 3.11 install.  I installed Pillow.   The following script change fixes it.

Traceback (most recent call last):
  File "c:\Foo\GpuMemDumpVis.py", line 280, in <module>
    textSize = draw.textsize(text, font=font)
               ^^^^^^^^^^^^^
AttributeError: 'ImageDraw' object has no attribute 'textsize'

GpuMemDumpVis.py, line 280
```
else:
            text = BytesToStr(byte)

            # this isn't compiling, and is reported here as returning incorrect data
            # https://levelup.gitconnected.com/how-to-properly-calculate-text-size-in-pil-images-17a2cc6f51fd
            # textSize = draw.textsize(text, font=font)
            # draw.text((x + IMG_MARGIN - textSize[0] - TEXT_MARGIN, y), text, fill=COLOR_TEXT_H2, font=font)
  
            textSize = font.getmask(text).getbbox()[2]
            draw.text((x + IMG_MARGIN - textSize - TEXT_MARGIN, y), text, fill=COLOR_TEXT_H2, font=font)
```

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this issue. I solved it by using function `textlength` instead of the deprecated `textsize` or `getmask` as you proposed. Please let me know if it works for you.
