### ISSUE TITLE
GpuDumpMemVis.py docs should indicate it doesn't handle aliasing

### ISSUE THREAD

**Issue by alecazam** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#381]
This code is only pulling in Size, and not reading offset for aliasing/overlap.   So this should be in the docs and flagged in the code.

**Comment by adam-sawicki-a** [comment]
Thank you for noticing this. You are right. I added a warning to the README file of the script. I will take a note to also print a warning when the script itself finds that aliasing occurs, or, even better, implement proper support for aliasing in the future.
