### ISSUE TITLE
vulkanApiVersion in doc refers to instance-api version and not device-api version

### ISSUE THREAD

**Issue by qbojj** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#384]
The documentation states about `vulkanApiVersion`:
`
It must be less or equal (preferably equal) to value as passed to vkCreateInstance as VkApplicationInfo::apiVersion
`
but most functions are using the `VkDevice` so device-api level should be used (min(instance-api level, physical device-api level)).

That value is check if some function/feature is enabled (e.g. dedicated allocation), but if the supplied `vulkanApiVersion >= VK_API_VERSION_1_1` but `VkPhysicalDeviceProperties::apiVersion < VK_API_VERSION_1_1` while not adding than VMA will think dedicated allocation is available even if it is not.

As such documentation should be changed or vulkanApiVersion should be clamped to `VkPhysicalDeviceProperties::apiVersion` of the physical device with which `VmaAllocator` is created.

**Comment by adam-sawicki-a** [comment]
Thank you for pointing to this problem in documentation. Hopefully I fixed it now.
