### ISSUE TITLE
Example for External Memory support

### ISSUE THREAD

**Issue by lobneroO** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#387]
The documentation for interop and external memory support is rather sparse and I can't get it to work, so I would like to ask if example code can be provided (in the documentation) on how to set it up.

What I have right now is roughly:

```
// create an example image creation struct to get the correct memory type for the pool
VkImageCreateInfo exampleImgInfo{};
exampleImgInfo.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
exampleImgInfo.imageType = VK_IMAGE_TYPE_2D;
exampleImgInfo.format = VK_FORMAT_R32G32B32A32_SFLOAT;
exampleImgInfo.tiling = VK_IMAGE_TILING_OPTIMAL;
exampleImgInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
exampleImgInfo.usage = VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT;
exampleImgInfo.samples = VK_SAMPLE_COUNT_1_BIT;
exampleImgInfo.flags = 0;
exampleImgInfo.mipLevels = 1;
exampleImgInfo.arrayLayers = 1;
exampleImgInfo.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
exampleImgInfo.queueFamilyIndexCount = 1;
exampleImgInfo.pQueueFamilyIndices = &QfIndices.GraphicsFamily.value();
exampleImgInfo.extent = VkExtent3D(1, 1, 1);

// allocation for the example image 
VmaAllocationCreateInfo allocCreateInfo = {};
allocCreateInfo.usage = VMA_MEMORY_USAGE_AUTO;

uint32_t memTypeIndex;
vmaFindMemoryTypeIndexForImageInfo(Device->MemoryAllocator, &exampleImgInfo, &allocCreateInfo, &memTypeIndex);
		
// create an extra pool which will handle memory and allocations for shared resources
PoolCreateInfo.memoryTypeIndex = memTypeIndex;

VkExportMemoryAllocateInfo ExportMemAllocInfo{};
ExportMemAllocInfo.sType = VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO;
#ifdef _WIN32
	ExportMemAllocInfo.handleTypes = VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT;
#else
	ExportMemAllocInfo.handleTypes = VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT;
#endif
PoolCreateInfo.pMemoryAllocateNext = &ExportMemAllocInfo;
		
VkResult result = vmaCreatePool(Device->MemoryAllocator, &PoolCreateInfo, &Device->ImageInteropPool);

// ...
VkImageCreateInfo createInfo{};
createInfo.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
createInfo.extent = VkExtent3D(1200, 800, 1);
createInfo.format = VK_FORMAT_R32G32B32A32_SFLOAT;
createInfo.imageType = VK_IMAGE_TYPE_2D;
createInfo.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
createInfo.mipLevels = 1;
createInfo.arrayLayers = 1;
createInfo.tiling = VK_IMAGE_TILING_OPTIMAL;
createInfo.usage = VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
createInfo.samples = VK_SAMPLE_COUNT_1_BIT;
createInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
createInfo.flags = 0;

VkExternalMemoryImageCreateInfo extMemInfo{ VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO };
#ifdef WIN32
	extMemInfo.handleTypes = VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT;
#else
	extMemInfo.handleTypes = VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT;
#endif
createInfo.pNext = &extMemInfo;

VmaAllocationCreateInfo allocInfo{};
allocInfo.usage = VMA_MEMORY_USAGE_AUTO;
allocInfo.pool = Device->ImageInteropPool;

VkResult result = vmaCreateImage(Device->MemoryAllocator, &createInfo, &allocInfo,
	&VulkanImage, &Allocation, nullptr);
```

but this crashes when running `vmaCreateImage`. The validation layers tell me 

>  vkCreateImage: pCreateInfo->pNext chain includes a structure with unknown VkStructureType (2081420000); Allowed structures are [VkBufferCollectionImageCreateInfoFUCHSIA, VkDedicatedAllocationImageCreateInfoNV, VkExportMetalObjectCreateInfoEXT, VkExternalFormatANDROID, VkExternalMemoryImageCreateInfo, VkExternalMemoryImageCreateInfoNV, VkImageCompressionControlEXT, VkImageDrmFormatModifierExplicitCreateInfoEXT, VkImageDrmFormatModifierListCreateInfoEXT, VkImageFormatListCreateInfo, VkImageStencilUsageCreateInfo, VkImageSwapchainCreateInfoKHR, VkImportMetalIOSurfaceInfoEXT, VkImportMetalTextureInfoEXT, VkOpaqueCaptureDescriptorDataCreateInfoEXT, VkOpticalFlowImageFormatInfoNV, VkVideoProfileListInfoKHR]. This error is based on the Valid Usage documentation for version 250 of the Vulkan header.  It is possible that you are using a struct from a private extension or an extension that was added to a later version of the Vulkan header, in which case the use of pCreateInfo->pNext is undefined and may not work correctly with validation enabled The Vulkan spec states: Each pNext member of any structure (including this one) in the pNext chain must be either NULL or a pointer to a valid instance of VkBufferCollectionImageCreateInfoFUCHSIA, VkDedicatedAllocationImageCreateInfoNV, VkExportMetalObjectCreateInfoEXT, VkExternalFormatANDROID, VkExternalMemoryImageCreateInfo, VkExternalMemoryImageCreateInfoNV, VkImageCompressionControlEXT, VkImageDrmFormatModifierExplicitCreateInfoEXT, VkImageDrmFormatModifierListCreateInfoEXT, VkImageFormatListCreateInfo, VkImageStencilUsageCreateInfo, VkImageSwapchainCreateInfoKHR, VkImportMetalIOSurfaceInfoEXT, VkImportMetalTextureInfoEXT, VkOpaqueCaptureDescriptorDataCreateInfoEXT, VkOpticalFlowImageFormatInfoNV, or VkVideoProfileListInfoKHR (https://vulkan.lunarg.com/doc/view/1.3.250.1/windows/1.3-extensions/vkspec.html#VUID-VkImageCreateInfo-pNext-pNext)

but that explcitily lists `VkExternalMemoryImageCreateInfo` which is what I have been using, so I don't know why this fails.

**Comment by adam-sawicki-a** [comment]
VMA provides help in memory allocation, but for learning correct usage, I recommend to start from bare Vulkan and its documentation. You can try to do the interop using Vulkan functions only: `vkAllocateMemory`, `vkCreateImage`, etc. to exclude the possibility of experiencing bugs in VMA. When it works, you can switch to using VMA for these interop images for convenience.

One possible issue I can see in your code is that you attach structure `VkExternalMemoryImageCreateInfo` to `VkImageCreateInfo` when creating the actual image, but not when doing "example image info" and calling `vmaFindMemoryTypeIndexForImageInfo`. You should use it there as well, because structures in `pNext` chain like this one can influence what memory types are supported.

Are you sure that `VK_IMAGE_TILING_OPTIMAL` is supported for interop? Maybe try `VK_IMAGE_TILING_LINEAR` as well.

**Comment by lobneroO** [comment]
Thank you for the hints, I have tried both the `pNext` addition in the example image and the `TILING_LINEAR`, but the crash is still the same. Regardless, I will take a look the bare Vulkan interop usage again.

**Comment by lobneroO** [comment]
I actually found the reason for the crash, so for completeness sake: the above code will work (or at least run without crashes), but I had simplified the debug code a bit and some of my creation structs were out of scope by the time of creation. This would lead to the vulkan error and VMA crash.

**Comment by adam-sawicki-a** [comment]
Thanks for the information. You likely met the case that the documentation of `VmaPoolCreateInfo::pMemoryAllocateNext` warns about:
https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/struct_vma_pool_create_info.html#abf71afe846790f72d1860e0afb12b883
> Structures pointed by this member must remain alive and unchanged for the whole lifetime of the custom pool.
