### ISSUE TITLE
VK9 Now Uses VulkanMemoryAllocator

### ISSUE THREAD

**Issue by disks86** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#39]
As of today VK9 uses the VulkanMemoryAllocator. I wasn't sure if you preferred issues or PRs for new items on the list of projects that use the allocator.

https://github.com/disks86/VK9

**Comment by adam-sawicki-amd** [comment]
Formally it is not required to notify us about usage of this library, but I appreciate such notification. I added VK9 to the list of usages in README.md. Thanks a lot!
