### ISSUE TITLE
Support using parts of VMA without vulkan [virtual allocation & defragmentation]

### ISSUE THREAD

**Issue by Ansraer** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#395]
I am currently using VMA in a vulkan project for most of my memory management. Recently an alternative rendering backend was merged (DX12), for which we had to roll our own memory management.

The real problem is how we manage the content of our SSBO. We have a handful of massive SSBOs and use VMA's virtual allocator to manage their content, something that happens outside the backend dependent code.
Given how both the virtual allocator and the defragmentation should be possible without relying on anything from vulkan it would be nice if VMA either had the vulkan specific code behind a define or offered the non platform dependent features (such as virtual allocaton & defragmentation) in a separate header file.

**Comment by adam-sawicki-a** [comment]
I am sorry, but this is out of scope of this project.

I agree that it would be good to have the core allocation algorithm (as exposed by "virtual allocator" feature, plus maybe defragmentation support) extracted to a separate library, used by VMA, D3D12MA, and available for use without any specific graphics API. However, we don't have a plan to provide it. VMA is a single-header library. Changing it would require major refactoring.

Extracting the allocation algorithm manually should be relatively easy. Please look at `VmaBlockMetadata_TLSF` class.

You may also look for some other libraries that implement TLSF or other allocation algorithm alone.
