### ISSUE TITLE
VMA crashing at startup on Android 14 devices

### ISSUE THREAD

**Issue by alecazam** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#397]
Our android 14 devices (now with Vulkan 1.3 support), are crashing in the following asserts.  I don't have the supported extension list yet, since I don't have one of these devices. I think I'll clamp the version we send of to 1.1 maximum for now.

1. This should fallback to vkGetDeviceBufferMemoryRequirementsKHR if maintenance4 is set.  That may be required on these Android devices even though they're "1.3".
2. This shouldn't be an assert if these are null, since VK_KHR_maintenance4 may not be set and for some reason these are VMA_NULL.

We are using volk.h, and it seems to support loading these extensions.  Also not seeing this problem on Windows Vulkan 1.2 and 1.3, but we're loading maintenance4 on drivers 1.3+.   Obviously 1.2 wouldn't enter this path.  

```
if(m_VulkanApiVersion >= VK_MAKE_VERSION(1, 3, 0))
{
	VMA_ASSERT(m_VulkanFunctions.vkGetDeviceBufferMemoryRequirements != VMA_NULL);
         VMA_ASSERT(m_VulkanFunctions.vkGetDeviceImageMemoryRequirements != VMA_NULL);
}
```

Here is our workaround to just skip this code for now:

```
           if ( allocatorInfo.vulkanApiVersion >= VK_API_VERSION_1_2 )
	   {
		   allocatorInfo.vulkanApiVersion = VK_API_VERSION_1_1;
	   }
```

**Comment by adam-sawicki-a** [comment]
Functions `vkGetDeviceBufferMemoryRequirements`, `vkGetDeviceImageMemoryRequirements` have been added in extension VK_KHR_maintenance4, promoted to Vulkan 1.3, so if either of these are available and enabled, these functions are expected to exist. If their pointers cannot be fetched, this is not a bug in VMA, but in the Vulkan implementation on a specific platform. Please report this bug in a repository/website suitable for it.

VMA doesn't offer specifying that VK_KHR_maintenance4 extension has been enabled and using these functions in such case, only when Vulkan 1.3 is enabled. It was a decision made to simplify the code, as using `vkGetDeviceBufferMemoryRequirements`, `vkGetDeviceImageMemoryRequirements` versus old `vkGetBufferMemoryRequirements`, `vkGetImageMemoryRequirements` is a minor difference - just a matter of not having to create a dummy buffer/texture in functions like `vmaFindMemoryTypeIndexForBufferInfo`. Please let me know if you have a different opinion about the importance of supporting these functions with VK_KHR_maintenance4.

**Comment by alecazam** [comment]
We have a lot of PC users with only Vulkan 1.2.  So seems odd to exclude calling this when there is a provided extension for 1.1 and 1.2.  I don't know how critical this call is to how VMA functions though.  I just thought an AMD part shouldn't crash.  I've forwarded this message to a friend who works with Samsung, so they're aware of this missing call.  But the asserts seem a bit extreme and will cause other Android devs to crash on this rare part.

**Comment by adam-sawicki-a** [comment]
So, you mean there is a group of devices that only support Vulkan 1.2, but support VK_KHR_maintenance4 extension? If so, I can add support for VK_KHR_maintenance4 to VMA.

As the use of these functions depends on their pointers not being null, would removing these asserts solve the problem with AMD driver?

**Comment by alecazam** [comment]
All my drivers are 1.1 on Android and 1.3 on Win.  But let me check our crash reports for maintenance4.  The Vulkan docs really don’t indicate which version you can start using extensions.  I also can’t find these parts on gpuinfo.   VMA checks the other extensions for null and just skip so this should too.  Expecting anything in Android even if in the spec is problematic.

**Comment by adam-sawicki-a** [comment]
I added support for VK_KHR_maintenance4 extension - added flag `VMA_ALLOCATOR_CREATE_KHR_MAINTENANCE4_BIT`. Please let me know if it works for you.

**Comment by alecazam** [comment]
Thanks Adam!  Also looking through our crash db, this was occurring on S22, S22 Ultra, S23 with Android 14.  And on a few Pixel 6, 6a, 7, and 8 devices.   So it's AMD (S22 Ultra), Qcom (S22/S23), Mali (Pixel 6/6a).   So good to fix it.

**Comment by alecazam** [comment]
Closing for now.  It will take some time before I can test, and we have our workaround to clamp to 1.1 on Android.
