### ISSUE TITLE
3.0.2 release for gcc-13 fix?

### ISSUE THREAD

**Issue by paultag** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#398]
Thank you so much for maintaining this library!

Would you be- able to cut a release that includes https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/commit/29d492b60c84ca784ea0943efc7d2e6e0f3bdaac ?

This library is failing to build off 3.0.1 locally due to the change in stdlib-included headers under gcc-13, and a new release would help me out greatly.

Thanks for all you do!

**Comment by adam-sawicki-a** [comment]
A new release is planned. A request for it is already covered by #318. For now, I recommend to use latest code from the "master" branch, which is always kept in a good state.
