### ISSUE TITLE
Functions use MS specific functions

### ISSUE THREAD

**Issue by Evangel63** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#4]
Functions ```VmaUint32ToStr``` and ```VmaUint64ToStr``` use the Microsoft specific functions ```_ultoa_s``` and ```_ui64toa_s```. These can be replaced with calls to ```snprintf``` to keep the reliance only on the standard libraries.

**Comment by adam-sawicki-amd** [comment]
Fixed. Thanks!
