### ISSUE TITLE
size_t value passed to fprintf with formatted %llu

### ISSUE THREAD

**Issue by baldurk** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#40]
In `VmaRecorder::RecordCreatePool` there's a fprintf call which uses `%llu` to print `createInfo.minBlockCount` and `createInfo.maxBlockCount` which are both of type `size_t`. This will fail on 32-bit platforms.

I think some printf implementations support `%zu` but I don't think that's standard, so it might be better to just cast those values up to `uint64_t`.

**Comment by adam-sawicki-amd** [comment]
Thank you for finding this issue. You are right. Official documentation of recording file format also mentions these fields are `uint64`. I fixed it on "development" branch.
