### ISSUE TITLE
Buggy mapping hysteresis optimization

### ISSUE THREAD

**Issue by matusfedorko** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#407]
Hi,

with `VMA_MAPPING_HYSTERESIS_ENABLED` on, repeatedly mapping a GPU allocated memory via `vmaMapMemory` suddenly succeeds after 8 attempts due to mapping hysteresis. This is because `VmaMappingHysteresis::PostMap` sets `m_ExtraMapping` to 1 after `COUNTER_MIN_EXTRA_MAPPING` retries without checking if the memory can actually be mapped at all. I don't know if this is a known issue, but I did not find any report here on github.

**Comment by matusfedorko** [comment]
A pseudo code to better illustrate what I mean:

```
VkBuffer buffer;
vkCreateBuffer(..., &buffer);

VmaAllocationCreateInfo allocCreateInfo = { };
allocCreateInfo.usage = VMA_MEMORY_USAGE_GPU_ONLY;  // allocate buffer in GPU memory inaccessible to CPU

VmaAllocation allocation;
vmaAllocateMemoryForBuffer(allocator, buffer, &allocCreateInfo, &allocation, nullptr);

void* ptr;
for (int i = 0; i < 8; ++i)
{
	const VkResult res = vmaMapMemory(allocator, allocation, &ptr);
	assert(res == VK_ERROR_MEMORY_MAP_FAILED);
}

const VkResult res = vmaMapMemory(allocator, allocation, &ptr); // after COUNTER_MIN_EXTRA_MAPPING attempts this returns VK_SUCCESS
assert(res == VK_SUCCESS);
```

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this bug.

I think that users should not attempt to map allocations in non-`HOST_VISIBLE` memory types. It could be considered an undefined behavior.

That said, I agree it would be good to handle this case, as it was not handled correctly by the mapping hysteresis logic. I hopefully fixed it now. Please let me know if it looks good to you.

By the way, `VMA_MEMORY_USAGE_GPU_ONLY` is deprecated. I recommend using the new `VMA_MEMORY_USAGE_AUTO`.
