### ISSUE TITLE
Fails to cross compile with mingw64 on Linux because of incorrect capitalization

### ISSUE THREAD

**Issue by turol** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#41]
Source includes `Windows.h` with upper case first letter. On Linux mingw64 calls the header `windows.h` with lower case first letter. This fails to compile because Linux is case sensitive. Please use lower case letters for windows header names.

**Comment by adam-sawicki-amd** [comment]
Original Windows header from `c:\Program Files (x86)\Windows Kits\8.1\Include\um\Windows.h` has upper case first letter, so I think mingw64 has it wrong. But OK, Windows doesn't care about case sensitivity, so I fixed it on "development" branch.
