### ISSUE TITLE
no support for `VkBufferUsageFlags2CreateInfoKHR`

### ISSUE THREAD

**Issue by qbojj** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#411]
Vma in many places (e.g `vmaCreateBuffer`) assumes that usage information is in `p*CreateInfo->usage` but with `VK_KHR_maintenance5` it can be in `VkBufferUsageFlags2CreateInfoKHR` in the `pNext` chain

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this. I agree this is a deficiency that should be fixed ASAP. I added support for this. Please let me know if it looks good to you.

**Comment by qbojj** [comment]
LGTM
