### ISSUE TITLE
Specify in documentation that individual pools can be individually used w/o external synchronization

### ISSUE THREAD

**Issue by tomilov** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#412]
In single-threaded context.

Can they? It seems natural. If library internally arranged "good" this property should be externally observable without any additional efforts from development.

**Comment by adam-sawicki-a** [comment]
Do you mean with or without `VMA_ALLOCATOR_CREATE_EXTERNALLY_SYNCHRONIZED_BIT`?

By default, functions of this library are thread-safe, synchronized internally, which is described in the documentation.

I am sorry, but I cannot guarantee thread safety when `VMA_ALLOCATOR_CREATE_EXTERNALLY_SYNCHRONIZED_BIT` is used, even for separate custom pools. There are places in the code other than specific to the pool that need synchronization, like `VmaAllocator_T::GetHeapBudgets`.
