### ISSUE TITLE
Compatibility issue with Vulkan 1.2.198 on OSX

### ISSUE THREAD

**Issue by HermanWolf** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#413]
Hi, 

I just want to report a compatibility issue I've encountered with an old system (macOS Catalina, Vulkan 1.2.198, VulkanSDK 1.2.198.1), and the latest version of VMA (Version 3.1.0-development). 

I had four errors of this kind: 
`Use of undeclared identifier 'VK_STRUCTURE_TYPE_DEVICE_IMAGE_MEMORY_REQUIREMENTS'; did you mean 'VK_STRUCTURE_TYPE_DEVICE_IMAGE_MEMORY_REQUIREMENTS_KHR'?`

I "solved" them (at least it compiles successfully on my system) by adding manually the KHR suffix where it was missing, in the vk_mem_alloc.h file. 

Thank you for your work on VMA.

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this issue. You are right - it should be `_KHR` for better compatibility with old versions of Vulkan SDK. I found only 1 occurrence of `VK_STRUCTURE_TYPE_DEVICE_IMAGE_MEMORY_REQUIREMENTS`. Please let me know if the fix works for you.

**Comment by HermanWolf** [comment]
To make vk_mem_alloc.h compile on my system, I have added the "KHR" suffix on four places: 
- VkDeviceBufferMemoryRequirements (line 15161)
- VK_STRUCTURE_TYPE_DEVICE_BUFFER_MEMORY_REQUIREMENTS (line 15161)
- VkDeviceImageMemoryRequirements (line 15213)
- VK_STRUCTURE_TYPE_DEVICE_IMAGE_MEMORY_REQUIREMENTS (line 15213). 

I haven't been able to successfully transition my simple Vulkan project to VMA yet (probably due to insufficient competence on my side) so I can't confirm that it works, besides just compiling.

**Comment by adam-sawicki-a** [comment]
Thanks for the clarification. I fixed all these places adding `_KHR`.
