### ISSUE TITLE
C++20 module

### ISSUE THREAD

**Issue by demihamster** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#427]
Hi,
since vulkan sdk added a module file "vulkan.cppm", perhaps you'd consider adding one for vma.

Alex

**Comment by adam-sawicki-a** [comment]
Thank you for the suggestion. However, this library is written in a C++ single-header style compatible with C++14 with interface in C similar to Vulkan. Bindings to any other programming languages, including C++20 modules, are out of scope of this project. If you create an external repository with such binding, I can link to it from README.
