### ISSUE TITLE
intellisense always analyzing implementation, reports false errors for undefined SRWLOCK

### ISSUE THREAD

**Issue by zongiin** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#443]
as reported in https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/26, the header has a define which makes intellisense always analyze the implementation part of `vk_mem_alloc.h`.

This makes intellisense report false errors in win32 applications where the cpp file does not include `<windows.h>`(replaced by a platform abstraction like SDL), because the implementation part of `VmaRWMutex` will always try to use `SRWLOCK`, a WinAPI class.

I think that either using `VK_USE_PLATFORM_WIN32_KHR` or another user defined macro to check whether to allow SRWLOCK use would be good. Currently, as the below comment in `vk_mem_alloc.h` states, the implementation assumes `<windows.h>` is included.

```
This library includes header `<vulkan/vulkan.h>`, which in turn
includes `<windows.h>` on Windows. If you need some specific macros defined
before including these headers (like `WIN32_LEAN_AND_MEAN` or
`WINVER` for Windows, `VK_USE_PLATFORM_WIN32_KHR` for Vulkan), you must define
them before every `#include` of this library.
It may be a good idea to create a dedicate header file for this purpose, e.g. "VmaUsage.h",
that will be included in other source files instead of VMA header directly.
```

**Comment by adam-sawicki-a** [comment]
Would checking `#ifdef SRWLOCK_INIT` work? This macro seems to be defined together with `SRWLOCK`.

**Comment by zongiin** [comment]
> Would checking `#ifdef SRWLOCK_INIT` to decide whether to use `SRWLOCK` version work for you? This macro seems to be defined together with `SRWLOCK`.

Yes, that would be desirable.
