### ISSUE TITLE
device <-> device via Vulkan Memory Allocator

### ISSUE THREAD

**Issue by CaptGreg** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#45]
Does the vulkan memory allocator support device to device memory transfers.  We would like to to go GPU to FPGA without going through host memory.

**Comment by adam-sawicki-amd** [comment]
How could the support look like?

For every separate `VkDevice` you use, you need to create a separate `VmaAllocator` object. This library doesn't launch any data transfers by itself. You have to do it on your side. VMA just lets you allocate chunks of memory. It helps with choosing right memory type out of available ones, and sub-allocating pieces of larger memory blocks. That's all. Everything else is user's responsibility or could constitute a higher-level library on top of VMA.

That said, please feel free to propose any enhancements that would be useful in your case.

By the way, if you develop using Vulkan on some exotic platform (exotic from my perspective, as a Windows PC developer :)) then can you please send me output of "vulkaninfo" from it, or some other document that would describe parameters of Vulkan environment in that platform? I'm curious what memory heaps and types are available there.

**Comment by adam-sawicki-amd** [comment]
I assume the question is answered now and I close the ticket. Please feel free to comment it if you have any additional questions or suggestions.

**Comment by expipiplus1** [comment]
Apologies for the off topic bump!

@CaptGreg just out of curiosity, what cool things are you doing requiring interop between GPU and FPGA?

**Comment by CaptGreg** [comment]
Fin-tech calculations.  We are seeing a 100x speed bump using a FPGA and a
GPU compared to a GPU only solution.  Our customers think that is cool.
Now if only the PCIe bus was faster, we could go faster.
