### ISSUE TITLE
vmaCreateImage(...) results in read access violation

### ISSUE THREAD

**Issue by Tom-Olsen** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#450]
I am trying to create a VkImage via `vmaCreateImage(...)` and run into a read access violation error in the line `bool HasExplicitBlockSize() const { return m_ExplicitBlockSize; }`.
For my VmaAllocator I use the following wrapper class:

VulkanMemoryAllocator.h:
```
#pragma once
#define VMA_STATIC_VULKAN_FUNCTIONS 0
#define VMA_DYNAMIC_VULKAN_FUNCTIONS 1
#include "vk_mem_alloc.h"

class VulkanMemoryAllocator
{
public:
	VmaAllocator allocator;
	VulkanMemoryAllocator(VkInstance* instance, VkDevice* logicalDevice, VkPhysicalDevice* physicalDevice);
	~VulkanMemoryAllocator();
};
```

VulkanMemoryAllocator.cpp:
```
#define VMA_IMPLEMENTATION
#include "vulkanMemoryAllocator.h"

VulkanMemoryAllocator::VulkanMemoryAllocator(VkInstance* instance, VkDevice* device, VkPhysicalDevice* physicalDevice)
{
	// References to vulkan functions:
	VmaVulkanFunctions vulkanFunctions = {};
	vulkanFunctions.vkGetInstanceProcAddr = &vkGetInstanceProcAddr;
	vulkanFunctions.vkGetDeviceProcAddr = &vkGetDeviceProcAddr;

	// Define allocator properties:
	VmaAllocatorCreateInfo allocatorInfo = {};
	allocatorInfo.instance = *instance;
	allocatorInfo.device = *device;
	allocatorInfo.physicalDevice = *physicalDevice;
	allocatorInfo.pVulkanFunctions = &vulkanFunctions;	// pointers to Vulkan functions
	allocatorInfo.vulkanApiVersion = VK_API_VERSION_1_3;	// same as `VulkanInstance::apiVersion`

	// Create allocator:
	VKA(vmaCreateAllocator(&allocatorInfo, &allocator));
}
VulkanMemoryAllocator::~VulkanMemoryAllocator()
{
	vmaDestroyAllocator(allocator);
}
```

Creating a buffer like this works totally fine:
```
	VkBufferCreateInfo bufferInfo = { VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO };
	bufferInfo.size = 512;
	bufferInfo.usage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;

	VmaAllocationCreateInfo allocInfo = {};
	allocInfo.usage = VMA_MEMORY_USAGE_AUTO_PREFER_HOST;
	allocInfo.flags = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT;

	VkBuffer buffer;
	VmaAllocation allocation;
	VmaAllocationInfo info;
	std::court << "creating buffer." std::endl;
	vmaCreateBuffer(allocator, &bufferInfo, &allocInfo, &buffer, &allocation, &info);
	std::court << "created buffer." std::endl;
```

Doing the analog process with an image results in the mentioned read access violation:
```
	VkImageCreateInfo imageInfo = { VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO };
	imageInfo.imageType = VK_IMAGE_TYPE_2D;
	imageInfo.extent.width = 1920;
	imageInfo.extent.height = 1080;
	imageInfo.extent.depth = 1;
	imageInfo.mipLevels = 1;
	imageInfo.arrayLayers = 1;
	imageInfo.format = VK_FORMAT_R8G8B8A8_SRGB;
	imageInfo.tiling = VK_IMAGE_TILING_OPTIMAL;
	imageInfo.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
	imageInfo.usage = VK_IMAGE_USAGE_SAMPLED_BIT;
	imageInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
	imageInfo.samples = VK_SAMPLE_COUNT_1_BIT;

	VmaAllocationCreateInfo allocationInfo;
	allocationInfo.usage = VMA_MEMORY_USAGE_AUTO_PREFER_HOST;
	allocationInfo.flags = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT;

	VkImage image;
	VmaAllocation allocation;
	VmaAllocationInfo info;
	std::court << "creating image." std::endl; 	// does print
	vmaCreateImage(allocator, &imageInfo, &allocationInfo, &image, &allocation, &info); 	// craches
	std::court << "created image." std::endl; 	// doesn't print
```

This might be a user error. I could not find a single example on how to use `vmaCreateImage(...)` online. I only found how to use `vmaCreateBuffer(...)` and mentions that the image variant works analogous.

**Comment by adam-sawicki-a** [comment]
To debug this issue, I recommend:

1. Make sure macro `VMA_ASSERT` in VMA is defined to something that will trigger a fault when false, not ignored.
2. Enable Vulkan Validation Layers in your projects and look for reported errors.

Please note that on many (if not most or all) GPUs creating an image, even more so with `VK_IMAGE_LAYOUT_UNDEFINED` is not possible when you want to map it, as you declare by using `VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT`. It wouldn't make sense anyway, because as the layout of the pixels of your image is "unknown", how are you going to write them to the mapped pointer? The solution is to create a staging buffer that is host-accessible, an image in the device memory, and perform `vkCmdCopyBufferToImage` from the buffer to the image.

**Comment by Tom-Olsen** [comment]
I have validation layers activated, but they do not log any warnings or errors regarding the `vmaCreateImage(...)` call.
Activating `VMA_ASSERT` manually did not change anything.
You are of course right, that the combination of `VK_IMAGE_LAYOUT_UNDEFINED` and `VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT` does not make much sense. I only used that configuration for testing. However, I tried a multitude of other combinations of flags, memory usage, and initial layout. All of them create the same read access violation. For example using:

```
	VkImageCreateInfo imageInfo = { VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO };
	imageInfo.imageType = VK_IMAGE_TYPE_2D;
	imageInfo.extent.width = 1920;
	imageInfo.extent.height = 1080;
	imageInfo.extent.depth = 1;
	imageInfo.mipLevels = 1;
	imageInfo.arrayLayers = 1;
	imageInfo.format = VK_FORMAT_R8G8B8A8_SRGB;
	imageInfo.tiling = VK_IMAGE_TILING_OPTIMAL;
	imageInfo.initialLayout = VK_IMAGE_LAYOUT_PREINITIALIZED;
	imageInfo.usage = VK_IMAGE_USAGE_SAMPLED_BIT;
	imageInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
	imageInfo.samples = VK_SAMPLE_COUNT_1_BIT;
	imageInfo.flags = 0;
		
	VmaAllocationCreateInfo allocationInfo;
	allocationInfo.usage = VMA_MEMORY_USAGE_AUTO;
	allocationInfo.flags = 0;
```

creates the same error.
I tried many different combinations, all of them fail. I think the error might be in the way I configured my VmaAllocator or that in the build process something is going wrong?

**Comment by turol** [comment]
You might have screwed up the lifetime of your `VulkanMemoryAllocator` and it's been deleted already. Try ASAN or Valgrind.

**Comment by adam-sawicki-a** [comment]
Please initialize variable `allocationInfo` with zeros so that the members that you don't assign have zeros and not random data, by doing:
```cpp
VmaAllocationCreateInfo allocationInfo = {};
```
Or calling `memset` or (on Windows) `ZeroMemory`.

**Comment by Tom-Olsen** [comment]
Thanks adam! This was the mistake... a stupid one, to be honest. Closing the issue.
