### ISSUE TITLE
Unreferenced variable warning

### ISSUE THREAD

**Issue by kennyalive** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#48]
I'd like to make a suggestion to suppress warning C4100 (unreferenced variable) for microsoft compiler or to update code correspondingly. We build our project with 'treat warnings as errors' and to fix build error we have to add #pragma warning( disable : 4100 ) to vk_mem_alloc.h.

**Comment by adam-sawicki-amd** [comment]
C4100 is one of the warnings that are already disabled temporarily for the inclusion of `vk_mem_alloc.h` in the sample application, as you can see in file src\VmaUsage.h. I recommend you do the same in your code.

I don't want to add such directives to the library itself. Maintaining C++ code to compile and work correctly on so many different platforms is hard enough, so I consider being free of any compiler warnings, on any version of any compiler, as not feasible.
