### ISSUE TITLE
Portability issues

### ISSUE THREAD

**Issue by rextimmy** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#5]
If you are compiling with GCC, it doesn't allow anonymous unions to have static data members, these structs need to be declared outside of the anonymous union https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/src/vk_mem_alloc.h#L2303-L2316 .

Also on 64bit linux, uint64_t is an unsigned long int not a unsigned long long int so you get a warning here https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/src/vk_mem_alloc.h#L843

**Comment by adam-sawicki-amd** [comment]
Do you mean that this would solve the problem?
```cpp
struct BlockAllocation
{
	VmaBlock* m_Block;
	VkDeviceSize m_Offset;
};

// Allocation for an object that has its own private VkDeviceMemory.
struct OwnAllocation
{
	uint32_t m_MemoryTypeIndex;
	VkDeviceMemory m_hMemory;
	bool m_PersistentMap;
	void* m_pMappedData;
};

union
{
	// Allocation out of VmaBlock.
	BlockAllocation m_BlockAllocation;
	// Allocation for an object that has its own private VkDeviceMemory.
	OwnAllocation m_OwnAllocation;
};
```

**Comment by rextimmy** [comment]
Yep exactly

**Comment by adam-sawicki-amd** [comment]
Fixed. Thank you for your help.

**Comment by rextimmy** [comment]
No worries, tested and working perfectly on linux with gcc.
