### ISSUE TITLE
Option to avoid including vulkan.h

### ISSUE THREAD

**Issue by baldurk** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#50]
Hey, in my codebase I avoid external dependencies where possible, and the `#include <vulkan/vulkan.h>` means search paths must be set up to point to locate it.

Would it be possible to have a `VMA_NO_INCLUDE_VULKAN_H` or similar option, where I could include `vulkan.h` myself before including `vk_mem_alloc.h`, and then `vk_mem_alloc.h` wouldn't include `vulkan.h` itself at all?

**Comment by adam-sawicki-amd** [comment]
I've changed the code so that Vulkan header is included only `#ifndef VULKAN_H_`. Please let me know if it is fine for you.

**Comment by baldurk** [comment]
That should work fine, thanks!

**Comment by baznzab** [comment]
doesnt vulkan.h itself do it already?:/
