### ISSUE TITLE
windows mingw-w64 cmake got: " not declared in this scope" error

### ISSUE THREAD

**Issue by wumo** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#54]
```
vk_mem_alloc.h:3306:28: error: 'InitializeSRWLock' was not declared in this scope
```

**Comment by wumo** [comment]
context code is here:
```
#elif defined(_WIN32)
        // Use SRWLOCK from WinAPI.
        class VmaRWMutex
        {
        public:
            VmaRWMutex() { InitializeSRWLock(&m_Lock); }
            void LockRead() { AcquireSRWLockShared(&m_Lock); }
            void UnlockRead() { ReleaseSRWLockShared(&m_Lock); }
            void LockWrite() { AcquireSRWLockExclusive(&m_Lock); }
            void UnlockWrite() { ReleaseSRWLockExclusive(&m_Lock); }
        private:
            SRWLOCK m_Lock;
        };
        #define VMA_RW_MUTEX VmaRWMutex
    #else
```

**Comment by turol** [comment]
Just fixed this in my project, you need to `#define _WIN32_WINNT 0x0600 ` somewhere before `windows.h` is included, preferably on the command line. This will tell mingw to enable those functions. As a side effect I think you lose XP support since those were introduced in either Vista or 7.

**Comment by adam-sawicki-amd** [comment]
I've submitted a fix. Please let me know if it fixes the issue for you.

I recommend to define `WINVER` and `_WIN32_WINNT` macros globally for your project to some value indicating usage of some newer WinAPI version, e.g. `0x0600` meaning minimum Windows Vista.
