### ISSUE TITLE
vmaCreateAllocator() crashes on Android

### ISSUE THREAD

**Issue by renelindsay** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#56]
I have a simple Vulkan app which renders a single triangle, and I'm trying to use vma to allocate the vertex buffer.  This works fine on Windows, but crashes with a segmentation fault on Andoid, as soon as I try to create the allocator like this:

    VmaAllocator allocator;
    VmaAllocatorCreateInfo allocatorInfo = {};
    allocatorInfo.physicalDevice = gpu;
    allocatorInfo.device = device;
    vmaCreateAllocator(&allocatorInfo, &allocator);  // CRASH

The error is:
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 20779 (window.Example3)

If I try to debug, the debugger gets stuck at line 14187:
    (*m_VulkanFunctions.vkGetPhysicalDeviceProperties)(m_PhysicalDevice, &m_PhysicalDeviceProperties);

**Comment by renelindsay** [comment]
I found the solution:  
Apparently the internal table of vulkan function pointers are not initialized on Android.  Setting: 
    #define VMA_STATIC_VULKAN_FUNCTIONS 1
didn't help, because the Android compiler doesn't like the syntax of the function that initializes the pointers.   So instead, I have to fill the pointers manually when creating VmaAllocator, like this:

    VmaAllocatorCreateInfo allocatorInfo = {};
    allocatorInfo.physicalDevice = gpu;
    allocatorInfo.device = device;
    allocatorInfo.preferredLargeHeapBlockSize = blockSize;

    VmaVulkanFunctions fn;
    fn.vkAllocateMemory                    = (PFN_vkAllocateMemory)vkAllocateMemory;
    fn.vkBindBufferMemory                  = (PFN_vkBindBufferMemory)vkBindBufferMemory;
    fn.vkBindImageMemory                   = (PFN_vkBindImageMemory)vkBindImageMemory;
    fn.vkCmdCopyBuffer                     = (PFN_vkCmdCopyBuffer)vkCmdCopyBuffer;
    fn.vkCreateBuffer                      = (PFN_vkCreateBuffer)vkCreateBuffer;
    fn.vkCreateImage                       = (PFN_vkCreateImage)vkCreateImage;
    fn.vkDestroyBuffer                     = (PFN_vkDestroyBuffer)vkDestroyBuffer;
    fn.vkDestroyImage                      = (PFN_vkDestroyImage)vkDestroyImage;
    fn.vkFlushMappedMemoryRanges           = (PFN_vkFlushMappedMemoryRanges)vkFlushMappedMemoryRanges;
    fn.vkFreeMemory                        = (PFN_vkFreeMemory)vkFreeMemory;
    fn.vkGetBufferMemoryRequirements       = (PFN_vkGetBufferMemoryRequirements)vkGetBufferMemoryRequirements;
    fn.vkGetImageMemoryRequirements        = (PFN_vkGetImageMemoryRequirements)vkGetImageMemoryRequirements;
    fn.vkGetPhysicalDeviceMemoryProperties = (PFN_vkGetPhysicalDeviceMemoryProperties)vkGetPhysicalDeviceMemoryProperties;
    fn.vkGetPhysicalDeviceProperties       = (PFN_vkGetPhysicalDeviceProperties)vkGetPhysicalDeviceProperties;
    fn.vkInvalidateMappedMemoryRanges      = (PFN_vkInvalidateMappedMemoryRanges)vkInvalidateMappedMemoryRanges;
    fn.vkMapMemory                         = (PFN_vkMapMemory)vkMapMemory;
    fn.vkUnmapMemory                       = (PFN_vkUnmapMemory)vkUnmapMemory;
    fn.vkGetBufferMemoryRequirements2KHR   = 0;  //(PFN_vkGetBufferMemoryRequirements2KHR)vkGetBufferMemoryRequirements2KHR;
    fn.vkGetImageMemoryRequirements2KHR    = 0;  //(PFN_vkGetImageMemoryRequirements2KHR)vkGetImageMemoryRequirements2KHR;
    allocatorInfo.pVulkanFunctions = &fn;

    VmaAllocator allocator;
    vmaCreateAllocator(&allocatorInfo, &allocator);

**Comment by adam-sawicki-amd** [comment]
Thank you for reporting this issue. I've changed the syntax used in function `VmaAllocator_T::ImportVulkanFunctions` like you suggested. Can you please check if the latest version from "master" branch works for you with just `#define VMA_STATIC_VULKAN_FUNCTIONS 1`?

Besides, I would recommend to always first compile and run your program with asserts enabled. If `VMA_ASSERT` was active in the way appropriate to your platform, your issue would be caught at the end of `VmaAllocator_T::ImportVulkanFunctions` function and you wouldn't need to debug the crash that happened later.

**Comment by mgrivich** [comment]
Adam, master is still crashing on Android whether #define VMA_STATIC_VULKAN_FUNCTIONS  is 0 or 1. Renelindsay's workaround still works. I'm guessing ImportVulkanFunctions() has an ordering problem, but I did not grind though the logic to figure it out.

**Comment by adam-sawicki-a** [comment]
@mgrivich I've made some fixes in the master branch. Can you please test on Android whether it solves your problem?

**Comment by adam-sawicki-a** [comment]
I'm closing this issue, but please let me know if there is anything more that can be fixed to make it working on your platform.

**Comment by mgrivich** [comment]
Sorry, I was working on a different project. Your current version still crashes. It can be corrected either by the original workaround, or this new fix:

Add
```
#ifdef __ANDROID__
#define VMA_STATIC_VULKAN_FUNCTIONS 1
#define VK_NO_PROTOTYPES 1
#include <vulkan/vulkan.h>

extern PFN_vkAllocateMemory vkAllocateMemory;
extern PFN_vkBindBufferMemory vkBindBufferMemory;
extern PFN_vkBindImageMemory vkBindImageMemory;
extern PFN_vkCmdCopyBuffer vkCmdCopyBuffer;
extern PFN_vkCreateBuffer vkCreateBuffer;
extern PFN_vkCreateImage vkCreateImage;
extern PFN_vkDestroyBuffer vkDestroyBuffer;
extern PFN_vkDestroyImage vkDestroyImage;
extern PFN_vkFlushMappedMemoryRanges vkFlushMappedMemoryRanges;
extern PFN_vkFreeMemory vkFreeMemory;
extern PFN_vkGetBufferMemoryRequirements vkGetBufferMemoryRequirements;
extern PFN_vkGetImageMemoryRequirements vkGetImageMemoryRequirements;
extern PFN_vkGetPhysicalDeviceMemoryProperties vkGetPhysicalDeviceMemoryProperties;
extern PFN_vkGetPhysicalDeviceProperties vkGetPhysicalDeviceProperties;
extern PFN_vkInvalidateMappedMemoryRanges vkInvalidateMappedMemoryRanges;
extern PFN_vkMapMemory vkMapMemory;
extern PFN_vkUnmapMemory vkUnmapMemory;
extern PFN_vkGetBufferMemoryRequirements2KHR vkGetBufferMemoryRequirements2KHR;
extern PFN_vkGetImageMemoryRequirements2KHR vkGetImageMemoryRequirements2KHR;
extern PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr;
extern PFN_vkGetDeviceProcAddr vkGetDeviceProcAddr;

#endif
```

to the top of vk_mem_alloc.h (right after #define AMD_VULKAN_MEMORY_ALLOCATOR_H). It can't be in the extern C, and the `VK_NO_PROTOTYPES 1`, `#include <vulkan/vulkan.h>`, `extern ...` ordering is required.

This code is extracted from vulkan_wrapper.h/.cpp at https://github.com/KhronosGroup/Vulkan-Tools/tree/master/common

**Comment by adam-sawicki-a** [comment]
Actually, I don't know why did I ever used statically linked functions instead of always fetching them with `vkGetInstanceProcAddr`/`vkGetDeviceProcAddr`. This should work on any platform, right?

Please check the latest code on master branch and see if it works for you.

**Comment by mgrivich** [comment]
I'm getting 

`vk_mem_alloc.h:12739:32: error: use of undeclared identifier 'VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT_KHR'; did you mean 'VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT_KHR'?`

during compilation.

**Comment by adam-sawicki-a** [comment]
How about now? Does it work for you?

**Comment by mgrivich** [comment]
It is crashing with a SIGSEGV. Could I just make a simple Android Studio project for you to test with? You could either buy a cheap Android device or use the free emulators to test.

**Comment by adam-sawicki-a** [comment]
Unfortunately I don't have Android development environment. The library is developed mostly on- and for Windows. Please feel free to propose a pull request with fix.

**Comment by mgrivich** [comment]
Android Studio is free. https://developer.android.com/studio.

I gave you a fix above (the post with the externs), you didn't implement it.

**Comment by adam-sawicki-a** [comment]
OK, I made further changes. I also added `extern` declarations as you proposed above. I think that defining `VK_NO_PROTOTYPES` should be done by the user before including the library. `VMA_STATIC_VULKAN_FUNCTIONS` is defined to 1 by default. Please let me know if it works for you now.

**Comment by majunlichn** [comment]
@adam-sawicki-a I checked the latest version. I think it's better add "#if VMA_DYNAMIC_VULKAN_FUNCTIONS == 1" for "VmaAllocator_T::ImportVulkanFunctions_Dynamic()" (both declaration and definition). Then we don't need to define vkGetInstanceProcAddr and vkGetDeviceProcAddr globally but just provide custom function pointers when create the allocator.

**Comment by adam-sawicki-a** [comment]
Good point, thanks! I made this change.

**Comment by adam-sawicki-a** [comment]
So, what do you think about the current code? Is it working in your environment?

**Comment by adam-sawicki-a** [comment]
I'm closing this ticket due to inactivity for a long time. Please let me know if the issue still needs fixing.

**Comment by adam-sawicki-a** [comment]
I know that there hasn't been an official release for long time and so using latest code from the "master" branch is recommended at the moment. We are working on a major release. It is tracked as #162.

Thank you for your feedback.
