### ISSUE TITLE
Fails to compile on Android

### ISSUE THREAD

**Issue by manaskulkarni786** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#57]
VmaDefragmentationAlgorithm_Generic constructor initializer list should be reversed for 
m_AllocationCount and m_AllAllocations to fix the "m_AllAllocations field will be initialized after m_AllocationCount field" compiler error on Android.

**Comment by adam-sawicki-amd** [comment]
You are right! Thank you for finding this bug. I've fixed it on master branch.
