### ISSUE TITLE
Few unused variables.

### ISSUE THREAD

**Issue by Damianno19** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#58]
You have few unused variables:
`
vk_mem_alloc.h(12288): warning : unused variable 'nonCoherentAtomSize' [-Wunused-variable]
vk_mem_alloc.h(12289): warning : unused variable 'memRange' [-Wunused-variable]
vk_mem_alloc.h(12423): warning : unused variable 'isHostCoherent' [-Wunused-variable]
vk_mem_alloc.h(6414): warning : private field 'm_AlgorithmFlags' is not used [-Wunused-private-field]
`
I opened issue instead pull request because I'm not sure if you left them intentionally, or not.

**Comment by adam-sawicki-amd** [comment]
Thank you for reporting this issue. I fixed it in master branch.
