### ISSUE TITLE
Defragmentation relies on undefined memory aliasing behavior

### ISSUE THREAD

**Issue by jeffbolznv** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#59]
I don't have a reproducer for this, it is just from code inspection.

Defragmentation works by binding a buffer to a block of memory and using that buffer to read the contents originally written through other resources. But if the data was written through an image, then this buffer has undefined contents according to the "Memory Aliasing" section of the Resources chapter, so it may write garbage. It may not even be valid to bind a buffer to this memory, if the buffer doesn't include the memory type in its memoryTypeBits.

This isn't just a theoretical problem, I don't expect these copies to work on NVIDIA's implementation. It may happen to work in some simple cases, but not in general.

**Comment by adam-sawicki-amd** [comment]
Thank you for reporting this issue and for the detailed description. I think you are right, it is a major issue. We will analyze it and go back to it when we find some proposed solution.

**Comment by adam-sawicki-amd** [comment]
I've made a clarification in the documentation stating that only buffers and images with `TILING_LINEAR` and `GENERAL` or `PREINITIALIZED` layout can be defragmented.

I also made a fix that limits GPU defragmentation only to those memory types that support creating a buffer used to do GPU transfers.

Do you think that defragmentation with these limitations is now compliant to Vulkan specification?

**Comment by jeffbolznv** [comment]
Yes, that should be compliant. The pre-edited comment where you mentioned linear images would be as well, since linear images are allowed to alias with buffers.

**Comment by Tobski** [comment]
Hey @jeffbolznv, I suggested @adam-sawicki-amd to remove the linear image part, as linear images still have an expected image "header" with undefined contents - buffers only have defined aliasing over the texel data, which occurs after an implementation defined offset. So that falls under the same conditions as the rest of a regular images AFAICT.

BTW I definitely think we need some spec clarifications here...

**Comment by jeffbolznv** [comment]
OK, fine with me.

I think the spec is fairly clear about what can alias with what in the resources-memory-aliasing section.

**Comment by Tobski** [comment]
Ah I forgot about that language - you're right that's fairly clear.

**Comment by adam-sawicki-amd** [comment]
Thank you for your help with sorting out this issue.

**Comment by adam-sawicki-a** [comment]
Please note a new defragmentation is being developed as #90 !
