### ISSUE TITLE
VulkanMemoryAllocator does not compile with VMA_USE_STL_CONTAINERS

### ISSUE THREAD

**Issue by warrantyvoids** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#60]
VMA doesn't seem to compile under Ubuntu, when VMA_USE_STL_CONTAINERS is defined as 1. The compiler complains about the member 'remove' being unknown for std::vector.

**Comment by adam-sawicki-amd** [comment]
Thank you for fixing this!
