### ISSUE TITLE
how to manage buffer memory for `VK_NV_RAY_TRACING` AccelerationStructure

### ISSUE THREAD

**Issue by wumo** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#63]
`AccelerationStructureMemory` uses `vkGetAccelerationStructureMemoryRequirementsNV` to get `VkMemoryRequirements2` and uses `vkBindAccelerationStructureMemoryNV` to bind memory. Allocating memory is the same as usual by calling `vkAllocateMemory`.
I want to let `vma` to manage the memory for me, but apparently I cannot just `vmaCreateBuffer()` as before. `vkGetAccelerationStructureMemoryRequirementsNV` and `vkBindAccelerationStructureMemoryNV` should be involved somewhere where I don't know.
I can manually create buffer, allocate memory and bind memory, but I hope `vma` will choose the memoryType for me and destory the buffer when it is no longer referenced. What are the necessary functions that must be called to achieve this?

**Comment by adam-sawicki-amd** [comment]
VK_NV_ray_tracing is a custom extension from Nvidia, not part of core Vulkan API and as such it's not directly supported by VMA. To use VMA to allocate memory for acceleration structure, use following steps:

1. Call `vkCreateAccelerationStructureNV`, get your `VkAccelerationStructureNV accelStruct`.
2. Call `vkGetAccelerationStructureMemoryRequirementsNV`, get `VkMemoryRequirements2KHR memReq`.
3. Fill `VmaAllocationCreateInfo allocCreateInfo`: set `memoryTypeBits = memReq.memoryTypeBits`, set rest of fields to zero.
4. Call `vmaAllocateMemory` - pass your `memReq.memoryRequirements` along with `allocCreateInfo`, get your `VmaAllocation alloc` and `VmaAllocationInfo allocInfo`.
5. Call `vkBindAccelerationStructureMemoryNV` to bind your `accelStruct` to `allocInfo.deviceMemory`, `allocInfo.offset`.

This is all assuming that you do all your memory allocation, mapping, and binding on one thread. If you use multiple threads, then please note that a memory for different acceleration structures or regular buffers and images may come from a single device memory block. Binding is synchronized internally when using functions like `vmaCreateBuffer` or `vmaBindBufferMemory`, but not when you call Vulkan function directly, like `vkBindAccelerationStructureMemoryNV`. In that case you need to either protect any allocation/mapping/binding with a mutex on your own, or use separate custom `VmaPool` for your resources used on one thread, or create each such allocation as `  VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT`.

Don't forget to destroy both acceleration structure and the allocation when no longer needed, using functions `vkDestroyAccelerationStructureNV`, `vmaFreeMemory` respectively.
