### ISSUE TITLE
-Wunused-private-field (Clang / Xcode)

### ISSUE THREAD

**Issue by past-due** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#65]
Working on a project with many warnings enabled (and treated as errors). Here is the `-Wunused-private-field` that shows up with the current master branch.

```
vk_mem_alloc.h:6434:20: error: private field 'm_AlgorithmFlags' is not used [-Werror,-Wunused-private-field]
    const uint32_t m_AlgorithmFlags;
```

**Comment by adam-sawicki-amd** [comment]
OK, you are right. I fixed it on "master" branch.
