### ISSUE TITLE
-Wunused-variable (Clang / Xcode / GCC)

### ISSUE THREAD

**Issue by past-due** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#67]
Working on a project with many warnings enabled (and treated as errors). Here are the `-Wunused-variable` warnings that show up with the current master branch.

```
vk_mem_alloc.h:10344:38: error: unused variable 'suballocations1st' [-Werror,-Wunused-variable]
            SuballocationVectorType& suballocations1st = AccessSuballocations1st();
                                     ^
vk_mem_alloc.h:11910:34: error: unused variable 'res' [-Werror,-Wunused-variable]
                        VkResult res = pBestRequestBlock->WriteMagicValueAroundAllocation(m_hAllocator, bestRequest.offset, size);
                                 ^
vk_mem_alloc.h:11948:22: error: unused variable 'res' [-Werror,-Wunused-variable]
            VkResult res = pBlock->ValidateMagicValueAroundAllocation(m_hAllocator, hAllocation->GetOffset(), hAllocation->GetSize());
                     ^
vk_mem_alloc.h:12112:22: error: unused variable 'res' [-Werror,-Wunused-variable]
            VkResult res = pBlock->WriteMagicValueAroundAllocation(m_hAllocator, currRequest.offset, size);
                     ^
vk_mem_alloc.h:12452:16: error: unused variable 'isHostCoherent' [-Werror,-Wunused-variable]
    const bool isHostCoherent = (memPropFlags & VK_MEMORY_PROPERTY_HOST_COHERENT_BIT) != 0;
               ^
vk_mem_alloc.h:15252:14: error: unused variable 'success' [-Werror,-Wunused-variable]
        bool success = VmaVectorRemoveSorted<VmaPointerLess>(m_Pools, pool);
             ^
vk_mem_alloc.h:15574:14: error: unused variable 'success' [-Werror,-Wunused-variable]
        bool success = VmaVectorRemoveSorted<VmaPointerLess>(*pDedicatedAllocations, allocation);
```

**Comment by adam-sawicki-amd** [comment]
Regarding `isHostCoherent`: you are right, this variable was unused. I removed it.

All other variables are used as long as `VMA_ASSERT` is not empty - which I highly recommend.

Personally I would say enabling and putting asserts in the code is more important than enabling such restrictive compiler warnings :)

**Comment by past-due** [comment]
> Regarding `isHostCoherent`: you are right, this variable was unused. I removed it.
> 
> All other mentioned variables are used as long as `VMA_ASSERT` is not empty - which I highly recommend.
> 

Yep - we'll be defining `VMA_ASSERT`. 👍 

> Personally I would say enabling and putting asserts in the code is more important than enabling such restrictive compiler warnings :)

While there is a brief mention in the [Configuration](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/configuration.html) section of the documentation, it might be worth adding a more explicit recommendation around defining `VMA_ASSERT` to the generated docs?

**Comment by adam-sawicki-amd** [comment]
You are right. I added this information to the documentation.
