### ISSUE TITLE
Remove dependency on windows.h

### ISSUE THREAD

**Issue by jesta88** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#72]
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/195016b0348038537dbd73d45d6ccaf795bfb367/src/vk_mem_alloc.h#L1698

For those who want to use VMA without pulling windows.h or having Vulkan already included, it would be nice to remove this line and replace it with this:
```
#ifndef VULKAN_H_
#	ifdef VK_USE_PLATFORM_WIN32_KHR
#		include <vulkan/vk_platform.h>
#		include <vulkan/vulkan_core.h>

		typedef unsigned long DWORD;
		typedef const wchar_t* LPCWSTR;
		typedef void* HANDLE;
		typedef struct HINSTANCE__* HINSTANCE;
		typedef struct HWND__* HWND;
		typedef struct HMONITOR__* HMONITOR;
		typedef struct _SECURITY_ATTRIBUTES SECURITY_ATTRIBUTES;

#		include <vulkan/vulkan_win32.h>
#	else
#		include <vulkan/vulkan.h>
#	endif
#endif
```
Then in the implementation part, either include windows.h or even better, only use the necessary win32 stuff. 

This saves ~200ms when parsing.

**Comment by res2k** [comment]
This approach can break under several circumstances:
* When `vulkan_win32.h` is changed and makes use of additional Windows types: they're not found.
* Those `typedef`s are, strictly speaking, `windows.h` implementation details: They may change in some future SDK update.
* There may be some other conflicts if `windows.h` is included before or after that bit.

While you may be able to live with the limitations, they're somewhat unsuited for a header that should work in a wide variety of projects.

**Comment by jesta88** [comment]
Yes these are the risks. Other popular vulkan libraries opted to remove windows.h anyways because realistically, this should be extremely rare (if ever, in the lifetime of a major Vulkan version) and is trivial to fix.

I understand if the owners don't see it that way though.

**Comment by res2k** [comment]
If I wanted to get rid of `windows.h` but keep `VK_USE_PLATFORM_WIN32_KHR`, I might create a wrapper header that does something like you did above, with a `#define VULKAN_H_` after `#include <vulkan/vulkan_win32.h>` and immediately including `vk_mem_alloc.h`. It should give the result you desire.

If you name your wrapper `vk_mem_alloc.h` (with the "real" header named differently, of course) you'll even get a transparent solution.

**Comment by adam-sawicki-amd** [comment]
In my opinion @res2k is right. The solution proposed is a hack and may not be reliable or future-proof. If Vulkan header includes "windows.h" then please contact the developers of Vulkan SDK with request to change that.

Many Windows applications include and use "windows.h" anyway. To speed up compilation under Visual Studio I recommend putting it in precompiled header.
