### ISSUE TITLE
C++ bindings à la Vulkan-Hpp

### ISSUE THREAD

**Issue by malte-v** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#77]
I think it would be great to have C++ bindings for VMA that incorporate the types defined in `vulkan.hpp` (e.g. functions return a `vk::Result`, not a `VkResult`). At the moment, you constantly have to switch between the C/C++ types when using this library with Vulkan-Hpp. I find it really inconsistent and annoying to work with. Type-safe bindings would most probably make many C++ programmers happy!

**Comment by adam-sawicki-amd** [comment]
C++ binding for this library has been created as external project:
https://github.com/malte-v/VulkanMemoryAllocator-Hpp
