### ISSUE TITLE
how should I update a uniform buffer

### ISSUE THREAD

**Issue by dodoleon** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#78]
In my engine, there are many uniform buffer. But i don't update these every frame.
When I update uniform buffer by Stage buffer, it work well. But update uniform buffer by getting pMappedData through vmaMapMemory, the result will flicker. 
BTW, In a simple demo as vulkan-tutorial, vmaMapMemory work well.
This is how I create Buffer.
```c++
VmaAllocationCreateInfo allocInfo{};
allocInfo.usage = VMA_MEMORY_USAGE_CPU_TO_GPU;
VkBuffer buffer;
auto & LogicalDevice = pRenderDeviceVk->GetLogicalDevice();
vmaCreateBuffer(LogicalDevice.GetVmaAlloctor(), &VkBuffCI, &allocInfo, &buffer, &m_GPUMemory, &info);
```
I want to know what may happened, when I update uniform buffer.
What interesting is that not flicker launched by renderdoc.

error uniform buffer.
0 3: MaterialUniforms ResourceId::447 0 - 448 81 Variables, 452 bytes needed, 448 provided

The bad result:
![image](https://user-images.githubusercontent.com/5832870/65309201-302c7580-dbbe-11e9-8b12-b2e0f8a71a39.png)
![image](https://user-images.githubusercontent.com/5832870/65309224-39b5dd80-dbbe-11e9-948b-04ab4afd2250.png)

**Comment by adam-sawicki-amd** [comment]
If you use single `VkBuffer` that you map and update on CPU, as well as use for rendering on the GPU, please make sure you don't access its content at the same time. Remember that GPU works asynchronously to the CPU - it is rendering previous frame while your C++ code is already preparing new frame. So in such use case you need to double- or triple-buffer such buffers just as you do for swap chain images, command buffers etc., so e.g. you update buffer 0 on CPU while buffer 1 is being used for rendering on GPU and then you swap them.

**Comment by dodoleon** [comment]
Thank you @adam-sawicki-amd . It make scenes. When I use stage buffer, will call buffer Barrier. So it will work well.
