### ISSUE TITLE
Add xml description file in Vulkan style

### ISSUE THREAD

**Issue by realitix** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#8]
Hello,

I'm the author of the Vulkan wrapper for Python [https://github.com/realitix/vulkan](https://github.com/realitix/vulkan). It works by parsing the `vk.xml` file. Lot of wrappers are generated this way.

**Proposal**

Adding an XML file that follows the `vk.xml` format would allow to easily write a wrapper for your library. @Berserker66 [requested](https://github.com/realitix/vulkan/issues/29) a wrapper for your library and I think that lot of people could be interested in.
Your library is becoming the reference as Vulkan memory allocator.

What do you think about this idea ?

**Comment by adam-sawicki-amd** [comment]
Creating wrapper for Python is a great idea, but I'm afraid that creating wrappers for programming languages other than C++ is out of scope of this project. External contributions of this type are welcomed.

I would recommend to wait with creating such wrapper until new version 2.0.0-alpha.3 is released, which should happen pretty soon. It brings a lot of changes.

**Comment by realitix** [comment]
Thanks @adam-sawicki-amd for your answer.
I agree with you that creating a wrapper is out of scope of this project. However, creating a file that describes the API may be a good idea. Like you said, it takes time to do it and we have to wait the version 2-alpha3.
I can create the wrapper without the description file so it's not a big problem but it's more convenient with it.

**Comment by adam-sawicki-amd** [comment]
I pushed version 2.0.0-alpha.3. Can you try to prepare Python wrapper for it?

**Comment by realitix** [comment]
Thanks @adam-sawicki-amd, can you give me instruction to compile the code as a static library ?

**Comment by adam-sawicki-amd** [comment]
If you mean Windows and Visual Studio platform, in order to compile VMA as static library:

- Create new project of type "Static library".
- Add `vk_mem_alloc.h` file to it.
- Create `vk_mem_alloc.cpp` file and place following code there:

```cpp
#define VMA_IMPLEMENTATION
#include "vk_mem_alloc.h"
```

**Comment by realitix** [comment]
Sorry, I forgot to tell you that I work on Linux (Ubuntu). So do you know how to do it on linux ?

**Comment by realitix** [comment]
I just saw that all is in one file `vk_mem_alloc.h`, nice!
Is `mathfu` mandatory ?

**Comment by adam-sawicki-amd** [comment]
Yes, the whole library is in file `vk_mem_alloc.h`. It depends only on Vulkan and standard C/C++ library. When included as-is, it works as a header. When included after `#define VMA_IMPLEMENTATION` from some CPP file, it adds whole implementation, so you should do it just once. All the rest is just testing app, including MathFu.

**Comment by realitix** [comment]
Ok very nice, I love well designed library. I'm starting the wrapper.

**Comment by FlayaN** [comment]
@realitix Are you making the vma.xml file or directly for python?
I would love a spec aswell to make a version of [KhronosGroup/Vulkan-Hpp](https://github.com/KhronosGroup/Vulkan-Hpp) for this repo

So I can use this library like this: 
```
auto memReq = vma::AllocationCreateInfo({}, vma::MemoryUsage::eGpuOnly)
   .setPool(&pool);
```
etc..

**Comment by realitix** [comment]
@FlayaN I am directly doing the python wrapper for testing.
If it's good, we should capitalize on the xml file.

I'm currently locked by this: https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/10

**Comment by realitix** [comment]
Here the Python Wrapper (WIP): https://github.com/realitix/pyvma
