### ISSUE TITLE
Associate debug name with VmaPool

### ISSUE THREAD

**Issue by kennyalive** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#82]
It would be nice to be able to associate names with custom pools so Dump Vis tool can use those names instead of generic 'Custom pool 17'. In our application we create a bunch of VmaPools for different purposes but it's hard to distinguish them in generated image. This would be invaluable for debugging when you see some unusual allocation pattern in a pool and the name will provide immediate information which type of allocation causes that behavior.

**Comment by adam-sawicki-a** [comment]
Thank you for this suggestion. I think it's a good idea and simple to implement. I will implement it soon.

**Comment by adam-sawicki-a** [comment]
I implemented this on master branch. Please check if it solves your issue.

**Comment by kennyalive** [comment]
It works for me. Thanks!
One thing that confused me at the beginning is that pool index is in the quotes and some of our pools have names that are numbers or just few letters mnemonics... so it looks like this: _Custom pool "5 64"_ or _Custom pool "1 m"_. Personally I would prefer _Custom pool 1 "m"_ if name is provided and _Custsom pool 5_ for pools without name (original naming).

**Comment by adam-sawicki-a** [comment]
I changed it the way you described. Please take a look at the latest version.

**Comment by kennyalive** [comment]
Works as expected. Thanks for implementing this.
