### ISSUE TITLE
nonCoherentAtomSize and allocation size

### ISSUE THREAD

**Issue by kennyalive** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#83]
Does the library guarantee that for non-coherent host visible memory _allocation size_ will be multiple of nonCoherentAtomSize?
From implementation I can see that allocation _offset_ is aligned according to nonCoherentAtomSize but I can't figure out if _size_ is also adjusted. I've checked documentation for vkGetXXXMemoryRequirement functions and it doesn't mention that returned size takes into account potential usage of non-coherent memory and any guarantee that size will be multiple of nonCoherentAtomSize.

**Comment by adam-sawicki-a** [comment]
You are right. Allocation size is not aligned to nonCoherentAtomSize and neither is the size of entire VkDeviceMemory block, but I think that's OK. All allocations in a non-coherent memory type are aligned to nonCoherentAtomSize, so there is never a situation where two allocations share same "atom size". Flush/Invalidate calls align their offset and size to nonCoherentAtomSize.

If you find a proof that this behavior is wrong according to Vulkan spec and should be changed, please let me know.
