### ISSUE TITLE
Transient/lazy memory doesn't appear to be handled

### ISSUE THREAD

**Issue by gary-sweet** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#84]
Used in the right way, transient allocations can mean that tile-based renderers may never actually have to allocate memory for certain buffers - depth being a prime example.

As far as I can see, VMA has no mechanism for marking memory as transient and dealing with it differently. It definitely does not want to be pulled from a pool of already allocated memory. Only the driver knows when transient memory actually needs to be allocated, so any lazy allocations really need to be given directly to the driver to handle.

Obviously, an application could choose to handle lazy memory itself and bypass VMA for such allocations, but that sort of defeats the object of having a nice library handle your memory for you.

**Comment by adam-sawicki-a** [comment]
You are right, transient/lazy memory is not handled in any special way in VMA at the moment. I may add something to the library to support it. How would you like the API for that to look like?

**Comment by gary-sweet** [comment]
The details of the API I'll leave to you. I've not been a direct user of VMA myself - I'm a Vulkan driver engineer primarily, but was also involved in the recent Khronos Vulkan-Samples repo which uses VMA. That's where I realised that transient memory handling was missing.

I suspect you'll just want a flag for transient allocations in VmaAllocationCreateFlagBits (very similar to VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT). Allocations marked as such should not be pooled, but just be a single driver allocation wrapped in a VmaAllocation for return.

**Comment by adam-sawicki-a** [comment]
I've updated master branch, added new memory usage enum value `VMA_MEMORY_USAGE_GPU_LAZILY_ALLOCATED` that looks for memory type with `VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT` and also implies dedicated allocation. Please let me know what you think.
