### ISSUE TITLE
Small inquiry about header including

### ISSUE THREAD

**Issue by mlfarrell** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#85]
Amazing library btw.  I'm moving off of my homebrew memory manager to yours (it served its purpose well while it lasted).

Quick q - I'm concerned about including a gigantic header in my files that use my engine.  Is there a way to forward-declare the type handles I need, VmaAllocator, VmaPool, and VmaAllocation so I can match it up with my memory manager implementation that includes vk_mem_alloc.h?

Ideally, i'd forward declare the memory manager class that I use, but I've abstracted my suballocation type as a nested type of that class, so I'm kinda stuck for awhile with it.

**Comment by adam-sawicki-a** [comment]
Thanks for the feedback. I'm glad you like the library.

VMA was designed to be a single-header "STB-style" library, meaning all declarations, private implementation, and documentation, are in one file, which has its pros and cons.

I hope you already know that the "vk_mem_alloc.h" included normal way contains just basic types and function declarations, and there are not so many of them, while full implementation is under `#ifdef`, to be enabled in just one C++ file.

I think it shouldn't be a performance issue during compilation. Processing file that contains large number of lines, especially if disabled by preprocessor, is not definitive factor for slow C++ compilation comparing to other steps, like linking.

If you really need to, you can predefine types from VMA on your own:

```cpp
struct VmaAllocation_T;
VK_DEFINE_HANDLE(VmaAllocation)
```

Or, if you don't want to include Vulkan header either:

```cpp
typedef struct VmaAllocation_T* VmaAllocation;
```

The problem you describe is not specific to VMA but a general issue with C++ language, where you need to expose private members of your class in a header file, make sure their types are defined etc. Nested types are particularly bad for this reason. You can prevent it in many ways, e.g.:

- Use plain C - global functions as an interface of the modules of your program
- Use "pimpl" design pattern
