### ISSUE TITLE
Memory flushing is poorly documented!

### ISSUE THREAD

**Issue by ROTARTSI82** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#91]
I have a question and could not find documentation so I was hoping to get it answered and documented.

How do I flush memory? Are `vkFlushMappedMemoryRanges` and `vkInvalidateMappedMemoryRanges` automatically called on unmap? Do I have to include the `VK_MEMORY_PROPERTY_HOST_COHERENT_BIT` flag?

**Comment by ROTARTSI82** [comment]
Oop! I didn't see `vmaFlushAllocation` ;P. I was searching for "flush" in the documentation and didn't get any results. Doxygen is weird.

**Comment by adam-sawicki-a** [comment]
Thanks for your suggestion. I clarified documentation regarding memory flush/invalidate in few places. Hopefully it will now be easier to find.
