### ISSUE TITLE
Validation warnings about vkFlushMappedMemoryRanges

### ISSUE THREAD

**Issue by jkunstwald** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#93]
Upon startup i receive three validation warnings when launching via Renderdoc.
ID 687 (once), warning that `Offset` in `pMemRanges[0]` in a `vkFlushMappedMemoryRanges` call is 0x400003, which is not a multiple of `VkPhysicalDeviceLimits::nonCoherentAtomSize` (which is 64)
and ID 1390 (twice), warning that `Size` in `pMemRanges[0]` is 0x3FFFFD and 0x8FE39D respectively, which is again not a multiple of 64. Curiously i do not receive these warnings with enabled validation layers outside of renderdoc.

**Comment by adam-sawicki-a** [comment]
What platform is this? Can you please also check what memory type is selected for the culprit allocation, what flags does it have?

If that's a PC then it might be a bug in RenderDoc or Validation Layers, as currently all 3 PC GPU vendors (AMD, NVIDIA, Intel) provide all their Vulkan memory types that are `HOST_VISIBLE` also as `HOST_COHERENT`, while `nonCoherentAtomSize` must be respected only when this flag is not present. Per Vulkan spec chapter 10.2.1:

> If the device memory was allocated without the VK_MEMORY_PROPERTY_HOST_COHERENT_BIT set, these guarantees must be made for an extended range: the application must round down the start of the range to the nearest multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize, and round the end of the range up to the nearest multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize.

How do you flush/invalidate mapped memory? Using `vkFlush...` or `vmaFlush...` functions? Or are you not doing those at all, but rather they are added by RenderDoc?

**Comment by jkunstwald** [comment]
Yes, sorry, this is:
Win10 1909, RTX 2080, driver 441.66
Renderdoc 1.5, Vulkan 1.1

I am not using `vmaFlush...` or `vkFlush...`, and the only mapped resources i create are allocated using VMA, and as such:
```C++
    VkBufferCreateInfo buffer_info = {};
    buffer_info.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
    buffer_info.size = size_bytes;
    buffer_info.usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT
                        | VK_BUFFER_USAGE_INDEX_BUFFER_BIT | VK_BUFFER_USAGE_VERTEX_BUFFER_BIT | VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT;

    VmaAllocationCreateInfo alloc_info = {};
    alloc_info.usage = VMA_MEMORY_USAGE_CPU_TO_GPU;
    alloc_info.flags = VMA_ALLOCATION_CREATE_MAPPED_BIT;

    VmaAllocation res_alloc;
    VmaAllocationInfo res_alloc_info;
    VkBuffer res_buffer;
    PR_VK_VERIFY_SUCCESS(vmaCreateBuffer(mAllocator.getAllocator(), &buffer_info, &alloc_info, &res_buffer, &res_alloc, &res_alloc_info));
```

**Comment by adam-sawicki-a** [comment]
OK then it must be RenderDoc issuing some `vkFlush...` calls. Summoning @baldurk.

Question is if that's a bug in RenderDoc or Vulkan Validation Layer. I bet the latter, as Vulkan spec says only those memory types that don't have `HOST_COHERENT` flag need to align their flush/invalidate to `nonCoherentAtomSize`.

I'm closing the ticket as it is not related to VMA directly.
