### ISSUE TITLE
How to get the size of the whole VkDeviceMemory associated with an allocation?

### ISSUE THREAD

**Issue by malte-v** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#96]
Is it possible to get the size of the whole VkDeviceMemory associated with an allocation without creating a pool with an explicit block size? I need this for importing a Vulkan memory object into OpenGL, and OpenGL needs to know the size of the whole memory object. Thanks!

**Comment by adam-sawicki-a** [comment]
Currently this information is not available through VMA interface as it was never needed. What specific Vulkan features do you use for importing memory? I thought that memory export/import requires having dedicated allocation just for your resource, and not part of a bigger block. For dedicated allocations, `VkDeviceMemory` block size is same as you requested.

**Comment by malte-v** [comment]
The `VkDeviceMemory` size is needed on the OpenGL side of things (for example in `void ImportMemoryFdEXT(uint memory, **uint64 size**, enum handleType, int fd)`).

I totally forgot that I could just directly allocate the external memory as usual without going through VMA. Since importing Vulkan memory into other APIs is the only use case for this I can think of, I'll close this now. This feature is unneeded, as you said.

**Comment by adam-sawicki-a** [comment]
That's right. It is also documented in chapter "Features not supported":
https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/general_considerations.html#general_considerations_features_not_supported

If you still want VMA to track such allocations, you can create them with `VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT`, which guarantees that the resource will get its own memory block and its size will be exactly as requested.
