### ISSUE TITLE
`VkDevice` (or `m_hDevice`) gettting from `VmaAllocator`

### ISSUE THREAD

**Issue by helixd-2k18** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#99]
Hello, I want to ask question. Why VMA doesn't implemented `m_hDevice` getter for return `VkDevice`. I tried access with tricks directly to `m_hDevice`, but always (when used more than one `.cpp` file) getting `incomplete type` or `symbol not found`...

**Comment by adam-sawicki-a** [comment]
Hello, I've added function `vmaGetAllocatorInfo`. Does it solve your issue?
